### ISSUE TITLE
<TargetFrameworks> causes Object null reference exception

### ISSUE THREAD

**Issue by csMACnz** [stryker-mutator/stryker-net#130]
When running against a test project using `<TargetFrameworks>` instead of `<TargetFramework>` causes a `System.NullReferenceException`.

```
[14:39:28 DBG] Determining project under test with name filter null
[14:39:28 ERR] An error occurred during the mutationtest run
System.NullReferenceException: Object reference not set to an instance of an object.
   at Stryker.Core.Initialisation.ProjectFileReader.FindTargetFrameworkReference(XDocument document)
   at Stryker.Core.Initialisation.ProjectFileReader.ReadProjectFile(XDocument projectFileContents, String projectUnderTestNameFilter)
   at Stryker.Core.Initialisation.InputFileResolver.ReadProjectFile(String projectFilePath, String projectName)
   at Stryker.Core.Initialisation.InputFileResolver.ResolveInput(String currentDirectory, String projectName)
   at Stryker.Core.Initialisation.InitialisationProcess.Initialize(StrykerOptions options)
   at Stryker.Core.StrykerRunner.RunMutationTest(StrykerOptions options)
[14:39:28 INF] Time Elapsed 00:00:00.2799214
```

The only indication that the issue is the `TargetFramework` is that the stack trace fails on `FindTargetFrameworkReference`.  This could do with a better messaging if you only support targeting one framework, or better support when `TargetFrameworks` is used.

**Comment by Jacrys** [comment]
looking at this...

**Comment by Mobrockers** [comment]
Issue closed by pull request as for now we have decided we only really need to support one target framework, so we will just take the first one we find if multiple are available.
