### ISSUE TITLE
'dotnet stryker' results in System.ArgumentException:  (Parameter 'annotations')

### ISSUE THREAD

**Issue by dsibinski** [stryker-mutator/stryker-net#1339]
**Describe the bug**
From time to time, randomly (let's say once per 5 runs) when running `dotnet stryker` I'm getting an exception.
When I re-run the command it normally works fine straight after.

**Logs**
Console output after running `dotner stryker`:
 
```
Version: 0.20.0 (beta)

[13:40:44 INF] Identifying project to mutate.
[13:40:46 INF] The project D:\Dev\MyProject\MyProject.csproj will be mutated.
[13:40:48 INF] Analysis complete.
[13:40:48 INF] Building test project D:\Dev\MyProject\Tests\MyProject.Tests\MyProject.Tests.csproj (1/1)
[13:41:58 INF] Initializing test runners (VsTest)
[13:42:00 INF] Test runners are ready
[13:42:01 INF] Total number of tests found: 29
[13:42:01 INF] Initial testrun started
[13:42:02 INF] Using 12326 ms as testrun timeout
[13:42:20 ERR] An error occurred during the mutation test run
System.ArgumentException:  (Parameter 'annotations')
   at Microsoft.CodeAnalysis.GreenNode..ctor(UInt16 kind, DiagnosticInfo[] diagnostics, SyntaxAnnotation[] annotations)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LocalDeclarationStatementSyntax..ctor(SyntaxKind kind, GreenNode attributeLists, SyntaxToken awaitKeyword, SyntaxToken usingKeyword, GreenNode modifiers, VariableDeclarationSyntax declaration, SyntaxToken semicolonToken, DiagnosticInfo[] diagnostics, SyntaxAnnotation[] annotations)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LocalDeclarationStatementSyntax.SetAnnotations(SyntaxAnnotation[] annotations)
   at Microsoft.CodeAnalysis.GreenNodeExtensions.WithAdditionalAnnotationsGreen[TNode](TNode node, IEnumerable`1 annotations)
   at Microsoft.CodeAnalysis.SyntaxNode.WithAdditionalAnnotationsInternal(IEnumerable`1 annotations)
   at Microsoft.CodeAnalysis.AnnotationExtensions.WithAdditionalAnnotations[TNode](TNode node, SyntaxAnnotation[] annotations)
   at Microsoft.CodeAnalysis.SyntaxNodeExtensions.<>c__37`1.<TrackNodes>b__37_0(SyntaxNode n, SyntaxNode r)
   at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxReplacer.Replacer`1.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitListElement[TNode](TNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitBlock(BlockSyntax node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxReplacer.Replacer`1.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode.ReplaceCore[TNode](IEnumerable`1 nodes, Func`3 computeReplacementNode, IEnumerable`1 tokens, Func`3 computeReplacementToken, IEnumerable`1 trivia, Func`3 computeReplacementTrivia)
   at Microsoft.CodeAnalysis.SyntaxNodeExtensions.ReplaceNodes[TRoot,TNode](TRoot root, IEnumerable`1 nodes, Func`3 computeReplacementNode)
   at Stryker.Core.Mutants.MutationContext.MutateNodeAndChildren(SyntaxNode node, Boolean statementLevelControlled) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\MutationContext.cs:line 88
   at Stryker.Core.Mutants.NodeOrchestrators.SyntaxNodeOrchestrator.OrchestrateMutation(SyntaxNode node, MutationContext context) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\NodeOrchestrators\SyntaxNodeOrchestrator.cs:line 9
   at Stryker.Core.Mutants.NodeOrchestrators.NodeSpecificOrchestrator`1.Mutate(SyntaxNode node, MutationContext context) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\NodeOrchestrators\NodeSpecificOrchestrator.cs:line 18
   at Stryker.Core.Mutants.MutantOrchestrator.Mutate(SyntaxNode currentNode, MutationContext context) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\MutantOrchestrator.cs:line 120
   at Stryker.Core.Mutants.MutationContext.Mutate(SyntaxNode subNode) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\MutationContext.cs:line 39
   at Stryker.Core.Mutants.MutationContext.MutateNodeAndChildren(SyntaxNode node, Boolean statementLevelControlled) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\MutationContext.cs:line 94
   at Stryker.Core.Mutants.NodeOrchestrators.MethodDeclarationOrchestrator.OrchestrateMutation(MethodDeclarationSyntax node, MutationContext context) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\NodeOrchestrators\MethodDeclarationOrchestrator.cs:line 17
   at Stryker.Core.Mutants.NodeOrchestrators.NodeSpecificOrchestrator`1.Mutate(SyntaxNode node, MutationContext context) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\NodeOrchestrators\NodeSpecificOrchestrator.cs:line 18
   at Stryker.Core.Mutants.MutantOrchestrator.Mutate(SyntaxNode currentNode, MutationContext context) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\MutantOrchestrator.cs:line 120
   at Stryker.Core.Mutants.MutationContext.Mutate(SyntaxNode subNode) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\MutationContext.cs:line 34
   at Stryker.Core.Mutants.MutationContext.MutateNodeAndChildren(SyntaxNode node, Boolean statementLevelControlled) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\MutationContext.cs:line 94
   at Stryker.Core.Mutants.NodeOrchestrators.SyntaxNodeOrchestrator.OrchestrateMutation(SyntaxNode node, MutationContext context) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\NodeOrchestrators\SyntaxNodeOrchestrator.cs:line 9
   at Stryker.Core.Mutants.NodeOrchestrators.NodeSpecificOrchestrator`1.Mutate(SyntaxNode node, MutationContext context) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\NodeOrchestrators\NodeSpecificOrchestrator.cs:line 18
   at Stryker.Core.Mutants.MutantOrchestrator.Mutate(SyntaxNode currentNode, MutationContext context) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\MutantOrchestrator.cs:line 120
   at Stryker.Core.Mutants.MutationContext.Mutate(SyntaxNode subNode) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\MutationContext.cs:line 34
   at Stryker.Core.Mutants.MutationContext.MutateNodeAndChildren(SyntaxNode node, Boolean statementLevelControlled) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\MutationContext.cs:line 94
   at Stryker.Core.Mutants.NodeOrchestrators.SyntaxNodeOrchestrator.OrchestrateMutation(SyntaxNode node, MutationContext context) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\NodeOrchestrators\SyntaxNodeOrchestrator.cs:line 9
   at Stryker.Core.Mutants.NodeOrchestrators.NodeSpecificOrchestrator`1.Mutate(SyntaxNode node, MutationContext context) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\NodeOrchestrators\NodeSpecificOrchestrator.cs:line 18
   at Stryker.Core.Mutants.MutantOrchestrator.Mutate(SyntaxNode currentNode, MutationContext context) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\MutantOrchestrator.cs:line 120
   at Stryker.Core.Mutants.MutationContext.Mutate(SyntaxNode subNode) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\MutationContext.cs:line 34
   at Stryker.Core.Mutants.MutationContext.MutateNodeAndChildren(SyntaxNode node, Boolean statementLevelControlled) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\MutationContext.cs:line 94
   at Stryker.Core.Mutants.NodeOrchestrators.SyntaxNodeOrchestrator.OrchestrateMutation(SyntaxNode node, MutationContext context) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\NodeOrchestrators\SyntaxNodeOrchestrator.cs:line 9
   at Stryker.Core.Mutants.NodeOrchestrators.NodeSpecificOrchestrator`1.Mutate(SyntaxNode node, MutationContext context) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\NodeOrchestrators\NodeSpecificOrchestrator.cs:line 18
   at Stryker.Core.Mutants.MutantOrchestrator.Mutate(SyntaxNode currentNode, MutationContext context) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\MutantOrchestrator.cs:line 120
   at Stryker.Core.Mutants.MutantOrchestrator.Mutate(SyntaxNode currentNode) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\MutantOrchestrator.cs:line 106
   at Stryker.Core.MutationTest.MutationTestProcess.Mutate() in D:\a\1\s\src\Stryker.Core\Stryker.Core\MutationTest\MutationTestProcess.cs:line 72
   at Stryker.Core.StrykerRunner.RunMutationTest(StrykerOptions options, IEnumerable`1 initialLogMessages) in D:\a\1\s\src\Stryker.Core\Stryker.Core\StrykerRunner.cs:line 78
```

So far I didn't manage to reproduce this running `dotnet stryker --log-file`, so no log file attached.

**Expected behavior**
No exception should be thrown.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Type of project: .NET Framework
 - Framework Version: 4.8
 - Stryker Version beta 0.20.0

**Comment by Mobrockers** [comment]
Thank you for the report!

**Comment by Mobrockers** [comment]
@dsibinski can you check if this still occurs with the latest version of Stryker? There was an update to the compiler package.

**Comment by mm-dsibinski** [comment]
Hi @Mobrockers ,
I haven't noticed this issue on the new Stryker version so far 😉 Looks good!

**Comment by Mobrockers** [comment]
Good to hear!
