### ISSUE TITLE
Cannot inject mutation error since 0.21

### ISSUE THREAD

**Issue by Dave-EMIS** [stryker-mutator/stryker-net#1386]
**Describe the bug**
Since updating to 0.21.0 (and 21.1) from 0.20.0 Stryker fails on every run with an exception.

**Logs**

I'm working on the log files (the failures were on Jenkins), the exception / stack trace are:

```
System.InvalidOperationException: Cannot inject mutation '!(            Int64.TryParse(x.Val, out var val)
01:51:15  )' in 'new User(
01:51:15                  id: "48622c30-5900-4e49-a847-cacf922048c0",
01:51:15                  name: "User")' because we cannot find the original code.
01:51:15     at Stryker.Core.Helpers.RoslynHelper.InjectMutation[T](T original, Mutation mutation)
01:51:15     at Stryker.Core.Mutants.NodeOrchestrators.PropertyDeclarationOrchestrator.<>c__DisplayClass1_0.<InjectMutations>b__0(Mutant m)
01:51:15     at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
01:51:15     at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
01:51:15     at Stryker.Core.Mutants.MutantPlacer.PlaceStatementControlledMutations(StatementSyntax original, IEnumerable`1 mutations)
01:51:15     at Stryker.Core.Mutants.NodeOrchestrators.PropertyDeclarationOrchestrator.InjectMutations(PropertyDeclarationSyntax sourceNode, BasePropertyDeclarationSyntax targetNode, MutationContext context)
01:51:15     at Stryker.Core.Mutants.NodeOrchestrators.NodeSpecificOrchestrator`2.Mutate(SyntaxNode node, MutationContext context)
01:51:15     at Stryker.Core.Mutants.CsharpMutantOrchestrator.Mutate(SyntaxNode currentNode, MutationContext context)
01:51:15     at Stryker.Core.Mutants.NodeOrchestrators.NodeSpecificOrchestrator`2.<>c__DisplayClass11_0.<OrchestrateChildrenMutation>b__0(SyntaxNode original, SyntaxNode _)
01:51:15     at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxReplacer.Replacer`1.Visit(SyntaxNode node)
01:51:15     at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitListElement[TNode](TNode node)
01:51:15     at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
01:51:15     at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitClassDeclaration(ClassDeclarationSyntax node)
01:51:15     at Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
01:51:15     at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
01:51:15     at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxReplacer.Replacer`1.Visit(SyntaxNode node)
01:51:15     at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxReplacer.Replace[TNode](SyntaxNode root, IEnumerable`1 nodes, Func`3 computeReplacementNode, IEnumerable`1 tokens, Func`3 computeReplacementToken, IEnumerable`1 trivia, Func`3 computeReplacementTrivia)
01:51:15     at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode.ReplaceCore[TNode](IEnumerable`1 nodes, Func`3 computeReplacementNode, IEnumerable`1 tokens, Func`3 computeReplacementToken, IEnumerable`1 trivia, Func`3 computeReplacementTrivia)
01:51:15     at Microsoft.CodeAnalysis.SyntaxNodeExtensions.ReplaceNodes[TRoot,TNode](TRoot root, IEnumerable`1 nodes, Func`3 computeReplacementNode)
01:51:15     at Stryker.Core.Mutants.NodeOrchestrators.NodeSpecificOrchestrator`2.OrchestrateChildrenMutation(TNode node, MutationContext context)
01:51:15     at Stryker.Core.Mutants.NodeOrchestrators.NodeSpecificOrchestrator`2.Mutate(SyntaxNode node, MutationContext context)
01:51:15     at Stryker.Core.Mutants.CsharpMutantOrchestrator.Mutate(SyntaxNode currentNode, MutationContext context)
01:51:15     at Stryker.Core.Mutants.NodeOrchestrators.NodeSpecificOrchestrator`2.<>c__DisplayClass11_0.<OrchestrateChildrenMutation>b__0(SyntaxNode original, SyntaxNode _)
01:51:15     at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxReplacer.Replacer`1.Visit(SyntaxNode node)
01:51:15     at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitListElement[TNode](TNode node)
01:51:15     at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
01:51:15     at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitNamespaceDeclaration(NamespaceDeclarationSyntax node)
01:51:15     at Microsoft.CodeAnalysis.CSharp.Syntax.NamespaceDeclarationSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
01:51:15     at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
01:51:15     at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxReplacer.Replacer`1.Visit(SyntaxNode node)
01:51:15     at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxReplacer.Replace[TNode](SyntaxNode root, IEnumerable`1 nodes, Func`3 computeReplacementNode, IEnumerable`1 tokens, Func`3 computeReplacementToken, IEnumerable`1 trivia, Func`3 computeReplacementTrivia)
01:51:15     at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode.ReplaceCore[TNode](IEnumerable`1 nodes, Func`3 computeReplacementNode, IEnumerable`1 tokens, Func`3 computeReplacementToken, IEnumerable`1 trivia, Func`3 computeReplacementTrivia)
01:51:15     at Microsoft.CodeAnalysis.SyntaxNodeExtensions.ReplaceNodes[TRoot,TNode](TRoot root, IEnumerable`1 nodes, Func`3 computeReplacementNode)
01:51:15     at Stryker.Core.Mutants.NodeOrchestrators.NodeSpecificOrchestrator`2.OrchestrateChildrenMutation(TNode node, MutationContext context)
01:51:15     at Stryker.Core.Mutants.NodeOrchestrators.NodeSpecificOrchestrator`2.Mutate(SyntaxNode node, MutationContext context)
01:51:15     at Stryker.Core.Mutants.CsharpMutantOrchestrator.Mutate(SyntaxNode currentNode, MutationContext context)
01:51:15     at Stryker.Core.Mutants.NodeOrchestrators.NodeSpecificOrchestrator`2.<>c__DisplayClass11_0.<OrchestrateChildrenMutation>b__0(SyntaxNode original, SyntaxNode _)
01:51:15     at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxReplacer.Replacer`1.Visit(SyntaxNode node)
01:51:15     at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitListElement[TNode](TNode node)
01:51:15     at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
01:51:15     at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitCompilationUnit(CompilationUnitSyntax node)
01:51:15     at Microsoft.CodeAnalysis.CSharp.Syntax.CompilationUnitSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
01:51:15     at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
01:51:15     at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxReplacer.Replacer`1.Visit(SyntaxNode node)
01:51:15     at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxReplacer.Replace[TNode](SyntaxNode root, IEnumerable`1 nodes, Func`3 computeReplacementNode, IEnumerable`1 tokens, Func`3 computeReplacementToken, IEnumerable`1 trivia, Func`3 computeReplacementTrivia)
01:51:15     at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode.ReplaceCore[TNode](IEnumerable`1 nodes, Func`3 computeReplacementNode, IEnumerable`1 tokens, Func`3 computeReplacementToken, IEnumerable`1 trivia, Func`3 computeReplacementTrivia)
01:51:15     at Microsoft.CodeAnalysis.SyntaxNodeExtensions.ReplaceNodes[TRoot,TNode](TRoot root, IEnumerable`1 nodes, Func`3 computeReplacementNode)
01:51:15     at Stryker.Core.Mutants.NodeOrchestrators.NodeSpecificOrchestrator`2.OrchestrateChildrenMutation(TNode node, MutationContext context)
01:51:15     at Stryker.Core.Mutants.NodeOrchestrators.NodeSpecificOrchestrator`2.Mutate(SyntaxNode node, MutationContext context)
01:51:15     at Stryker.Core.Mutants.CsharpMutantOrchestrator.Mutate(SyntaxNode currentNode, MutationContext context)
01:51:15     at Stryker.Core.Mutants.CsharpMutantOrchestrator.Mutate(SyntaxNode input)
01:51:15     at Stryker.Core.MutationTest.CsharpMutationProcess.Mutate()
01:51:15     at Stryker.Core.MutationTest.MutationTestProcess.Mutate()
01:51:15     at Stryker.Core.Initialisation.ProjectMutator.MutateProject(IStrykerOptions options, IReporter reporters)
01:51:15     at Stryker.Core.Initialisation.ProjectOrchestrator.MutateProjects(StrykerOptions options, IReporter reporters)+MoveNext()
01:51:15     at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
01:51:15     at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
01:51:15     at Stryker.Core.StrykerRunner.RunMutationTest(StrykerOptions options, IEnumerable`1 initialLogMessages)
```

**Expected behavior**
Stryker does not fail

**Desktop (please complete the following information):**
 - OS: Debian buster
 - Type of project: netcore 
 - Framework Version: target netcoreapp3.1, running on net5.0 sdk
 - Stryker Version 0.21.0 / 0.21.1

**Additional context**
Let me know if there's more information I can provide. This is a closed source application so I cannot share too much details.

**Comment by Mobrockers** [comment]
@Dave-EMIS Thank you for the report! I think these logs are enough for us to investigate the issue. If not we'll let you know!

**Comment by dupdob** [comment]
There is clearly a bug in mutation injection. This exception is new: in previous versions, this kind of problem went unnoticed and resulted in mutations that could not be killed (as they were not injected in the code).

@Dave-EMIS : any chance you can share the source file that caused this? that would be great. Alternatively, the methods and properties that contain both bits of code (`Int64.TryParse(x.Val, out var val)` and  `new User(id: "48622c30-5900-4e49-a847-cacf922048c0", name: "User")`).
It may be related to a some local function definition or/and an inner class. At the very least, if you could provide some description of the code structure could be helpful.

**Comment by Dave-EMIS** [comment]
I'll do my best...

The overall method is something like this:

```
var y = new Foo(
  name: name,
  age: ParseAge(x.Age),
  user1: FixedUser,
  user2: FixedUser,
  other: GetOther(x.Other),
  wibble: null,
  id: GetId(x.Id))
  {
    Optional1 = x.Optional1
    //etc.
  }
```

The other methods involved that appear in the logs are:

```
private static User FixedUser =>
  new User(
    id: "48622c30-5900-4e49-a847-cacf922048c0",
    name: "User");

private static Int64? GetId(C c) =>
  Int64.TryParse(c.Id, out var id)
  ?
  id
  :
  (Int64?)null;
```

The error message appears to be a conflict between mutating FixedUser and GetId. I tried replacing the second FixedUser with copy called FixedUser2 with a different GUID, but the outcome is the same (even the same GUIDs in the log).

```
2021-01-25T15:26:34.1203549+00:00  [DBG] Mutant 201 created "\"48622c30-5900-4e49-a847-cacf922048c0\"" -> "\"\"" using "Stryker.Core.Mutators.StringMutator" (310d25d3)
2021-01-25T15:26:34.1204194+00:00  [DBG] Mutant 202 created "\"User\"" -> "\"\"" using "Stryker.Core.Mutators.StringMutator" (310d25d3)
2021-01-25T15:26:34.1727052+00:00  [ERR] An error occurred during the mutation test run  (2ecaed66)
System.InvalidOperationException: Cannot inject mutation '!(            Int64.TryParse(c.Id, out var id)
)' in 'new User(
                id: "48622c30-5900-4e49-a847-cacf922048c0",
                name: "User")' because we cannot find the original code.
```

As I look at the logs I can see it working its way down the different values passed to `Foo` ctor and providing mutants, but I cannot see anything for `GetOther` or `wibble`, but I'm not sure that has any mutants possible...

It then seems to get confused over `GetId` and `FixedUser`?

**Comment by Dave-EMIS** [comment]
I tried changing FixedUser to a normal getter property:

```
private static User FixedUser2
        {
            get
            {
                return
                    new User(
                        id: "ern:emis:user:user:48622c30-5900-4e49-a847-cacf922048c1",
                        name: "EMIS Web User");
            }
        }
```

And I got the same error

I then made it public and got a Null Reference Exception:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Stryker.Core.Mutants.NodeOrchestrators.AccessorSyntaxOrchestrator.<>c__DisplayClass1_0.<InjectMutations>b__0(Mutation toConvert) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\NodeOrchestrators\AccessorSyntaxOrchestrator.cs:line 37
   at Stryker.Core.Mutants.NodeOrchestrators.AccessorSyntaxOrchestrator.<>c__DisplayClass1_0.<InjectMutations>b__2(Mutant m) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\NodeOrchestrators\AccessorSyntaxOrchestrator.cs:line 44
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at Stryker.Core.Mutants.MutantPlacer.PlaceStatementControlledMutations(StatementSyntax original, IEnumerable`1 mutations) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\MutantPlacer.cs:line 83
   at Stryker.Core.Mutants.NodeOrchestrators.AccessorSyntaxOrchestrator.InjectMutations(AccessorDeclarationSyntax sourceNode, SyntaxNode targetNode, MutationContext context) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\NodeOrchestrators\AccessorSyntaxOrchestrator.cs:line 41
   at Stryker.Core.Mutants.NodeOrchestrators.NodeSpecificOrchestrator`2.Mutate(SyntaxNode node, MutationContext context) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\NodeOrchestrators\NodeSpecificOrchestrator.cs:line 117
   at Stryker.Core.Mutants.CsharpMutantOrchestrator.Mutate(SyntaxNode currentNode, MutationContext context) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\CsharpMutantOrchestrator.cs:line 107
   at Stryker.Core.Mutants.NodeOrchestrators.NodeSpecificOrchestrator`2.<>c__DisplayClass11_0.<OrchestrateChildrenMutation>b__0(SyntaxNode original, SyntaxNode _) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\NodeOrchestrators\NodeSpecificOrchestrator.cs:line 93
   at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxReplacer.Replacer`1.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitListElement[TNode](TNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitAccessorList(AccessorListSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.AccessorListSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxReplacer.Replacer`1.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxReplacer.Replace[TNode](SyntaxNode root, IEnumerable`1 nodes, Func`3 computeReplacementNode, IEnumerable`1 tokens, Func`3 computeReplacementToken, IEnumerable`1 trivia, Func`3 computeReplacementTrivia)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode.ReplaceCore[TNode](IEnumerable`1 nodes, Func`3 computeReplacementNode, IEnumerable`1 tokens, Func`3 computeReplacementToken, IEnumerable`1 trivia, Func`3 computeReplacementTrivia)
   at Microsoft.CodeAnalysis.SyntaxNodeExtensions.ReplaceNodes[TRoot,TNode](TRoot root, IEnumerable`1 nodes, Func`3 computeReplacementNode)
   at Stryker.Core.Mutants.NodeOrchestrators.NodeSpecificOrchestrator`2.OrchestrateChildrenMutation(TNode node, MutationContext context) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\NodeOrchestrators\NodeSpecificOrchestrator.cs:line 92
   at Stryker.Core.Mutants.NodeOrchestrators.NodeSpecificOrchestrator`2.Mutate(SyntaxNode node, MutationContext context) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\NodeOrchestrators\NodeSpecificOrchestrator.cs:line 117
   at Stryker.Core.Mutants.CsharpMutantOrchestrator.Mutate(SyntaxNode currentNode, MutationContext context) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\CsharpMutantOrchestrator.cs:line 107
   at Stryker.Core.Mutants.NodeOrchestrators.NodeSpecificOrchestrator`2.<>c__DisplayClass11_0.<OrchestrateChildrenMutation>b__0(SyntaxNode original, SyntaxNode _) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\NodeOrchestrators\NodeSpecificOrchestrator.cs:line 93
   at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxReplacer.Replacer`1.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitPropertyDeclaration(PropertyDeclarationSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.PropertyDeclarationSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxReplacer.Replacer`1.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxReplacer.Replace[TNode](SyntaxNode root, IEnumerable`1 nodes, Func`3 computeReplacementNode, IEnumerable`1 tokens, Func`3 computeReplacementToken, IEnumerable`1 trivia, Func`3 computeReplacementTrivia)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode.ReplaceCore[TNode](IEnumerable`1 nodes, Func`3 computeReplacementNode, IEnumerable`1 tokens, Func`3 computeReplacementToken, IEnumerable`1 trivia, Func`3 computeReplacementTrivia)
   at Microsoft.CodeAnalysis.SyntaxNodeExtensions.ReplaceNodes[TRoot,TNode](TRoot root, IEnumerable`1 nodes, Func`3 computeReplacementNode)
   at Stryker.Core.Mutants.NodeOrchestrators.NodeSpecificOrchestrator`2.OrchestrateChildrenMutation(TNode node, MutationContext context) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\NodeOrchestrators\NodeSpecificOrchestrator.cs:line 92
   at Stryker.Core.Mutants.NodeOrchestrators.NodeSpecificOrchestrator`2.Mutate(SyntaxNode node, MutationContext context) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\NodeOrchestrators\NodeSpecificOrchestrator.cs:line 117
   at Stryker.Core.Mutants.CsharpMutantOrchestrator.Mutate(SyntaxNode currentNode, MutationContext context) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\CsharpMutantOrchestrator.cs:line 107
   at Stryker.Core.Mutants.NodeOrchestrators.NodeSpecificOrchestrator`2.<>c__DisplayClass11_0.<OrchestrateChildrenMutation>b__0(SyntaxNode original, SyntaxNode _) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\NodeOrchestrators\NodeSpecificOrchestrator.cs:line 93
   at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxReplacer.Replacer`1.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitListElement[TNode](TNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitClassDeclaration(ClassDeclarationSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxReplacer.Replacer`1.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxReplacer.Replace[TNode](SyntaxNode root, IEnumerable`1 nodes, Func`3 computeReplacementNode, IEnumerable`1 tokens, Func`3 computeReplacementToken, IEnumerable`1 trivia, Func`3 computeReplacementTrivia)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode.ReplaceCore[TNode](IEnumerable`1 nodes, Func`3 computeReplacementNode, IEnumerable`1 tokens, Func`3 computeReplacementToken, IEnumerable`1 trivia, Func`3 computeReplacementTrivia)
   at Microsoft.CodeAnalysis.SyntaxNodeExtensions.ReplaceNodes[TRoot,TNode](TRoot root, IEnumerable`1 nodes, Func`3 computeReplacementNode)
   at Stryker.Core.Mutants.NodeOrchestrators.NodeSpecificOrchestrator`2.OrchestrateChildrenMutation(TNode node, MutationContext context) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\NodeOrchestrators\NodeSpecificOrchestrator.cs:line 92
   at Stryker.Core.Mutants.NodeOrchestrators.NodeSpecificOrchestrator`2.Mutate(SyntaxNode node, MutationContext context) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\NodeOrchestrators\NodeSpecificOrchestrator.cs:line 117
   at Stryker.Core.Mutants.CsharpMutantOrchestrator.Mutate(SyntaxNode currentNode, MutationContext context) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\CsharpMutantOrchestrator.cs:line 107
   at Stryker.Core.Mutants.NodeOrchestrators.NodeSpecificOrchestrator`2.<>c__DisplayClass11_0.<OrchestrateChildrenMutation>b__0(SyntaxNode original, SyntaxNode _) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\NodeOrchestrators\NodeSpecificOrchestrator.cs:line 93
   at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxReplacer.Replacer`1.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitListElement[TNode](TNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitNamespaceDeclaration(NamespaceDeclarationSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.NamespaceDeclarationSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxReplacer.Replacer`1.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxReplacer.Replace[TNode](SyntaxNode root, IEnumerable`1 nodes, Func`3 computeReplacementNode, IEnumerable`1 tokens, Func`3 computeReplacementToken, IEnumerable`1 trivia, Func`3 computeReplacementTrivia)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode.ReplaceCore[TNode](IEnumerable`1 nodes, Func`3 computeReplacementNode, IEnumerable`1 tokens, Func`3 computeReplacementToken, IEnumerable`1 trivia, Func`3 computeReplacementTrivia)
   at Microsoft.CodeAnalysis.SyntaxNodeExtensions.ReplaceNodes[TRoot,TNode](TRoot root, IEnumerable`1 nodes, Func`3 computeReplacementNode)
   at Stryker.Core.Mutants.NodeOrchestrators.NodeSpecificOrchestrator`2.OrchestrateChildrenMutation(TNode node, MutationContext context) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\NodeOrchestrators\NodeSpecificOrchestrator.cs:line 92
   at Stryker.Core.Mutants.NodeOrchestrators.NodeSpecificOrchestrator`2.Mutate(SyntaxNode node, MutationContext context) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\NodeOrchestrators\NodeSpecificOrchestrator.cs:line 117
   at Stryker.Core.Mutants.CsharpMutantOrchestrator.Mutate(SyntaxNode currentNode, MutationContext context) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\CsharpMutantOrchestrator.cs:line 107
   at Stryker.Core.Mutants.NodeOrchestrators.NodeSpecificOrchestrator`2.<>c__DisplayClass11_0.<OrchestrateChildrenMutation>b__0(SyntaxNode original, SyntaxNode _) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\NodeOrchestrators\NodeSpecificOrchestrator.cs:line 93
   at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxReplacer.Replacer`1.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitListElement[TNode](TNode node)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.VisitCompilationUnit(CompilationUnitSyntax node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.CompilationUnitSyntax.Accept[TResult](CSharpSyntaxVisitor`1 visitor)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxRewriter.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxReplacer.Replacer`1.Visit(SyntaxNode node)
   at Microsoft.CodeAnalysis.CSharp.Syntax.SyntaxReplacer.Replace[TNode](SyntaxNode root, IEnumerable`1 nodes, Func`3 computeReplacementNode, IEnumerable`1 tokens, Func`3 computeReplacementToken, IEnumerable`1 trivia, Func`3 computeReplacementTrivia)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode.ReplaceCore[TNode](IEnumerable`1 nodes, Func`3 computeReplacementNode, IEnumerable`1 tokens, Func`3 computeReplacementToken, IEnumerable`1 trivia, Func`3 computeReplacementTrivia)
   at Microsoft.CodeAnalysis.SyntaxNodeExtensions.ReplaceNodes[TRoot,TNode](TRoot root, IEnumerable`1 nodes, Func`3 computeReplacementNode)
   at Stryker.Core.Mutants.NodeOrchestrators.NodeSpecificOrchestrator`2.OrchestrateChildrenMutation(TNode node, MutationContext context) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\NodeOrchestrators\NodeSpecificOrchestrator.cs:line 92
   at Stryker.Core.Mutants.NodeOrchestrators.NodeSpecificOrchestrator`2.Mutate(SyntaxNode node, MutationContext context) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\NodeOrchestrators\NodeSpecificOrchestrator.cs:line 117
   at Stryker.Core.Mutants.CsharpMutantOrchestrator.Mutate(SyntaxNode currentNode, MutationContext context) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\CsharpMutantOrchestrator.cs:line 107
   at Stryker.Core.Mutants.CsharpMutantOrchestrator.Mutate(SyntaxNode input) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\CsharpMutantOrchestrator.cs:line 81
   at Stryker.Core.MutationTest.CsharpMutationProcess.Mutate() in D:\a\1\s\src\Stryker.Core\Stryker.Core\MutationTest\CsharpMutationProcess.cs:line 57
   at Stryker.Core.MutationTest.MutationTestProcess.Mutate() in D:\a\1\s\src\Stryker.Core\Stryker.Core\MutationTest\MutationTestProcess.cs:line 75
   at Stryker.Core.Initialisation.ProjectMutator.MutateProject(IStrykerOptions options, IReporter reporters) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Initialisation\ProjectMutator.cs:line 41
   at Stryker.Core.Initialisation.ProjectOrchestrator.MutateProjects(StrykerOptions options, IReporter reporters)+MoveNext() in D:\a\1\s\src\Stryker.Core\Stryker.Core\Initialisation\ProjectOrchestrator.cs:line 61
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Stryker.Core.StrykerRunner.RunMutationTest(StrykerOptions options, IEnumerable`1 initialLogMessages) in D:\a\1\s\src\Stryker.Core\Stryker.Core\StrykerRunner.cs:line 58
```

**Comment by dupdob** [comment]
Thanks for your details. I have enough data to attempt to reproduce the issue.
Here is some background for this, since you look interested in understanding the cause of the problem:
Stryker.Net uses either conditional operator (`?:`) or `if` statements depending on the type of mutation and the code syntax. `?:` can be injected in any expression, but `if` statements need to be injected between statements and also need to respect visibility scope. This means that Stryker uses an internal accumulator to track pending mutations that need to be controlled at the statement level (instead of the expression level, i.e in place).
For example
```csharp
private static Int64? GetId(C c) =>
  Int64.TryParse(c.Id, out var id) ? i : (Int64?)null;
```
Need to be mutated to:
```csharp
private static Int64? GetId(C c) {
  if (Stryker.MutationControl.IsActive(12)
  {
    return (!Int64.TryParse(c.Id, out var id)) ? id : (Int64?)null;
  }
  else
  {
    return Int64.TryParse(c.Id, out var id) ? id : (Int64?)null;
  }
}
```
What happens here is that this mutation was not properly injected in the `GetId` method and ended up being injected in the `FixedUser` property. Which probably means the property is defined After the method, and not before.

So, I think:

- there is a bug with expression formed method
- there should be some safeguarding mechanism to prevent mutations to leak to the next method...

@Dave-EMIS: if my theory is correct or close to being correct, you can work around this issue by transforming `GetId` to the body form.
Note that similar constructs will lead to similar issue, but the workaround should work everywhere

**Comment by dupdob** [comment]
update: I can reproduce the issue!

**Comment by Dave-EMIS** [comment]
Confirmed, if I change to a block body method it works for me too.

It's definitely not the only one of those we have in our codebase (we are fans of the succinct expression bodies and what not).

**Comment by dupdob** [comment]
Don't worry: I am working on a fix.
