### ISSUE TITLE
System.IO.FileNotFoundException: Could not load file or assembly 'Stryker.DataCollector

### ISSUE THREAD

**Issue by itachi1994** [stryker-mutator/stryker-net#1393]
**Describe the bug**
Sometimes the build fails with the following error:
_System.IO.FileNotFoundException: Could not load file or assembly 'Stryker.DataCollector, Version=0.16.1.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified._

Re-running the build fixes the problem.

**Logs**
```
Version: 0.21.1 (beta)

[12:16:18 INF] Identifying project to mutate.
[12:16:20 INF] The project /home/admin1/actions-runner/ix-sdc/_work/ix-sdc/ix-sdc/com.iX.Sdc/com.iX.Sdc.csproj will be mutated.
[12:16:22 INF] Analysis complete.
[12:16:22 INF] Building test project /home/admin1/actions-runner/ix-sdc/_work/ix-sdc/ix-sdc/com.iX.Sdc.Test/com.iX.Sdc.Test.csproj (1/1)
[12:16:26 INF] Initializing test runners (VsTest)
[12:16:27 ERR] An error occurred during the mutation test run 
System.IO.FileNotFoundException: Could not load file or assembly 'Stryker.DataCollector, Version=0.16.1.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'Stryker.DataCollector, Version=0.16.1.0, Culture=neutral, PublicKeyToken=null'
   at Stryker.Core.TestRunners.VsTest.VsTestRunner.GenerateRunSettings(Nullable`1 timeout, Boolean forMutantTesting, Boolean forCoverage, Dictionary`2 mutantTestsMap)
   at Stryker.Core.TestRunners.VsTest.VsTestRunner.DiscoverTests(String runSettings)
   at Stryker.Core.TestRunners.VsTest.VsTestRunner.InitializeVsTestConsole()
   at Stryker.Core.TestRunners.VsTest.VsTestRunner..ctor(IStrykerOptions options, OptimizationFlags flags, ProjectInfo projectInfo, ICollection`1 testCasesDiscovered, IFileSystem fileSystem, IVsTestHelper helper, ILogger logger, IVsTestConsoleWrapper wrapper, Func`2 hostBuilder)
   at Stryker.Core.TestRunners.VsTest.VsTestRunnerPool..ctor(IStrykerOptions options, OptimizationFlags flags, ProjectInfo projectInfo)
   at Stryker.Core.TestRunners.TestRunnerFactory.Create(IStrykerOptions options, OptimizationFlags flags, ProjectInfo projectInfo)
   at Stryker.Core.Initialisation.InitialisationProcess.Initialize(IStrykerOptions options)
   at Stryker.Core.Initialisation.ProjectMutator.MutateProject(IStrykerOptions options, IReporter reporters)
   at Stryker.Core.Initialisation.ProjectOrchestrator.MutateProjects(StrykerOptions options, IReporter reporters)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Stryker.Core.StrykerRunner.RunMutationTest(StrykerOptions options, IEnumerable`1 initialLogMessages)

[12:16:27 INF] Time Elapsed 00:00:09.3529921
Write-Error: /home/admin1/actions-runner/ix-sdc/_work/ix-sdc/ix-sdc/.ix-github-actions/actions/stryker/docker/RunStryker.ps1:122
Line |
 122 |          RunForOneAssembly $project.testPath $strykerData.solutionFile
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Error in running Stryker, exiting the script
```

**Expected behavior**
Stryker should successfully execute. No error should be displayed.

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Type of project [core]
 - Framework Version [core 3.1]
 - Stryker Version [beta 0.21.1]

**Additional context**
Re-running the stryker fixes the problem.

**Comment by Mobrockers** [comment]
Hi @itachi1994 Interesting problem. We have never seen this before and I have no clue how this could happen. Stryker.DataCollector is shipped with stryker, there is basically no way for it to not be available 🤔

**Comment by bcollamore** [comment]
It is not uncommon for us to see this issue.  It is coincidental that it was Stryker.DataCollector that was unavailable.  It appears to be random as to which dll is missing.  (e.g., newtonsoft.dll, etc.).  At first we thought this was an artifact of our build environment, because it's not running in an isolated Docker container (yet).  We do (re-)install the tool to the latest version on each build run.  We thought multiple GitHub Workflows were perhaps running in parallel, but that's not how those work.  Note: some of these SLNs have multiple Test projects, so we run it once per test project, serially; however, in this case the first run failed, so its not that the first affected the second.  Is it a possible side effect of the clean that happens during this process?  If others do not face this, we will focus on the build environment first.

**Comment by Mobrockers** [comment]
If it was only the datacollector then I would be willing to entertain the thought that it was related to stryker but if it's other dll's such as newtonsoft as well then I don't see how it could be related to us specifically. All dll's are packaged with stryker and when you install stryker only one nuget package is downloaded. This package includes all relevant dll's. If a dll is missing something went wrong after download and unpack. Either in your build environment or in dotnet itself.

**Comment by bcollamore** [comment]
We confirmed that GitHub Actions are running multiple workflows concurrently, even on the same build runner.  Stryker is fine!  We'll install the tool locally for better isolation.
