### ISSUE TITLE
Stryker.CLI fails to start on MacOSX (microsoft.testplatform.portable not found)

### ISSUE THREAD

**Issue by MindWrapper** [stryker-mutator/stryker-net#1428]
**Describe the bug**
I started running Stryker on mac and got the following error:

```
Version: 0.21.1 (beta)
[20:09:49 INF] Identifying project to mutate.
[20:09:51 INF] The project /Users/yan/unity/cds.test-platform/source/Automation/Unity.TestProtocol/Unity.TestProtocol.csproj will be mutated.
[20:09:52 INF] Analysis complete.
[20:09:52 INF] Building test project /Users/yan/unity/cds.test-platform/source/Automation/Unity.TestProtocol.UnitTests/Unity.TestProtocol.UnitTests.csproj (1/1)
[20:09:55 INF] Initializing test runners (VsTest)
[20:09:55 ERR] An error occurred during the mutation test run 
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at Stryker.Core.ToolHelpers.VsTestHelper.DeployEmbeddedVsTestBinaries() in /Users/yan/stryker-net/src/Stryker.Core/Stryker.Core/ToolHelpers/VsTestHelper.cs:line 194
   at Stryker.Core.ToolHelpers.VsTestHelper.GetVsTestToolPaths() in /Users/yan/stryker-net/src/Stryker.Core/Stryker.Core/ToolHelpers/VsTestHelper.cs:line 89
   at Stryker.Core.ToolHelpers.VsTestHelper.GetCurrentPlatformVsTestToolPath() in /Users/yan/stryker-net/src/Stryker.Core/Stryker.Core/ToolHelpers/VsTestHelper.cs:line 42
   at Stryker.Core.TestRunners.VsTest.VsTestRunner.PrepareVsTestConsole() in /Users/yan/stryker-net/src/Stryker.Core/Stryker.Core/TestRunners/VsTest/VsTestRunner.cs:line 452
   at Stryker.Core.TestRunners.VsTest.VsTestRunner..ctor(IStrykerOptions options, OptimizationFlags flags, ProjectInfo projectInfo, ICollection`1 testCasesDiscovered, IFileSystem fileSystem, IVsTestHelper helper, ILogger logger, IVsTestConsoleWrapper wrapper, Func`2 hostBuilder) in /Users/yan/stryker-net/src/Stryker.Core/Stryker.Core/TestRunners/VsTest/VsTestRunner.cs:line 74
   at Stryker.Core.TestRunners.VsTest.VsTestRunnerPool..ctor(IStrykerOptions options, OptimizationFlags flags, ProjectInfo projectInfo) in /Users/yan/stryker-net/src/Stryker.Core/Stryker.Core/TestRunners/VsTest/VsTestRunnerPool.cs:line 31
   at Stryker.Core.TestRunners.TestRunnerFactory.Create(IStrykerOptions options, OptimizationFlags flags, ProjectInfo projectInfo) in /Users/yan/stryker-net/src/Stryker.Core/Stryker.Core/TestRunners/TestRunnerFactory.cs:line 33
   at Stryker.Core.Initialisation.InitialisationProcess.Initialize(IStrykerOptions options) in /Users/yan/stryker-net/src/Stryker.Core/Stryker.Core/Initialisation/InitialisationProcess.cs:line 79
   at Stryker.Core.Initialisation.ProjectMutator.MutateProject(IStrykerOptions options, IReporter reporters) in /Users/yan/stryker-net/src/Stryker.Core/Stryker.Core/Initialisation/ProjectMutator.cs:line 29
   at Stryker.Core.Initialisation.ProjectOrchestrator.MutateProjects(StrykerOptions options, IReporter reporters)+MoveNext() in /Users/yan/stryker-net/src/Stryker.Core/Stryker.Core/Initialisation/ProjectOrchestrator.cs:line 61
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Stryker.Core.StrykerRunner.RunMutationTest(StrykerOptions options, IEnumerable`1 initialLogMessages) in /Users/yan/stryker-net/src/Stryker.Core/Stryker.Core/StrykerRunner.cs:line 59
[20:09:55 INF] Time Elapsed 00:00:05.6408068
```
**Logs**
--log-file wasn't recognized. Therefore I pasted plain logs above

**Expected behavior**
Stryker should mutate the project

**Desktop (please complete the following information):**
 - OS: MacOsX
 - Type of project: core:
 - Framework Version: core 3.1
 - Stryker Version: 0.21.1 (beta)

**Additional context**
I can fix it myself, will submit PR shortly

**Comment by Mobrockers** [comment]
Hi @MindWrapper 👋

Were you running from source when you got this error?

**Comment by MindWrapper** [comment]
Hey @Mobrockers, yes I was running from source.

**Comment by Mobrockers** [comment]
That explains your error.

When running from source vstest.console _should_ be picked up from your nuget cache folder automatically: 
https://github.com/stryker-mutator/stryker-net/blob/0b234fd1f90523cc4753a9f0bebc68480221bd31/src/Stryker.Core/Stryker.Core/ToolHelpers/VsTestHelper.cs#L110

For some reason this is not working on your system. Can you confirm that the testplatform nupkg is available in your machine package cache?


May I also ask why you are trying to run from source? :)
