### ISSUE TITLE
System.InvalidOperationException: No return at the end of

### ISSUE THREAD

**Issue by bcollamore** [stryker-mutator/stryker-net#1512]
**Describe the bug**
Stryker failed

**Logs**
Logs attached.  Notes below.

**Expected behavior**
Stryker succeeds

**Desktop (please complete the following information):**
 - OS: Linux
 - Type of project: .NET Standard
 - Framework Version: Standard 1.3
 - Stryker Version: 0.22.2

**Additional context**

Version 0.21.1 reported "this should not happen" but we missed it in the CI pipeline.

[strykerlogs.txt](https://github.com/stryker-mutator/stryker-net/files/6326685/strykerlogs.txt)
Original method:
		public bool AddRelationship(T dependent, T dependsOn, out string cyclePath)
		{
			cyclePath = string.Empty;
			lock (Graph)
			{
				// If either dependent or dependee is new to the graph, a cycle isn't possible.
				bool isCyclePossible = !_graphAdder.Add(Graph, dependent, out Node<T> dependentNode);
				isCyclePossible |= !_graphAdder.Add(Graph, dependsOn, out Node<T> dependsOnNode);

				bool cycleFound = false;
				var answerKey = new List<Node<T>>();
				if (isCyclePossible)
				{
					cycleFound = DoesPathExist(start: dependsOnNode, end: dependentNode, visited: new List<Node<T>>(), answerKey: answerKey);
				}

				if (cycleFound)
				{
					answerKey.Add(dependsOnNode);
					cyclePath = ToString(answerKey);
					return false;
				}
				dependentNode.AddDependency(dependsOnNode);
				return true;
			}
		}

Error:
2021-04-16T16:37:27.7609948Z [12:37:27 DBG] Remove a mutation helper.
2021-04-16T16:37:27.7758873Z [12:37:27 ERR] An error occurred during the mutation test run 
2021-04-16T16:37:27.7760014Z System.InvalidOperationException: No return at the end of: {
2021-04-16T16:37:27.7761564Z 			cyclePath = (StrykerJtpdbb49QO1lapm.MutantControl.IsActive(292)?"Stryker was here!":string.Empty);
2021-04-16T16:37:27.7762715Z 			lock (Graph)
2021-04-16T16:37:27.7763087Z {			{
2021-04-16T16:37:27.7764314Z 				// If either dependent or dependee is new to the graph, a cycle isn't possible.
2021-04-16T16:37:27.7765473Z 				bool isCyclePossible = !_graphAdder.Add(Graph, dependent, out Node<T> dependentNode);
2021-04-16T16:37:27.7767336Z if(StrykerJtpdbb49QO1lapm.MutantControl.IsActive(295)){				isCyclePossible ^=!_graphAdder.Add(Graph, dependsOn, out Node<T> dependsOnNode);
2021-04-16T16:37:27.7769825Z }else{if(StrykerJtpdbb49QO1lapm.MutantControl.IsActive(294)){				isCyclePossible &=!_graphAdder.Add(Graph, dependsOn, out Node<T> dependsOnNode);
2021-04-16T16:37:27.7771668Z }else{				isCyclePossible |= !_graphAdder.Add(Graph, dependsOn, out Node<T> dependsOnNode);
2021-04-16T16:37:27.7772434Z }}
2021-04-16T16:37:27.7773466Z 				bool cycleFound = (StrykerJtpdbb49QO1lapm.MutantControl.IsActive(297)?true:false);
2021-04-16T16:37:27.7774998Z 				var answerKey = new List<Node<T>>();
2021-04-16T16:37:27.7776421Z 				if ((StrykerJtpdbb49QO1lapm.MutantControl.IsActive(298)?!(isCyclePossible):isCyclePossible))
2021-04-16T16:37:27.7777543Z 				{
2021-04-16T16:37:27.7778423Z 					cycleFound = DoesPathExist(start: dependsOnNode, end: dependentNode, visited: new List<Node<T>>(), answerKey: answerKey);
2021-04-16T16:37:27.7779317Z 				}
2021-04-16T16:37:27.7779562Z 
2021-04-16T16:37:27.7780588Z 				if ((StrykerJtpdbb49QO1lapm.MutantControl.IsActive(299)?!(cycleFound):cycleFound))
2021-04-16T16:37:27.7781592Z 				{
2021-04-16T16:37:27.7782090Z 					answerKey.Add(dependsOnNode);
2021-04-16T16:37:27.7782726Z 					cyclePath = ToString(answerKey);
2021-04-16T16:37:27.7783872Z 					return (StrykerJtpdbb49QO1lapm.MutantControl.IsActive(300)?true:false);
2021-04-16T16:37:27.7785088Z 				}
2021-04-16T16:37:27.7785838Z 				dependentNode.AddDependency(dependsOnNode);
2021-04-16T16:37:27.7787153Z 				return (StrykerJtpdbb49QO1lapm.MutantControl.IsActive(301)?false:true);
2021-04-16T16:37:27.7788143Z 			}
2021-04-16T16:37:27.7788476Z }		}
2021-04-16T16:37:27.7789896Z    at Stryker.Core.Instrumentation.EndingReturnEngine.Revert(BaseMethodDeclarationSyntax node)
2021-04-16T16:37:27.7792020Z    at Stryker.Core.Instrumentation.BaseEngine`1.RemoveInstrumentation(SyntaxNode node)
2021-04-16T16:37:27.7793781Z    at Stryker.Core.Mutants.MutantPlacer.RemoveMutant(SyntaxNode nodeToRemove)
2021-04-16T16:37:27.7796588Z    at Stryker.Core.Compiling.RollbackProcess.RemoveMutantIfStatements(SyntaxTree originalTree, IEnumerable`1 diagnosticInfo, Boolean devMode)
2021-04-16T16:37:27.7799603Z    at Stryker.Core.Compiling.RollbackProcess.Start(CSharpCompilation compiler, ImmutableArray`1 diagnostics, Boolean lastAttempt, Boolean devMode)
2021-04-16T16:37:27.7802518Z    at Stryker.Core.Compiling.CompilingProcess.TryCompilation(Stream ms, Stream symbolStream, CSharpCompilation compilation, EmitResult previousEmitResult, Boolean lastAttempt, Boolean devMode, Int32 retryCount)
2021-04-16T16:37:27.7805459Z    at Stryker.Core.Compiling.CompilingProcess.Compile(IEnumerable`1 syntaxTrees, Stream ilStream, Stream symbolStream, Boolean devMode)
2021-04-16T16:37:27.7807895Z    at Stryker.Core.MutationTest.CsharpMutationProcess.CompileMutations()
2021-04-16T16:37:27.7810136Z    at Stryker.Core.MutationTest.CsharpMutationProcess.Mutate()
2021-04-16T16:37:27.7812043Z    at Stryker.Core.MutationTest.MutationTestProcess.Mutate()
2021-04-16T16:37:27.7814237Z    at Stryker.Core.Initialisation.ProjectMutator.MutateProject(IStrykerOptions options, IReporter reporters)
2021-04-16T16:37:27.7817044Z    at Stryker.Core.Initialisation.ProjectOrchestrator.MutateProjects(StrykerOptions options, IReporter reporters)+MoveNext()
2021-04-16T16:37:27.7819135Z    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
2021-04-16T16:37:27.7820310Z    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
2021-04-16T16:37:27.7821872Z    at Stryker.Core.StrykerRunner.RunMutationTest(StrykerOptions options, IEnumerable`1 initialLogMessages)
2021-04-16T16:37:27.7823136Z [12:37:27 INF] Time Elapsed 00:00:24.4456539
2021-04-16T16:37:27.7949595Z Unhandled exception. System.InvalidOperationException: No return at the end of: {
2021-04-16T16:37:27.7951526Z 			cyclePath = (StrykerJtpdbb49QO1lapm.MutantControl.IsActive(292)?"Stryker was here!":string.Empty);
2021-04-16T16:37:27.7954290Z 			lock (Graph)
2021-04-16T16:37:27.7954663Z {			{
2021-04-16T16:37:27.7956260Z 				// If either dependent or dependee is new to the graph, a cycle isn't possible.
2021-04-16T16:37:27.7957308Z 				bool isCyclePossible = !_graphAdder.Add(Graph, dependent, out Node<T> dependentNode);
2021-04-16T16:37:27.7959215Z if(StrykerJtpdbb49QO1lapm.MutantControl.IsActive(295)){				isCyclePossible ^=!_graphAdder.Add(Graph, dependsOn, out Node<T> dependsOnNode);
2021-04-16T16:37:27.7961654Z }else{if(StrykerJtpdbb49QO1lapm.MutantControl.IsActive(294)){				isCyclePossible &=!_graphAdder.Add(Graph, dependsOn, out Node<T> dependsOnNode);
2021-04-16T16:37:27.7963779Z }else{				isCyclePossible |= !_graphAdder.Add(Graph, dependsOn, out Node<T> dependsOnNode);
2021-04-16T16:37:27.7964534Z }}
2021-04-16T16:37:27.7965652Z 				bool cycleFound = (StrykerJtpdbb49QO1lapm.MutantControl.IsActive(297)?true:false);
2021-04-16T16:37:27.7966784Z 				var answerKey = new List<Node<T>>();
2021-04-16T16:37:27.7968021Z 				if ((StrykerJtpdbb49QO1lapm.MutantControl.IsActive(298)?!(isCyclePossible):isCyclePossible))
2021-04-16T16:37:27.7969146Z 				{
2021-04-16T16:37:27.7970041Z 					cycleFound = DoesPathExist(start: dependsOnNode, end: dependentNode, visited: new List<Node<T>>(), answerKey: answerKey);
2021-04-16T16:37:27.7970916Z 				}
2021-04-16T16:37:27.7971138Z 
2021-04-16T16:37:27.7972173Z 				if ((StrykerJtpdbb49QO1lapm.MutantControl.IsActive(299)?!(cycleFound):cycleFound))
2021-04-16T16:37:27.7973202Z 				{
2021-04-16T16:37:27.7973679Z 					answerKey.Add(dependsOnNode);
2021-04-16T16:37:27.7974314Z 					cyclePath = ToString(answerKey);
2021-04-16T16:37:27.7975501Z 					return (StrykerJtpdbb49QO1lapm.MutantControl.IsActive(300)?true:false);
2021-04-16T16:37:27.7976467Z 				}
2021-04-16T16:37:27.7977135Z 				dependentNode.AddDependency(dependsOnNode);
2021-04-16T16:37:27.7978460Z 				return (StrykerJtpdbb49QO1lapm.MutantControl.IsActive(301)?false:true);
2021-04-16T16:37:27.7979423Z 			}
2021-04-16T16:37:27.7979754Z }		}
2021-04-16T16:37:27.7981194Z    at Stryker.Core.Instrumentation.EndingReturnEngine.Revert(BaseMethodDeclarationSyntax node)
2021-04-16T16:37:27.7983313Z    at Stryker.Core.Instrumentation.BaseEngine`1.RemoveInstrumentation(SyntaxNode node)
2021-04-16T16:37:27.7985274Z    at Stryker.Core.Mutants.MutantPlacer.RemoveMutant(SyntaxNode nodeToRemove)
2021-04-16T16:37:27.7987792Z    at Stryker.Core.Compiling.RollbackProcess.RemoveMutantIfStatements(SyntaxTree originalTree, IEnumerable`1 diagnosticInfo, Boolean devMode)
2021-04-16T16:37:27.7990596Z    at Stryker.Core.Compiling.RollbackProcess.Start(CSharpCompilation compiler, ImmutableArray`1 diagnostics, Boolean lastAttempt, Boolean devMode)
2021-04-16T16:37:27.7993512Z    at Stryker.Core.Compiling.CompilingProcess.TryCompilation(Stream ms, Stream symbolStream, CSharpCompilation compilation, EmitResult previousEmitResult, Boolean lastAttempt, Boolean devMode, Int32 retryCount)
2021-04-16T16:37:27.7996638Z    at Stryker.Core.Compiling.CompilingProcess.Compile(IEnumerable`1 syntaxTrees, Stream ilStream, Stream symbolStream, Boolean devMode)
2021-04-16T16:37:27.7999075Z    at Stryker.Core.MutationTest.CsharpMutationProcess.CompileMutations()
2021-04-16T16:37:27.8001339Z    at Stryker.Core.MutationTest.CsharpMutationProcess.Mutate()
2021-04-16T16:37:27.8003495Z    at Stryker.Core.MutationTest.MutationTestProcess.Mutate()
2021-04-16T16:37:27.8005780Z    at Stryker.Core.Initialisation.ProjectMutator.MutateProject(IStrykerOptions options, IReporter reporters)
2021-04-16T16:37:27.8008510Z    at Stryker.Core.Initialisation.ProjectOrchestrator.MutateProjects(StrykerOptions options, IReporter reporters)+MoveNext()
2021-04-16T16:37:27.8010569Z    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
2021-04-16T16:37:27.8011737Z    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
2021-04-16T16:37:27.8013639Z    at Stryker.Core.StrykerRunner.RunMutationTest(StrykerOptions options, IEnumerable`1 initialLogMessages)
2021-04-16T16:37:27.8016184Z    at Stryker.CLI.StrykerCLI.RunStryker(StrykerOptions options) in D:\a\1\s\src\Stryker.CLI\Stryker.CLI\StrykerCLI.cs:line 136
2021-04-16T16:37:27.8018189Z    at Stryker.CLI.StrykerCLI.<>c__DisplayClass7_0.<Run>b__0() in D:\a\1\s\src\Stryker.CLI\Stryker.CLI\StrykerCLI.cs:line 125
2021-04-16T16:37:27.8020398Z    at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass146_0.<OnExecute>b__0(CancellationToken _)
2021-04-16T16:37:27.8023929Z    at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
2021-04-16T16:37:27.8027806Z    at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
2021-04-16T16:37:27.8029927Z    at Stryker.CLI.StrykerCLI.Run(String[] args) in D:\a\1\s\src\Stryker.CLI\Stryker.CLI\StrykerCLI.cs:line 128
2021-04-16T16:37:27.8031279Z    at Stryker.CLI.Program.Main(String[] args) in D:\a\1\s\src\Stryker.CLI\Stryker.CLI\Program.cs:line 16

**Comment by dupdob** [comment]
Update report: 
0) fix is implemented and looking good in terms of design
1) unit testing has been improved (try to remove helpers twice)
2) I have reproduced the problem, in a simpler context
3) I no longer think there is a (new) larger problem. It turns out this issue occurs when safe mode will be triggered anyway
4) now the interesting part is what triggered the safe mode here!

The compilation error that triggered a swipe removal of mutations is `The name 'dependsOnNode' does not exist in the current context`. This is a situation never encountered nor dealt with before. I guess it will requires a new helper logic, or some mutator logic correction.

I will look into this.
