### ISSUE TITLE
Uncaught exception when copy of original source dll was not properly cleaned up

### ISSUE THREAD

**Issue by rouke-broersma** [stryker-mutator/stryker-net#1593]
**Describe the bug**
When something happens in the mutation testrun to cause stryker to quit early the .stryker-unchanged copy of the original source code dll is not removed. Subsequent stryker runs will fail because that file already exists.

**Logs**
```
Unhandled exception. System.IO.IOException: Cannot create a file when that file already exists.
   at System.IO.FileSystem.MoveFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Move(String sourceFileName, String destFileName, Boolean overwrite)
   at System.IO.File.Move(String sourceFileName, String destFileName)
   at System.IO.Abstractions.FileWrapper.Move(String sourceFileName, String destFileName)
   at Stryker.Core.MutationTest.CsharpMutationProcess.CompileMutations() in C:\git\stryker\stryker-net\src\Stryker.Core\Stryker.Core\MutationTest\CsharpMutationProcess.cs:line 86
   at Stryker.Core.MutationTest.CsharpMutationProcess.Mutate() in C:\git\stryker\stryker-net\src\Stryker.Core\Stryker.Core\MutationTest\CsharpMutationProcess.cs:line 67
   at Stryker.Core.MutationTest.MutationTestProcess.Mutate() in C:\git\stryker\stryker-net\src\Stryker.Core\Stryker.Core\MutationTest\MutationTestProcess.cs:line 75
   at Stryker.Core.Initialisation.ProjectMutator.MutateProject(IStrykerOptions options, IReporter reporters) in C:\git\stryker\stryker-net\src\Stryker.Core\Stryker.Core\Initialisation\ProjectMutator.cs:line 41
   at Stryker.Core.Initialisation.ProjectOrchestrator.MutateProjects(StrykerOptions options, IReporter reporters)+MoveNext() in C:\git\stryker\stryker-net\src\Stryker.Core\Stryker.Core\Initialisation\ProjectOrchestrator.cs:line 61
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Stryker.Core.StrykerRunner.RunMutationTest(StrykerOptions options, IEnumerable`1 initialLogMessages) in C:\git\stryker\stryker-net\src\Stryker.Core\Stryker.Core\StrykerRunner.cs:line 59
   at Stryker.CLI.StrykerCLI.RunStryker(StrykerOptions options) in C:\git\stryker\stryker-net\src\Stryker.CLI\Stryker.CLI\StrykerCLI.cs:line 136
   at Stryker.CLI.StrykerCLI.<>c__DisplayClass7_0.<Run>b__0() in C:\git\stryker\stryker-net\src\Stryker.CLI\Stryker.CLI\StrykerCLI.cs:line 125
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass146_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Stryker.CLI.StrykerCLI.Run(String[] args) in C:\git\stryker\stryker-net\src\Stryker.CLI\Stryker.CLI\StrykerCLI.cs:line 128
   at Stryker.CLI.Program.Main(String[] args) in C:\git\stryker\stryker-net\src\Stryker.CLI\Stryker.CLI\Program.cs:line 16
```

**Additional context**
https://github.com/stryker-mutator/stryker-net/blob/v1.0/src/Stryker.Core/Stryker.Core/MutationTest/CsharpMutationProcess.cs#L87
We need to check if the file already exists and if so delete it before trying to create a new copy.

**Comment by dupdob** [comment]
I implemented a fix in one of my two PRs. Can’t remember which one, but I think it is the refactoring one.
