### ISSUE TITLE
[1.0.0-rc1] - DeployEmbeddedVsTestBinaries() Sequence contains no matching element

### ISSUE THREAD

**Issue by corentinaltepe** [stryker-mutator/stryker-net#1685]
**Describe the bug**
Hello. I'm stoked about the newly released v1.0.0-rc1. I tried it out on a real-world project. Unfortunately, I run against an error.

Here's the command line I execute:
`dotnet stryker -p C:\src\[MyProductionProject].csproj -L > debug.log`

**Logs**
I appologize, the logs are more detailed than what I'm willing to submit. Here's the end of the logs. Please let me know if there are more significant parts of the logs you might want to see.

```
[15:15:59 DBG] Initial build successful
[15:15:59 ERR] An error occurred during the mutation test run 
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at Stryker.Core.ToolHelpers.VsTestHelper.DeployEmbeddedVsTestBinaries() in C:\git\stryker\stryker-net\src\Stryker.Core\Stryker.Core\ToolHelpers\VsTestHelper.cs:line 181
   at Stryker.Core.ToolHelpers.VsTestHelper.GetVsTestToolPaths() in C:\git\stryker\stryker-net\src\Stryker.Core\Stryker.Core\ToolHelpers\VsTestHelper.cs:line 78
   at Stryker.Core.ToolHelpers.VsTestHelper.GetCurrentPlatformVsTestToolPath() in C:\git\stryker\stryker-net\src\Stryker.Core\Stryker.Core\ToolHelpers\VsTestHelper.cs:line 41
   at Stryker.Core.TestRunners.VsTest.VsTestRunner.PrepareVsTestConsole() in C:\git\stryker\stryker-net\src\Stryker.Core\Stryker.Core\TestRunners\VsTest\VsTestRunner.cs:line 554
   at Stryker.Core.TestRunners.VsTest.VsTestRunner..ctor(StrykerOptions options, ProjectInfo projectInfo, IDictionary`2 tests, TestSet testSet, IFileSystem fileSystem, IVsTestHelper helper, ILogger logger, IVsTestConsoleWrapper wrapper, Func`2 hostBuilder) in C:\git\stryker\stryker-net\src\Stryker.Core\Stryker.Core\TestRunners\VsTest\VsTestRunner.cs:line 70
   at Stryker.Core.TestRunners.VsTest.VsTestRunnerPool..ctor(StrykerOptions options, ProjectInfo projectInfo) in C:\git\stryker\stryker-net\src\Stryker.Core\Stryker.Core\TestRunners\VsTest\VsTestRunnerPool.cs:line 30
   at Stryker.Core.Initialisation.InitialisationProcess.Initialize(StrykerOptions options, DashboardReporter dashboardReporter) in C:\git\stryker\stryker-net\src\Stryker.Core\Stryker.Core\Initialisation\InitialisationProcess.cs:line 85
   at Stryker.Core.Initialisation.ProjectMutator.MutateProject(StrykerOptions options, IReporter reporters) in C:\git\stryker\stryker-net\src\Stryker.Core\Stryker.Core\Initialisation\ProjectMutator.cs:line 31
   at Stryker.Core.Initialisation.ProjectOrchestrator.MutateProjects(StrykerOptions options, IReporter reporters)+MoveNext() in C:\git\stryker\stryker-net\src\Stryker.Core\Stryker.Core\Initialisation\ProjectOrchestrator.cs:line 61
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Stryker.Core.StrykerRunner.RunMutationTest(IStrykerInputs inputs, ILoggerFactory loggerFactory, IProjectOrchestrator projectOrchestrator) in C:\git\stryker\stryker-net\src\Stryker.Core\Stryker.Core\StrykerRunner.cs:line 62
[15:15:59 INF] Time Elapsed 00:00:16.1947232
```

**Expected behavior**
I would expect to get the tests run and get the mutation results.

This works properly on v0.22.10, but not on v1.0.0-rc1.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Type of project: net5.0, with dependencies on netstandard2.0.
 - Framework Version: sdk 5.0.400
 - Stryker Version: 1.0.0-rc1

**Additional context**
Below are the test project's dependencies (some redacted) that might be relevant:

```csproj
<ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="5.0.9" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.11.0" />
    <PackageReference Include="coverlet.collector" Version="3.1.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="5.0.9" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="5.0.0" />
    <PackageReference Include="Mongo2Go" Version="3.1.3" />
    <PackageReference Include="Moq" Version="4.16.1" />
    <PackageReference Include="NUnit" Version="3.13.2" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.0.0" />
    <PackageReference Include="[OneProjetDependency]" Version="1.0.2" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\[MyMainProjectUnderTest].csproj" />
    <ProjectReference Include="..\..\[AnotherProjectDependency].csproj" />
  </ItemGroup>
```

**Comment by rouke-broersma** [comment]
I think this is my bad! I had to deploy the rc package by hand and I think I missed a step, sorry!

**Comment by rouke-broersma** [comment]
I have released rc2 which should fix this issue. Thank you for letting us know! See: https://www.nuget.org/packages/dotnet-stryker/1.0.0-rc2

**Comment by corentinaltepe** [comment]
Thank you for being so reactive! The issue is solved with rc2.
Best Regards
