### ISSUE TITLE
Exception when use flag -v or --version

### ISSUE THREAD

**Issue by IlyaAtGitHub** [stryker-mutator/stryker-net#1718]
dotnet-stryker -v

Specify --help for a list of available options and commands.
Unhandled exception. McMaster.Extensions.CommandLineUtils.CommandParsingException: Missing value for option 'v'
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.ProcessOption(OptionArgument arg)
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.ProcessNext()
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.Process()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Parse(String[] args)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Stryker.CLI.StrykerCli.Run(String[] args) in C:\git\stryker\stryker-net\src\Stryker.CLI\Stryker.CLI\StrykerCLI.cs:line 66
   at Stryker.CLI.Program.Main(String[] args) in C:\git\stryker\stryker-net\src\Stryker.CLI\Stryker.CLI\Program.cs:line 15

**Comment by rouke-broersma** [comment]
`-v/--version` is used to set the csharp language version used and not to print the stryker version. You should pass a csharp version with the `--version` option. Example: `--version csharp8`
