### ISSUE TITLE
Unhandled System.InvalidOperationException

### ISSUE THREAD

**Issue by gmdunlop** [stryker-mutator/stryker-net#1776]
**Describe the bug**
There is an unhandled exception being thrown during stryker run. This was not an issue until we updated to 1.0.0. Here we are running stryker on a template project, which doesn't have any code or tests. Previously, stryker would run successfully and produce a mutation score of 0.

**Logs**
[18:07:36 INF] Logging enabled at level Info
Version: 1.0.0-undefined

[18:07:36 DBG] Stryker started with options: {"MsBuildPath": null, "DevMode": false, "BasePath": "/../MyNewProject.Test", "OutputPath": "/../MyNewProject.Test/StrykerOutput/2021-11-02.18-07-36", "SolutionPath": "/../MyNewProject.sln", "TargetFramework": null, "LogOptions": {"LogToFile": false, "LogLevel": "Debug", "$type": "LogOptions"}, "MutationLevel": "Standard", "Thresholds": {"High": 80, "Low": 60, "Break": 0, "$type": "Thresholds"}, "AdditionalTimeout": 5000, "LanguageVersion": "Default", "Concurrency": 4, "ProjectUnderTestName": "", "TestProjects": [], "TestCaseFilter": "", "WithBaseline": false, "Reporters": ["Json"], "BaselineProvider": "Disk", "AzureFileStorageUrl": "", "AzureFileStorageSas": "", "DashboardUrl": "https://dashboard.stryker-mutator.io", "DashboardApiKey": null, "Since": false, "SinceTarget": null, "DiffIgnoreChanges": [], "FallbackVersion": null, "ModuleName": "", "Mutate": [{"Glob": {"Tokens": [{"TrailingPathSeparator": {"Value": "/", "$type": "PathSeparatorToken"}, "LeadingPathSeparator": null, "$type": "WildcardDirectoryToken"}, {"$type": "WildcardToken"}], "$type": "Glob"}, "IsExclude": false, "TextSpans": [{"Start": 0, "End": 2147483647, "Length": 2147483647, "IsEmpty": false, "$type": "TextSpan"}], "$type": "FilePattern"}], "IgnoredMethods": [], "ExcludedMutations": [], "ExcludedLinqExpressions": [], "OptimizationMode": "CoverageBasedTest", "ProjectName": "", "ProjectVersion": "", "$type": "StrykerOptions"}
[18:07:37 INF] Identifying project to mutate.
[18:07:37 DBG] Using /../MyNewProject.Test.csproj as test project
[18:07:37 DBG] Analyzing solution file /../MyNewProject.sln
[18:07:37 DBG] Analyzing project file /../MyNewProject.Test.csproj
A new version of Stryker.NET (1.0.0) is available. Please consider upgrading using `dotnet tool update -g dotnet-stryker`

A preview version of Stryker.NET (1.0.0) is available.
If you would like to try out this preview version you can install it with `dotnet tool update -g dotnet-stryker --version 1.0.0`
Since this is a preview feature things might not work as expected! Please report any findings on GitHub!

[18:07:39 DBG] Using /../.MyNewProject.csproj as project under test
[18:07:39 INF] The project /../MyNewProject.csproj will be mutated.
[18:07:39 DBG] Analyzing solution file /../MyNewProject.sln
[18:07:39 DBG] Analyzing project file /../MyNewProject.csproj
[18:07:40 DBG] Skipping auto-generated code file: /../MyNewProject.AssemblyInfo.cs
[18:07:40 INF] Analysis complete.
[18:07:40 INF] Building test project /../MyNewProject.Test.csproj (1/1)
[18:07:40 DBG] Started initial build using dotnet build
[18:07:40 DBG] Initial build using path: /../MyNewProject.sln
[18:07:45 DBG] Initial build successful
[18:07:45 DBG] VsTest zip was copied to: /tmp/ogqrqsyx.v3b/.vstest/vstest.zip
[18:07:45 DBG] VsTest zip was unzipped to: /tmp/ogqrqsyx.v3b/.vstest
[18:07:45 DBG] Using vstest from deployed vstest package
[18:07:45 DBG] Using vstest.console: /tmp/ogqrqsyx.v3b/.vstest/tools/netcoreapp2.1/vstest.console.dll for OS LINUX
[18:07:50 INF] Total number of tests found: Unable to detect.
[18:07:50 INF] Initial testrun started.
[18:07:51 DBG] Initial testrun output: .
[18:07:51 DBG] 0 mutants created
[18:07:51 DBG] Trying compilation for the first time.
[18:07:53 DBG] Compilation successful
[18:07:53 DBG] Injected the mutated assembly file into /../MyNewProject.dll
[18:07:53 INF] 0 mutants created
[18:07:53 INF] Capture mutant coverage using 'CoverageBasedTest' mode.
[18:07:53 DBG] Runner 1: Capturing coverage.
[18:07:54 INF] Time Elapsed 00:00:17.6589391
Unhandled exception. System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Max[TSource](IEnumerable`1 source, Func`2 selector)
   at Stryker.Core.TestRunners.VsTest.VsTestRunner.ParseResultsForCoverage(IEnumerable`1 testResults, IEnumerable`1 mutants)
   at Stryker.Core.TestRunners.VsTest.VsTestRunner.CaptureCoverage(IEnumerable`1 mutants)
   at Stryker.Core.TestRunners.VsTest.VsTestRunnerPool.CaptureCoverage(IEnumerable`1 mutants)
   at Stryker.Core.CoverageAnalysis.CoverageAnalyser.DetermineTestCoverage()
   at Stryker.Core.MutationTest.MutationTestProcess.GetCoverage()
   at Stryker.Core.StrykerRunner.AnalyseCoverage(StrykerOptions options)
   at Stryker.Core.StrykerRunner.RunMutationTest(IStrykerInputs inputs, ILoggerFactory loggerFactory, IProjectOrchestrator projectOrchestrator)
   at Stryker.CLI.StrykerCli.RunStryker(IStrykerInputs inputs) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 90
   at Stryker.CLI.StrykerCli.<>c__DisplayClass9_0.<Run>b__0() in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 65
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass146_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Stryker.CLI.StrykerCli.Run(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 71
   at Stryker.CLI.Program.Main(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/Program.cs:line 15

**Expected behavior**
Stryker should run successfully and produce a mutation score of 0.

**Desktop (please complete the following information):**
 - OS: Linux
 - Type of project: .NET core
 - Framework Version: 3.1
 - Stryker Version: 1.0.0-undefined

**Additional context**
I shortened the file paths to not include company info.
Stryker command: dotnet stryker --solution $solutionPath --reporter "json" --verbosity debug
Command used to download stryker: dotnet tool install dotnet-stryker

**Comment by richardwerkman** [comment]
I suspect this has something to do with the message:
`[18:07:50 INF] Total number of tests found: Unable to detect.`

The same data is used for coverage analysis. Thats why I think we get a sequence contains no elements. But this will be hard to solve without a reproduction project. 

As you removed the paths I take it we can't get access to your project to reproduct this bug?

Btw, if you turn off coverage analysis you should still be able to use stryker (but it will be slow)

**Comment by gmdunlop** [comment]
Correct, you won't be able to access the exact project, but it is basically just an empty NET core project with an empty test project. I think I will turn off coverage analysis for now since it's not necessary for us.

**Comment by dupdob** [comment]
This problem has been reported also as part of #1781. Latest version of Stryker crashes when there is no mutant.
I have a fix ready, I will open a PR shortly.
