### ISSUE TITLE
Stryker throws for the mutant-free world

### ISSUE THREAD

**Issue by psfinaki** [stryker-mutator/stryker-net#1806]
**Describe the bug**
Wanted to test the latest feature but got an exception:
```csharp
PS C:\Users\psemkin\Desktop\Repro\Repro.Test> dotnet stryker

   _____ _              _               _   _ ______ _______  
  / ____| |            | |             | \ | |  ____|__   __| 
 | (___ | |_ _ __ _   _| | _____ _ __  |  \| | |__     | |    
  \___ \| __| '__| | | | |/ / _ \ '__| | . ` |  __|    | |    
  ____) | |_| |  | |_| |   <  __/ |    | |\  | |____   | |    
 |_____/ \__|_|   \__, |_|\_\___|_| (_)|_| \_|______|  |_|    
                   __/ |                                      
                  |___/                                       


Version: 1.1.0

[14:01:16 INF] Identifying project to mutate.
[14:01:19 INF] The project C:\Users\psemkin\Desktop\Repro\Repro\Repro.csproj will be mutated.
[14:01:21 INF] Analysis complete.
[14:01:21 INF] Building test project C:\Users\psemkin\Desktop\Repro\Repro.Test\Repro.Test.csproj (1/1)
[14:01:28 INF] Total number of tests found: 1.
[14:01:28 INF] Initial testrun started.
[14:01:31 INF] 0 mutants created
[14:01:31 INF] Capture mutant coverage using 'CoverageBasedTest' mode.
[14:01:33 WRN] It's a mutant-free world, nothing to test.
[14:01:34 INF] Time Elapsed 00:00:17.6776698
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Stryker.Core.Reporters.Progress.ProgressBar.Tick(String message) in /_/src/Stryker.Core/Stryker.Core/Reporters/Progress/ProgressBar.cs:line 36
   at Stryker.Core.Reporters.Progress.ProgressBarReporter.ReportFinalState() in /_/src/Stryker.Core/Stryker.Core/Reporters/Progress/ProgressBarReporter.cs:line 68
   at Stryker.Core.Reporters.Progress.ProgressReporter.OnAllMutantsTested(IReadOnlyProjectComponent reportComponent) in /_/src/Stryker.Core/Stryker.Core/Reporters/Progress/ProgressReporter.cs:line 32
   at Stryker.Core.Reporters.BroadcastReporter.OnAllMutantsTested(IReadOnlyProjectComponent reportComponent) in /_/src/Stryker.Core/Stryker.Core/Reporters/BroadcastReporter.cs:line 63
   at Stryker.Core.StrykerRunner.RunMutationTest(IStrykerInputs inputs, ILoggerFactory loggerFactory, IProjectOrchestrator projectOrchestrator) in /_/src/Stryker.Core/Stryker.Core/StrykerRunner.cs:line 95
   at Stryker.CLI.StrykerCli.RunStryker(IStrykerInputs inputs) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 90
   at Stryker.CLI.StrykerCli.<>c__DisplayClass9_0.<Run>b__0() in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 65
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass146_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Stryker.CLI.StrykerCli.Run(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 71
   at Stryker.CLI.Program.Main(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/Program.cs:line 15
```

So I guess things work in general, it's just the latest mutation report voodoo broke something.

**Expected behavior**
Generated report with the mutation score 100 - or at least no exception.

**Desktop (please complete the following information):**
 - OS: Windows
 - Type of project: core
 - Framework Version: net6
 - Stryker Version: 1.1.0

**Additional context**
Repro: [Repro.zip](https://github.com/stryker-mutator/stryker-net/files/7546478/Repro.zip)

**Comment by rouke-broersma** [comment]
I think this might be specifically the progressbar that's broken. I did not run my test with it enabled 🙈

**Comment by psfinaki** [comment]
Yes, I confirm this :)

**Comment by Meffistas** [comment]
Same issue with ClearTextReporter on row 65.

**Comment by JadersonGomes** [comment]
> 

I have the same error. How can I disable this, could you help me?

**Comment by rouke-broersma** [comment]
You can disable the broken reporters.

**Comment by psfinaki** [comment]
Thanks for fixing, verified it for me as well 👍 

Is there any released planned for soon? This is not urgent, so just asking, no pushing :)

**Comment by rouke-broersma** [comment]
> Thanks for fixing, verified it for me as well 👍 
> 
> Is there any released planned for soon? This is not urgent, so just asking, no pushing :)

We can release tomorrow probably

**Comment by psfinaki** [comment]
Amazing, thanks!

**Comment by richardwerkman** [comment]
@psfinaki this has been released just now!

**Comment by psfinaki** [comment]
Thanks a lot, Richard :)
