### ISSUE TITLE
Compile error relating to indexer method

### ISSUE THREAD

**Issue by oliwennell** [stryker-mutator/stryker-net#1839]
**Describe the bug**
Hi, I think I've found a bug where Stryker generates a non-compilable mutation when C# indexers are used.

**Logs**
[stryker-log.txt](https://github.com/stryker-mutator/stryker-net/files/7735896/stryker-log.txt)

**Expected behavior**

Given a method that uses an indexer:
```
public class ThingWithIndexer
{
    private readonly Dictionary<string, List<string>> _dictionary = new();

    public List<string> this[string key]
    {
        get
        {
            if (_dictionary.TryGetValue(key, out var value))
            {
                return value;
            }
    
            var result = new List<string>();
            _dictionary.Add(key, result);
            return result;
        }
    }
}
```

Instead of generating a mutation report, Stryker instead returns an error. The relevant output being:
```
Stryker.NET encountered an compile error in <redacted>\ThingWithIndexer.cs (at 8:8) with message: 'ThingWithIndexer.this[string].get': not all code paths return a value (Source code: get
{if(Stryker1xw31fAaPhATnF0.MutantControl.IsActive(0)){}else{if(Stryker1xw31fAaPhATnF0.MutantControl.IsActive(1))        {
            if (!(_dictionary.TryGetValue(key, out var value)))
            {
                return value;
            }

            var result = new List<string>();
            _dictionary.Add(key, result);
            return result;
        }
else        {
            if (_dictionary.TryGetValue(key, out var value))
{if(Stryker1xw31fAaPhATnF0.MutantControl.IsActive(2)){}else            {
                return value;
            }
}
            var result = new List<string>();
if(Stryker1xw31fAaPhATnF0.MutantControl.IsActive(3)){;}else{            _dictionary.Add(key, result);
}            return result;
        }
}})
[14:42:41 WRN] Safe Mode! Stryker will try to continue by rolling back all mutations in method. This should not happen, please report this as an issue on github with the previous error message.
[14:42:41 INF] 4 mutants created
[14:42:41 INF] Capture mutant coverage using 'CoverageBasedTest' mode.
[14:42:42 INF] 4     mutants got status CompileError. Reason: Mutant caused compile errors
[14:42:42 INF] 4     total mutants are skipped for the above mentioned reasons
[14:42:42 INF] 0     total mutants will be tested
[14:42:43 INF] Time Elapsed 00:00:13.8404451
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Type of project core
 - Framework Version core 6.0
 - Stryker Version 1,2,1

**Additional context**

In case it's useful, the unit test I used in this repro was:
```
public class Tests
{
    [Test]
    public void Test1()
    {
        var thing = new ThingWithIndexer();
        thing["a"].Add("aaa");
        Assert.That(thing["a"], Is.EquivalentTo(new[] { "aaa" }));
    }
}
```

If I change the indexer to be a normal method (e.g. `public List<string> GetOrCreate(string key)`) , Stryker runs successfully.

Stryker also seems to throw a second exception when it exits, not sure if that's related:
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Stryker.Core.Reporters.Progress.ProgressBar.Tick(String message) in /_/src/Stryker.Core/Stryker.Core/Reporters/Progress/ProgressBar.cs:line 36
   at Stryker.Core.Reporters.Progress.ProgressBarReporter.ReportFinalState() in /_/src/Stryker.Core/Stryker.Core/Reporters/Progress/ProgressBarReporter.cs:line 68
   at Stryker.Core.Reporters.Progress.ProgressReporter.OnAllMutantsTested(IReadOnlyProjectComponent reportComponent) in /_/src/Stryker.Core/Stryker.Core/Reporters/Progress/ProgressReporter.cs:line 32
   at Stryker.Core.Reporters.BroadcastReporter.OnAllMutantsTested(IReadOnlyProjectComponent reportComponent) in /_/src/Stryker.Core/Stryker.Core/Reporters/BroadcastReporter.cs:line 63
   at Stryker.Core.StrykerRunner.RunMutationTest(IStrykerInputs inputs, ILoggerFactory loggerFactory, IProjectOrchestrator projectOrchestrator) in /_/src/Stryker.Core/Stryker.Core/StrykerRunner.cs:line 94
   at Stryker.CLI.StrykerCli.RunStryker(IStrykerInputs inputs) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 90
   at Stryker.CLI.StrykerCli.<>c__DisplayClass9_0.<Run>b__0() in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 65
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass146_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Stryker.CLI.StrykerCli.Run(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 71
   at Stryker.CLI.Program.Main(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/Program.cs:line 15
```

**Comment by rouke-broersma** [comment]
Your second issue will probably be fixed by #1833
