### ISSUE TITLE
InvalidOperationException: Can't extract original expression when running stryker-dotnet

### ISSUE THREAD

**Issue by b3b00** [stryker-mutator/stryker-net#1847]
when trying to stryke the unit test of my project (ParserTests.csproj" in https://github.com/b3b00/csly i get an exception stopping the execution

```
Unhandled exception. System.InvalidOperationException: Can't extract original expression from {if(StrykerXzgiWGN6TVeZSlm.MutantControl.IsActive(1785)){return!(x is TerminalClause<IN,OUT> || x is ChoiceClause<IN,OUT>) && (x is TerminalClause<IN,OUT> t && !t.Discarded) || (x is ChoiceClause<IN,OUT> c && !c.IsDiscarded) ;}else{return(StrykerXzgiWGN6TVeZSlm.MutantControl.IsActive(1786)?(x is TerminalClause<IN,OUT> || x is ChoiceClause<IN,OUT>) :!((StrykerXzgiWGN6TVeZSlm.MutantControl.IsActive(1787)?x is TerminalClause<IN,OUT> && x is ChoiceClause<IN,OUT>:x is TerminalClause<IN,OUT> || x is ChoiceClause<IN,OUT>)) )|| (x is TerminalClause<IN,OUT> t && !t.Discarded) || (x is ChoiceClause<IN,OUT> c && !c.IsDiscarded) ;}}
   at Stryker.Core.Instrumentation.AnonymousFunctionExpressionToBodyEngine.Revert(AnonymousFunctionExpressionSyntax node) in /_/src/Stryker.Core/Stryker.Core/Instrumentation/AnonymousFunctionExpressionToBodyEngine.cs:line 41
   at Stryker.Core.Instrumentation.BaseEngine`1.RemoveInstrumentation(SyntaxNode node) in /_/src/Stryker.Core/Stryker.Core/Instrumentation/BaseEngine.cs:line 47
   at Stryker.Core.Mutants.MutantPlacer.RemoveMutant(SyntaxNode nodeToRemove) in /_/src/Stryker.Core/Stryker.Core/Mutants/MutantPlacer.cs:line 114
   at Stryker.Core.Compiling.RollbackProcess.RemoveMutantIfStatements(SyntaxTree originalTree, IEnumerable`1 diagnosticInfo, Boolean devMode) in /_/src/Stryker.Core/Stryker.Core/Compiling/RollbackProcess.cs:line 253
   at Stryker.Core.Compiling.RollbackProcess.Start(CSharpCompilation compiler, ImmutableArray`1 diagnostics, Boolean lastAttempt, Boolean devMode) in /_/src/Stryker.Core/Stryker.Core/Compiling/RollbackProcess.cs:line 59
   at Stryker.Core.Compiling.CsharpCompilingProcess.TryCompilation(Stream ms, Stream symbolStream, CSharpCompilation compilation, EmitResult previousEmitResult, Boolean lastAttempt, Boolean devMode, Int32 retryCount) in /_/src/Stryker.Core/Stryker.Core/Compiling/CsharpCompilingProcess.cs:line 134
   at Stryker.Core.Compiling.CsharpCompilingProcess.Compile(IEnumerable`1 syntaxTrees, Stream ilStream, Stream symbolStream, Boolean devMode) in /_/src/Stryker.Core/Stryker.Core/Compiling/CsharpCompilingProcess.cs:line 81
   at Stryker.Core.MutationTest.CsharpMutationProcess.CompileMutations() in /_/src/Stryker.Core/Stryker.Core/MutationTest/CsharpMutationProcess.cs:line 74
   at Stryker.Core.MutationTest.CsharpMutationProcess.Mutate() in /_/src/Stryker.Core/Stryker.Core/MutationTest/CsharpMutationProcess.cs:line 66
   at Stryker.Core.MutationTest.MutationTestProcess.Mutate() in /_/src/Stryker.Core/Stryker.Core/MutationTest/MutationTestProcess.cs:line 116
   at Stryker.Core.Initialisation.ProjectMutator.MutateProject(StrykerOptions options, IReporter reporters) in /_/src/Stryker.Core/Stryker.Core/Initialisation/ProjectMutator.cs:line 42
   at Stryker.Core.Initialisation.ProjectOrchestrator.MutateProjects(StrykerOptions options, IReporter reporters)+MoveNext() in /_/src/Stryker.Core/Stryker.Core/Initialisation/ProjectOrchestrator.cs:line 61
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Stryker.Core.StrykerRunner.RunMutationTest(IStrykerInputs inputs, ILoggerFactory loggerFactory, IProjectOrchestrator projectOrchestrator) in /_/src/Stryker.Core/Stryker.Core/StrykerRunner.cs:line 58
   at Stryker.CLI.StrykerCli.RunStryker(IStrykerInputs inputs) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 90
   at Stryker.CLI.StrykerCli.<>c__DisplayClass9_0.<Run>b__0() in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 65
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass146_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Stryker.CLI.StrykerCli.Run(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 71
   at Stryker.CLI.Program.Main(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/Program.cs:line 15
```

**Desktop (please complete the following information):**
 - OS: win10
 - Type of project : dotnet core xunit test 
 - Framework Version core 3.1
 - Stryker Version 1.2.1

**Comment by b3b00** [comment]
I 've found a workaround rewriting my code from: 
```c#
var realClauses = rule.Clauses.Where(x => !(x is TerminalClause<IN,OUT> || x is ChoiceClause<IN,OUT>) || (x is TerminalClause<IN,OUT> t && !t.Discarded) || (x is ChoiceClause<IN,OUT> c && !c.IsDiscarded) ).ToList();
```

to : 

```c#
Func<IClause<IN, OUT>,bool> realClausesPredicate = (IClause<IN, OUT> x) =>
                {
                    return !(x is TerminalClause<IN, OUT> || x is ChoiceClause<IN, OUT>) ||
                           (x is TerminalClause<IN, OUT> t && !t.Discarded) ||
                           (x is ChoiceClause<IN, OUT> c && !c.IsDiscarded);
                };
                
                var realClauses = rule.Clauses.Where(realClausesPredicate).ToList();
```

**Comment by dupdob** [comment]
Thanks for reporting!
I will look into this.
Stryker often needs to convert 'expression form' method/lambda/accessor to body form in order to inject mutations. In case of massive roll back, Stryker normally reverts the mutated method/lambda/accessor to expression form. There is clearly a bug here, I will reproduce and fix it when time permits.

As a simpler work around, you should be able to use anonymous lambda in body form (i.e. you don't need a separate declaration)

**Comment by dupdob** [comment]
@b3b00 : I am trying to reproduce the issue, but the code line you provided is properly mutated in my sample:
``` csharp
var realClauses = rule.Clauses.Where(x => !(x is TerminalClause<IN,OUT> || x is ChoiceClause<IN,OUT>) || (x is TerminalClause<IN,OUT> t && !t.Discarded) || (x is ChoiceClause<IN,OUT> c && !c.IsDiscarded) ).ToList();
```
it triggers some build error during mutation but those are properly rolled back and the test run can proceed.

Can you test with the very last version to see if you still have the issue ? 
And could provide the full method that cause the problem or a project allowing to reproduce it ?

**Comment by rouke-broersma** [comment]
> And could provide the full method that cause the problem or a project allowing to reproduce it ? 

I think the project is https://github.com/b3b00/csly

**Comment by dupdob** [comment]
Thanks. This is the one

**Comment by b3b00** [comment]
@dupdob to be complete , the project to stryke is sly/sly.csproj and unit test project is ParserTests/parserTests.csproj

**Comment by b3b00** [comment]
using latest version (1.2.2)  i still get the error

**Comment by b3b00** [comment]
One last thing : main branch is dev

**Comment by dupdob** [comment]
thanks for the details. I figured them myself and I am working on this. Your codebase raises several issues, this one being the most obvious

**Comment by dupdob** [comment]
This bug is due to Stryker.Net rolling back some mutations in the wrong order; I have reproduced it and fixed it here.
I will fix a bunch of other bugs along the way before opening a PR.

**Comment by pawelhevy** [comment]
Hi 
I have simillar problem in my project. Stryker failed totaly with exception:
```
Unhandled exception. System.InvalidOperationException: Can't extract original expression from {{return client.SendCompleted -= handler;}}
   at Stryker.Core.Instrumentation.AnonymousFunctionExpressionToBodyEngine.Revert(AnonymousFunctionExpressionSyntax node) in /_/src/Stryker.Core/Stryker.Core/Instrumentation/AnonymousFunctionExpressionToBodyEngine.cs:line 40
   at Stryker.Core.Instrumentation.BaseEngine`1.RemoveInstrumentation(SyntaxNode node) in /_/src/Stryker.Core/Stryker.Core/Instrumentation/BaseEngine.cs:line 47
   at Stryker.Core.Mutants.MutantPlacer.RemoveMutant(SyntaxNode nodeToRemove) in /_/src/Stryker.Core/Stryker.Core/Mutants/MutantPlacer.cs:line 114
   at Stryker.Core.Compiling.RollbackProcess.RemoveMutantIfStatements(SyntaxTree originalTree, IEnumerable`1 diagnosticInfo, Boolean devMode) in /_/src/Stryker.Core/Stryker.Core/Compiling/RollbackProcess.cs:line 253
   at Stryker.Core.Compiling.RollbackProcess.Start(CSharpCompilation compiler, ImmutableArray`1 diagnostics, Boolean lastAttempt, Boolean devMode) in /_/src/Stryker.Core/Stryker.Core/Compiling/RollbackProcess.cs:line 59
   at Stryker.Core.Compiling.CsharpCompilingProcess.TryCompilation(Stream ms, Stream symbolStream, CSharpCompilation compilation, EmitResult previousEmitResult, Boolean lastAttempt, Boolean devMode, Int32 retryCount) in /_/src/Stryker.Core/Stryker.Core/Compiling/CsharpCompilingProcess.cs:line 134
   at Stryker.Core.Compiling.CsharpCompilingProcess.Compile(IEnumerable`1 syntaxTrees, Stream ilStream, Stream symbolStream, Boolean devMode) in /_/src/Stryker.Core/Stryker.Core/Compiling/CsharpCompilingProcess.cs:line 81
   at Stryker.Core.MutationTest.CsharpMutationProcess.CompileMutations() in /_/src/Stryker.Core/Stryker.Core/MutationTest/CsharpMutationProcess.cs:line 74
   at Stryker.Core.MutationTest.CsharpMutationProcess.Mutate() in /_/src/Stryker.Core/Stryker.Core/MutationTest/CsharpMutationProcess.cs:line 66
   at Stryker.Core.MutationTest.MutationTestProcess.Mutate() in /_/src/Stryker.Core/Stryker.Core/MutationTest/MutationTestProcess.cs:line 116
   at Stryker.Core.Initialisation.ProjectMutator.MutateProject(StrykerOptions options, IReporter reporters) in /_/src/Stryker.Core/Stryker.Core/Initialisation/ProjectMutator.cs:line 42
   at Stryker.Core.Initialisation.ProjectOrchestrator.MutateProjects(StrykerOptions options, IReporter reporters)+MoveNext() in /_/src/Stryker.Core/Stryker.Core/Initialisation/ProjectOrchestrator.cs:line 61
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Stryker.Core.StrykerRunner.RunMutationTest(IStrykerInputs inputs, ILoggerFactory loggerFactory, IProjectOrchestrator projectOrchestrator) in /_/src/Stryker.Core/Stryker.Core/StrykerRunner.cs:line 58
   at Stryker.CLI.StrykerCli.RunStryker(IStrykerInputs inputs) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 90
   at Stryker.CLI.StrykerCli.<>c__DisplayClass9_0.<Run>b__0() in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 65
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass143_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Stryker.CLI.StrykerCli.Run(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 71
   at Stryker.CLI.Program.Main(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/Program.cs:line 15
```

This is caused by my (in my project)
```
Action unsubscribe = () => client.SendCompleted -= handler;
```

But it works if I replace it by (like in https://github.com/stryker-mutator/stryker-net/issues/1847#issuecomment-1003970854)
```
Action unsubscribe = () => { client.SendCompleted -= handler; };
```

I've notice that there is not implemented case in switch statement:
![image](https://user-images.githubusercontent.com/7288991/153584247-7943de2d-ef35-4d3c-80f6-9b8e7b8554d6.png)
But when I change my code (fix mentioned above) this method is not even called

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Type of project: core
 - Framework Version: net6.0
 - Stryker Version: 1.3.1

**Comment by rouke-broersma** [comment]
@pawelhevy could you create a new issue? The original issue is solved, your issue is probably due to a slightly different syntax or problem.

**Comment by pawelhevy** [comment]
I've created https://github.com/stryker-mutator/stryker-net/issues/1902. Thanks!
