### ISSUE TITLE
ProgressBar NRE when no mutants tested

### ISSUE THREAD

**Issue by commonquail** [stryker-mutator/stryker-net#1864]
This is similar to #1806.

When Stryker.NET 1.2.2 generates some non-zero amount of mutations but skips all of them the ProgressBar reporter throws a NullReferenceException:

```
Version: 1.2.2

[14:57:24 INF] Identifying project to mutate.
[14:57:25 INF] The project /tmp/tmp.g40Wn4yMdA/l/l.csproj will be mutated.
[14:57:26 INF] Analysis complete.
[14:57:26 INF] Building test project /tmp/tmp.g40Wn4yMdA/t/t.csproj (1/1)
[14:57:29 INF] Total number of tests found: 1.
[14:57:29 INF] Initial testrun started.
[14:57:31 INF] 1 mutants created
[14:57:31 INF] Capture mutant coverage using 'CoverageBasedTest' mode.
[14:57:32 INF] 1     mutants got status NoCoverage.   Reason: Mutant has no test coverage
[14:57:32 INF] 1     total mutants are skipped for the above mentioned reasons
[14:57:32 INF] 0     total mutants will be tested
[14:57:32 WRN] It looks like all non-ignored mutants are not covered by a test. Go add some tests!
[14:57:33 INF] Time Elapsed 00:00:09.5080642
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Stryker.Core.Reporters.Progress.ProgressBar.Tick(String message)
   at Stryker.Core.Reporters.Progress.ProgressBarReporter.ReportFinalState()
   at Stryker.Core.Reporters.Progress.ProgressReporter.OnAllMutantsTested(IReadOnlyProjectComponent reportComponent)
   at Stryker.Core.Reporters.BroadcastReporter.OnAllMutantsTested(IReadOnlyProjectComponent reportComponent)
   at Stryker.Core.StrykerRunner.RunMutationTest(IStrykerInputs inputs, ILoggerFactory loggerFactory, IProjectOrchestrator projectOrchestrator)
   at Stryker.CLI.StrykerCli.RunStryker(IStrykerInputs inputs) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 90
   at Stryker.CLI.StrykerCli.<>c__DisplayClass9_0.<Run>b__0() in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 65
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass146_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Stryker.CLI.StrykerCli.Run(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 71
   at Stryker.CLI.Program.Main(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/Program.cs:line 15
```

The mutation target is a new classlib project containing only

```csharp
namespace l;
public class Class1
{
    int n()
    {
        return 42;
    }
}
```

This happens because [`StrykerRunner::RunMutationTest` calls `BroadcastReporter::OnAllMutantsTested` before `BroadcastReporter::OnStartMutantTestRun`][run].

`OnStartMutantTestRun` calls into `ProgressBarReporter::ReportInitialState`, which calls into `ProgressBar::Start`, [which initializes the `_progressBar` field][start]. However, when all mutants are skipped, `RunMutationTest` proceeds straight into `OnAllMutantsTested`, which calls into `ProgressBarReporter::ReportFinalState`, which calls [`ProgressBar::Tick`, which needs the not yet initialized `_progressBar`][tick].

[run]: https://github.com/stryker-mutator/stryker-net/blob/db75d6f0a60bd451e57a97e16565aa1674d69e0b/src/Stryker.Core/Stryker.Core/StrykerRunner.cs#L73-L102
[start]: https://github.com/stryker-mutator/stryker-net/blob/db75d6f0a60bd451e57a97e16565aa1674d69e0b/src/Stryker.Core/Stryker.Core/Reporters/Progress/ProgressBar.cs#L29-L31
[tick]: https://github.com/stryker-mutator/stryker-net/blob/db75d6f0a60bd451e57a97e16565aa1674d69e0b/src/Stryker.Core/Stryker.Core/Reporters/Progress/ProgressBar.cs##L34-L36

**Comment by psfinaki** [comment]
Nope, still not working :)
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/5451366/150982088-099a45a7-8394-4825-9e33-563dd4abe83d.png">

[Repro.zip](https://github.com/stryker-mutator/stryker-net/files/7933735/Repro.zip)

@rouke-broersma @dupdob don't want to create a new bug but cannot reopen this one...
My humble advice - time to create some integration test for this, gentlemen ;)

**Comment by dupdob** [comment]
This was an opportunistic tentative fix as I indeed did not add a (regression test) for this. I now have a proper test, hence a better fix to push.
