### ISSUE TITLE
Stryker crashes when running in Azure Devops pipeline

### ISSUE THREAD

**Issue by Al4ric** [stryker-mutator/stryker-net#1938]
**Describe the bug**
When running in Azure pipeline on Ubuntu image as script:
dotnet stryker --threshold-high 90 --threshold-low 75
After couple of errors:
[09:54:28 ERR] Mutation not found, this should not happen
I get nullreference with following stack

**Logs**
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Stryker.Core.Mutants.MutantPlacer.RemoveMutant(SyntaxNode nodeToRemove)
   at Stryker.Core.Compiling.RollbackProcess.RemoveMutantIfStatements(SyntaxTree originalTree, IEnumerable`1 diagnosticInfo, Boolean devMode)
   at Stryker.Core.Compiling.RollbackProcess.Start(CSharpCompilation compiler, ImmutableArray`1 diagnostics, Boolean lastAttempt, Boolean devMode)
   at Stryker.Core.Compiling.CsharpCompilingProcess.TryCompilation(Stream ms, Stream symbolStream, CSharpCompilation compilation, EmitResult previousEmitResult, Boolean lastAttempt, Boolean devMode, Int32 retryCount)
   at Stryker.Core.Compiling.CsharpCompilingProcess.Compile(IEnumerable`1 syntaxTrees, Stream ilStream, Stream symbolStream, Boolean devMode)
   at Stryker.Core.MutationTest.CsharpMutationProcess.CompileMutations()
   at Stryker.Core.MutationTest.CsharpMutationProcess.Mutate()
   at Stryker.Core.MutationTest.MutationTestProcess.Mutate()
   at Stryker.Core.Initialisation.ProjectMutator.MutateProject(StrykerOptions options, IReporter reporters)
   at Stryker.Core.Initialisation.ProjectOrchestrator.MutateProjects(StrykerOptions options, IReporter reporters)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Stryker.Core.StrykerRunner.RunMutationTest(IStrykerInputs inputs, ILoggerFactory loggerFactory, IProjectOrchestrator projectOrchestrator)
   at Stryker.CLI.StrykerCli.RunStryker(IStrykerInputs inputs) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 90
   at Stryker.CLI.StrykerCli.<>c__DisplayClass9_0.<Run>b__0() in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 65
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass143_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Stryker.CLI.StrykerCli.Run(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 71
   at Stryker.CLI.Program.Main(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/Program.cs:line 15

**Expected behavior**
Runs ends successfully

**Desktop (please complete the following information):**
 - OS: Ubuntu-latest
 - Type of project Class Library (packed into nuget)
 - Framework Version 6.0
 - Stryker Version 2.198.0

**Additional context**
Running in Azure Devops with following:
pool:
  vmImage: ubuntu-latest

**Comment by rouke-broersma** [comment]
Sounds like a duplicate of #1937. Could you try reverting to a previous version as a workaround?

**Comment by Al4ric** [comment]
You are right. That is the case. Previous version works.
