### ISSUE TITLE
Tool generates negative RunConfiguration.TestSessionTimeout which throws SettingsException

### ISSUE THREAD

**Issue by iamdmitrij** [stryker-mutator/stryker-net#2002]
**Describe the bug**
After minor version update newest to the `dotnet-stryker` 1.5.1 tool, test execution fail. After enabling verbose logs, job fails because of negative `RunConfiguration.TestSessionTimeout` setting which throws an exception: `[Error] Microsoft.VisualStudio.TestPlatform.ObjectModel.SettingsException: Invalid settings 'RunConfiguration'.  Invalid value '-169088' specified for 'TestSessionTimeout'.` 

Example of failing [job](https://github.com/iamdmitrij/Tethos/runs/6066782447?check_suite_focus=true). 

Tool is invoked simply using `dotnet stryker` command:

```
dotnet stryker --config-file test/Tethos.Tests/stryker-config.json
  --version "$target_branch"
  --reporter "$extra_reporter"
  --reporter "cleartext"
  --reporter "html"
```
Full job definition can be found [here](https://github.com/iamdmitrij/Tethos/blob/c7380c597706fe8db854fa61be45ab6964031492/.github/workflows/stryker.yml#L70).

Note: Works fine with v1.5.0 with an [example job](https://github.com/iamdmitrij/Tethos/runs/6066941867?check_suite_focus=true).

**Logs**
```
[14:36:30 DBG] Runner 0: Using -169088 ms as test run timeout
[14:36:30 VRB] Runner 0: VsTest run settings set to: <RunSettings>
 <RunConfiguration>

  <MaxCpuCount>1</MaxCpuCount>
<TestSessionTimeout>-169088</TestSessionTimeout>

<DisableParallelization>true</DisableParallelization>
<DesignMode>false</DesignMode>
<BatchSize>1</BatchSize>

 </RunConfiguration>
<InProcDataCollectionRunSettings><InProcDataCollectors><InProcDataCollector friendlyName="StrykerCoverage" uri="https://stryker-mutator.io/" codebase="/home/runner/.dotnet/tools/.store/dotnet-stryker/1.5.1/dotnet-stryker/1.5.1/tools/net5.0/any/Stryker.DataCollector.dll" assemblyQualifiedName="Stryker.DataCollector.CoverageCollector, Stryker.DataCollector, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null">
<Configuration><Parameters><Mutant id='42' tests='23bae28c-17fa-9f1e-0f0b-0db4f21e11e3'/><Mutant id='48' tests='808036fc-5b2a-2989-183f-e2fe0e3d9ae3'/><Mutant id='49' tests='722834a5-e8af-ddf9-93d4-079787facdb7'/><Mutant id='50' tests='063e1e69-54f3-842e-9e24-a6f3f7cf1cf3'/><Mutant id='9' tests='ee944c96-c847-fee4-72b9-6b1df81aae40,fff51969-2e71-b134-9a61-f6a13c5b9d35'/><Mutant id='33' tests='e3676fae-eac6-ea07-5beb-305fae116731,8b444e74-5097-d7ee-035c-faba28a5203b'/><Mutant id='23' tests='50b8f8b5-6dde-937e-b591-2fdf4cca1200,27038c7c-aa26-336f-82e2-91e75aea6bcc,167df25e-fbb0-6e2c-e8ad-1d8c3a7aaad2'/><Mutant id='32' tests='a44ffca8-a476-2ecb-ebb9-a905695d6beb,0c1026b7-a8f0-687f-e114-e087c33962e3,247613aa-be8f-8138-83b9-9abbeeb2ffe7,53b1693d-09e4-c041-d8fb-89177d230449'/><Mutant id='29' tests='e8d95ee2-c242-fee3-9db7-a895cd0877c6,67130f64-00c4-167c-c3cf-a32507828d1f,8479cdc1-ea3a-5d0e-8f93-753004fbe602,6587978b-e611-3526-00ca-7c67c9d42934,e6a73c78-a210-fa14-fd48-77669ab794e7'/><Mutant id='17' tests='f6aeb162-41d0-ce35-7c84-fd15a4f7b932,5be922bd-b82c-ce41-e41c-2d95a9a88451,d0ec8f50-7ab9-dc5f-c054-583b924ac4bc,0babd1b3-4c43-cdac-0fca-f7fb2743d82e,6631d8b1-5f55-7051-a6df-5351b2b16530,2b18d6a1-e59e-a8d2-4d03-000177f21970'/><MutantControl  name='StrykerODz7lWODKfow9f2.MutantControl'/></Parameters></Configuration></InProcDataCollector></InProcDataCollectors></InProcDataCollectionRunSettings>
</RunSettings>
[14:36:30 WRN] Runner 0: VsTest did not report the end of test session in due time, it may have hang. Retrying
[14:36:30 INF] Time Elapsed 00:06:14.3630344
Unhandled exception. System.AggregateException: One or more errors occurred. (*** Failed to create a TestRunner, Stryker cannot recover from this!***)
 ---> 
*** Failed to create a TestRunner, Stryker cannot recover from this!***


   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
Error: 30 VRB] Runner 0: [Error] Microsoft.VisualStudio.TestPlatform.ObjectModel.SettingsException: Invalid settings 'RunConfiguration'.  Invalid value '-169088' specified for 'TestSessionTimeout'.
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.TestPlatform.ObjectModel.RunConfiguration.FromXml(XmlReader reader)
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at Microsoft.VisualStudio.TestPlatform.ObjectModel.Utilities.XmlRunSettingsUtilities.GetNodeValue[T](String settingsXml, String nodeName, Func`2 nodeParser)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at Microsoft.VisualStudio.TestPlatform.ObjectModel.Utilities.XmlRunSettingsUtilities.GetRunConfigurationNode(String settingsXml)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 list, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at Microsoft.VisualStudio.TestPlatform.CommandLine.TestPlatformHelpers.TestRequestManager.UpdateRunSettingsIfRequired(String runsettingsXml, IList`1 sources, IBaseTestEventsRegistrar registrar, String& updatedRunSettingsXml)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at Microsoft.VisualStudio.TestPlatform.CommandLine.TestPlatformHelpers.TestRequestManager.RunTests(TestRunRequestPayload testRunRequestPayload, ITestHostLauncher testHostLauncher, ITestRunEventsRegistrar testRunEventsRegistrar, ProtocolConfig protocolConfig)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body)
   at Microsoft.VisualStudio.TestPlatform.Client.DesignMode.DesignModeClient.<>c__DisplayClass23_0.<StartTestRun>b__0()
   at Stryker.Core.MutationTest.MutationTestProcess.TestMutants(IEnumerable`1 mutantsToTest)
   at Stryker.Core.MutationTest.MutationTestProcess.Test(IEnumerable`1 mutantsToTest)
   at Stryker.Core.StrykerRunner.RunMutationTest(IStrykerInputs inputs, ILoggerFactory loggerFactory, IProjectOrchestrator projectOrchestrator)
   at Stryker.CLI.StrykerCli.RunStryker(IStrykerInputs inputs) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 93
   at Stryker.CLI.StrykerCli.<>c__DisplayClass10_0.<Run>b__0() in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 68
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass143_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Stryker.CLI.StrykerCli.Run(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 74
   at Stryker.CLI.Program.Main(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/Program.cs:line 14
Error: Process completed with exit code 134.
```

**Expected behavior**
`RunConfiguration.TestSessionTimeout` should not have negative value.

**Desktop:**
 - OS: Ubuntu
 -  .NET 6.0
 - Stryker Version 1.5.1

**Comment by rouke-broersma** [comment]
Interesting! Thank you for reporting!

**Comment by dupdob** [comment]
thanks for the reporting. Looking at the log I see that Stryker generates negative timeouts in both versions. In V1.5 it results in VsTest crashes (and invalid results). In V1.51 it results in Stryker crashes due to the new timeout safeguard features.

I analyzed it: the problem comes (unsurprisingly) from the test time out calculator. It computes the difference between the total test time duration with the sum of the duration of each tests as a way to estimate the (constant) init time of test sessions. With this project, there is a difference of 30 seconds, i.e. the sum of the duration of every test appears 30 seconds longer than the total test time. This leads to a huge negative init time...

Safeguarding against this should be easy, but I need the opportunity to figure out where this huge gap comes from.

**Comment by iamdmitrij** [comment]
Thank you for the workaround. I've increased default `additional-timeout` from `5000` to `60000` ms and it [works](https://github.com/iamdmitrij/Tethos/runs/6072224982?check_suite_focus=true) fine now. For some reason with `40000` it was still failing with negative timeout value.

```
{
  "stryker-config": {
    "additional-timeout": 60000
  }
}
```

Also, I've remembered that in the failing test project I would have long running tests with mutated code. Some of those tests would need at least couple of seconds before failing. In the non-mutated scenario those tests would run pretty quickly, but if underlying implementation changes, some of those tests would need larger timeout and perhaps `5000` is simply not enough.

**Comment by dupdob** [comment]
Thanks for the comment about your tests duration, but this not a problem of 'normal' vs 'mutated' duration. 
I am analyzing it, and it seems there is an issue in how xUnit reports the duration of some tests: in your project, there is a test (Tethos.Tests.Extensions.Assembly.AssemblyExtensionsTests.GetDependencies_ShouldLoad) that reports 12 results with a 3.8 seconds run each time, resulting in a total run time of 45 seconds, while the test session lasts around 40 seconds.
It seems that we should not aggregate the test times for this test, but I am trying to understand the logic behind xUnit reporting.

**Comment by dupdob** [comment]
Ok, I had to read the source code of xUnit to get a confirmation: xUnit returns the total run times for certain `Theories` (those whose data cannot be properly serialized at discovery time and thus are reported as a single test case).

So I will adjust the logic accordingly in Stryker
