### ISSUE TITLE
Unhandled Exception on Color or Style when in a filesystem containing a space

### ISSUE THREAD

**Issue by Christian-Oleson** [stryker-mutator/stryker-net#2009]
**Describe the bug**
Unhandled exception. System.InvalidOperationException: Could not find color or style:
This happens when there is a space in the name of the directory

**Logs**
 dotnet stryker -o

   _____ _              _               _   _ ______ _______  
  / ____| |            | |             | \ | |  ____|__   __| 
 | (___ | |_ _ __ _   _| | _____ _ __  |  \| | |__     | |    
  \___ \| __| '__| | | | |/ / _ \ '__| | . ` |  __|    | |    
  ____) | |_| |  | |_| |   <  __/ |    | |\  | |____   | |    
 |_____/ \__|_|   \__, |_|\_\___|_| (_)|_| \_|______|  |_|    
                   __/ |                                      
                  |___/                                       

Version: 1.5.2

[10:19:00 INF] Identifying project to mutate.
[10:19:02 INF] The project C:\Projects\myProject\My Project\Imports\Company..Project\Company..Project.csproj will be mutated.
[10:19:04 INF] Analysis complete.
[10:19:04 INF] Building test project C:\Projects\myProject\My Project\Tests\ImportTests\Company..Project.Tests\Company..Project.Tests.csproj (1/1)
[10:19:10 INF] Total number of tests found: 11.
[10:19:10 INF] Initial testrun started.
[10:19:16 WRN] Stryker.NET encountered an compile error in C:\Projects\myProject\My Project\Imports\Company..Project\Implementation\ProjectService.cs (at 118:22) with message: Use of unassigned local variable 'hasNextPage' (Source code: hasNextPage)
[10:19:16 WRN] Stryker.NET encountered an compile error in C:\Projects\myProject\My Project\Imports\Company..Project\Implementation\ProjectService.cs (at 150:22) with message: Use of unassigned local variable 'hasNextPage' (Source code: hasNextPage)
[10:19:16 INF] 339 mutants created
[10:19:16 INF] Capture mutant coverage using 'CoverageBasedTest' mode.
[10:19:19 INF] 8     mutants got status CompileError. Reason: Mutant caused compile errors
[10:19:19 INF] 105   mutants got status NoCoverage.   Reason: Mutant has no test coverage
[10:19:19 INF] 17    mutants got status Ignored.      Reason: Removed by exclude from code coverage filter
[10:19:19 INF] 130   total mutants are skipped for the above mentioned reasons
[10:19:19 INF] 209   total mutants will be tested
█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████100.00% │ Testing mutant 209 / 209 │ K 33 │ S 176 │ T 0 │ ~0m 00s │                                                                                                                                                                  00:03:08
Killed:    33
Survived: 176
Timeout:    0

Your html report has been generated at:
[10:22:28 INF] Time Elapsed 00:03:28.5192532
Unhandled exception. System.InvalidOperationException: Could not find color or style 'Project/Tests/ImportTests/Company..Project.Tests/StrykerOutput/2022-04-22.10-19-00/reports/mutation-report.html'.
   at Spectre.Console.StyleParser.Parse(String text) in /_/src/Spectre.Console/StyleParser.cs:line 10
   at Spectre.Console.MarkupParser.Parse(String text, Style style) in /_/src/Spectre.Console/Internal/Text/Markup/MarkupParser.cs:line 22
   at Spectre.Console.AnsiConsoleExtensions.Markup(IAnsiConsole console, String value) in /_/src/Spectre.Console/Extensions/AnsiConsoleExtensions.Markup.cs:line 77
   at Spectre.Console.AnsiConsoleExtensions.MarkupLine(IAnsiConsole console, String value) in /_/src/Spectre.Console/Extensions/AnsiConsoleExtensions.Markup.cs:line 117
   at Stryker.Core.Reporters.Html.reporter.HtmlReporter.OnAllMutantsTested(IReadOnlyProjectComponent reportComponent) in /_/src/Stryker.Core/Stryker.Core/Reporters/HtmlReporter/HtmlReporter.cs:line 57
   at Stryker.Core.Reporters.BroadcastReporter.OnAllMutantsTested(IReadOnlyProjectComponent reportComponent) in /_/src/Stryker.Core/Stryker.Core/Reporters/BroadcastReporter.cs:line 63
   at Stryker.Core.StrykerRunner.RunMutationTest(IStrykerInputs inputs, ILoggerFactory loggerFactory, IProjectOrchestrator projectOrchestrator) in /_/src/Stryker.Core/Stryker.Core/StrykerRunner.cs:line 111
   at Stryker.CLI.StrykerCli.RunStryker(IStrykerInputs inputs) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 93
   at Stryker.CLI.StrykerCli.<>c__DisplayClass10_0.<Run>b__0() in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 68
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass143_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Stryker.CLI.StrykerCli.Run(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 74
   at Stryker.CLI.Program.Main(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/Program.cs:line 14

**Expected behavior**
A space in the name of the directory should not cause issues

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Type of project: .NET Core 3.1 Console App
 - Framework Version: .NET Core 3.1
 - Stryker Version: 1.5.2

**Additional context**
N/a

**Comment by dupdob** [comment]
Thanks for reporting this. It seems this bug is without significant impact, except for the crash at the very end of the test session. The report must have been generated and can be used.
I just opened a PR for the fix, since it is a minor change, I assume it will be part of the next release.
