### ISSUE TITLE
Stryker throws an exception after initial test run

### ISSUE THREAD

**Issue by sobcvogl** [stryker-mutator/stryker-net#2016]
**Describe the bug**
If you run stryker it throws an exception after initial test run.
For Duplicated Tests using XUnit an Exception is Thrown.

```
Unhandled exception. System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Stryker.Core.TestRunners.VsTest.VsTestDescription.get_InitialRunTime() in /_/src/Stryker.Core/Stryker.Core/TestRunners/VsTest/VsTestDescription.cs:line 42
   at Stryker.Core.TestRunners.VsTest.VsTestRunner.<>c.<BuildTestRunResult>b__23_3(VsTestDescription t) in /_/src/Stryker.Core/Stryker.Core/TestRunners/VsTest/VsTestRunner.cs:line 212
   at System.Linq.Enumerable.Sum[TSource](IEnumerable`1 source, Func`2 selector)
   at Stryker.Core.TestRunners.VsTest.VsTestRunner.BuildTestRunResult(IRunResults testResults, Int32 expectedTests, Boolean compressAll) in /_/src/Stryker.Core/Stryker.Core/TestRunners/VsTest/VsTestRunner.cs:line 212
   at Stryker.Core.TestRunners.VsTest.VsTestRunner.InitialTest() in /_/src/Stryker.Core/Stryker.Core/TestRunners/VsTest/VsTestRunner.cs:line 99
   at Stryker.Core.TestRunners.VsTest.VsTestRunnerPool.InitialTest() in /_/src/Stryker.Core/Stryker.Core/TestRunners/VsTest/VsTestRunnerPool.cs:line 57
   at Stryker.Core.Initialisation.InitialTestProcess.InitialTest(StrykerOptions options, ITestRunner testRunner) in /_/src/Stryker.Core/Stryker.Core/Initialisation/InitialTestProcess.cs:line 44
   at Stryker.Core.Initialisation.InitialisationProcess.InitialTest(StrykerOptions options) in /_/src/Stryker.Core/Stryker.Core/Initialisation/InitialisationProcess.cs:line 101
   at Stryker.Core.Initialisation.ProjectMutator.MutateProject(StrykerOptions options, IReporter reporters) in /_/src/Stryker.Core/Stryker.Core/Initialisation/ProjectMutator.cs:line 39
   at Stryker.Core.Initialisation.ProjectOrchestrator.MutateProjects(StrykerOptions options, IReporter reporters)+MoveNext() in /_/src/Stryker.Core/Stryker.Core/Initialisation/ProjectOrchestrator.cs:line 61
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Stryker.Core.StrykerRunner.RunMutationTest(IStrykerInputs inputs, ILoggerFactory loggerFactory, IProjectOrchestrator projectOrchestrator) in /_/src/Stryker.Core/Stryker.Core/StrykerRunner.cs:line 58
   at Stryker.CLI.StrykerCli.RunStryker(IStrykerInputs inputs) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 93
   at Stryker.CLI.StrykerCli.<>c__DisplayClass10_0.<Run>b__0() in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 68
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass143_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Stryker.CLI.StrykerCli.Run(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 74
   at Stryker.CLI.Program.Main(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/Program.cs:line 14
```

**Logs**
Log files are attached

**Desktop (please complete the following information):**
 - OS: Windows 10, Windows Server 2019
 - Type of project .Net 6
 - Framework Version 6.0.201
 - Stryker Version 1.5.2

**Possible Solution**
I debugged stryker with our solution and recognized not every VsTestDescription has an entry in _initialResults.
So maybe a solution is to add an default value to avoid an exception.

**Stryker.Core.TestRunners.VsTest.VsTestDescription**
```csharp
if (Framework == TestFramework.xUnit)
{
      // xUnit returns the run time for the case within each result, so the first one is sufficient
      return _initialResults.FirstOrDefault()?.Duration ?? TimeSpan.Zero;
}
```

**Additional context**
Log Files: [logs.zip](https://github.com/stryker-mutator/stryker-net/files/8562885/logs.zip)

**Comment by dupdob** [comment]
Hi, thanks for reporting this. Feel free to open a PR with this fix. But this only happens if no test is detected in the test project, which is odd, to say the least. Actually, this is a sure sign that something else went wrong.
I also had a look at your logs and it appears this project often uses `ClassData` (or `MemberData`). I strongly suggest you turn off coverage analysis then, because there is no sure way to detect mutation coverage when you are using this kind of data sources for your theories.

**Comment by sobcvogl** [comment]
Hi, it seems the root cause of the Problem are duplicated Tests. We had several test cases with the same parameter, it seems XUnit detects these and does not execute the duplicate. After cleaning the identical tests the issue was resolved.

Also coverage analysis is already turned off in the config file.

**stryker-config.json**
```
{
  "stryker-config": {
    "mutation-level": "Complete",
    "reporters": ["html"],
    "thresholds": {
      "high": 100,
      "low": 100,
      "break": 100
    },
    "coverage-analysis": "off"
  }
}
```
