### ISSUE TITLE
Stryker cannot find tests on project

### ISSUE THREAD

**Issue by laurijssen** [stryker-mutator/stryker-net#2070]
Trying to get stryker to run on a VisualStudio 22 unit test project.

The unit test project uses .NET framework 4.8 with MSTest.TestFramework 2.2.10 The referenced project (engine) uses .NET framework 4.5.1

Then running

`dotnet stryker --test-project Engine.Tests/Engine.Tests.csproj -p Projects/Engine/Engine.csproj -s Engine.sln`

It looks like all is al right but then:

[14:16:28 INF] Analysis complete.  
[14:16:28 INF] Building test project Engine.Tests\Engine.Tests.csproj (1/1)  
[14:17:08 INF] Total number of tests found: Unable to detect

The tests can be started from Visual Studio so they absolutely exist.

Example test:

    [TestMethod]
    public void TestFMSShippingCostsInvalidDeliveryType()
    {
        var c = new ShippingCosts();

        Dealer dealer = new Dealer {
            SendByMail = false,
        };

        c.IsValidOrder(dealer, DateTime.Today).Should().BeFalse();
    }

What to do to get stryker to find these tests?

**Logs**

[14:16:28 INF] Building test project Engine.Tests\Engine.Tests.csproj (1/1)  
[14:17:08 INF] Total number of tests found: Unable to detect

**Expected behavior**

stryker finds tests

**Desktop (please complete the following information):**
 - OS windows 10
 - Type of project: unit test assembly dll
 - Framework Version 4.8, 4.5.1
 - Stryker Version latest

**Comment by psfinaki** [comment]
Is it possible to share the code? Maybe it's some open source stuff?

**Comment by laurijssen** [comment]
> Is it possible to share the code? Maybe it's some open source stuff?

What code? 

This test still produces   "Total number of tests found: Unable to detect"

        [TestMethod]
        public void TestX()
        {
            int x = 10;

            if (x == 9)
                Assert.Fail();
        }

**Comment by psfinaki** [comment]
Well the code of the project. Basically some repro. Something to debug :)

**Comment by dupdob** [comment]
just to be more specific: Stryker is expected to work on Net 4.8, and there is an integration test for this platform.
I just tried it and it runs fine. Hence this is likely there is something related to your project or your setup that triggers this problem. We need your help to identify this trigger(s) so we can fix underlying issue.

Can you use `--log-to-file` to get log files ? I suspect there is some VsTest internal error that is not reported there. One important fact you need to know is that Stryker relies on VsTest internally to run the tests, and it provides very limited information back, so it can fail silently, leading to this kind of error messages

**Comment by robertlyson** [comment]
Having same issue. Attaching logs from command `dotnet stryker --log-to-file` [logs.zip](https://github.com/stryker-mutator/stryker-net/files/9276623/logs.zip).
Thought that maybe it's related to .NET version of `NUnit` / `Microsoft.NET.Test.Sdk` so downgraded but it didn't help. Here is my current test project csproj

```
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netcoreapp3.1</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Library</OutputType>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="ApprovalTests" Version="5.7.3" />
      <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0" />
      <PackageReference Include="Microsoft.VisualStudio.TestPlatform" Version="14.0.0" />
      <PackageReference Include="NUnit" Version="3.0.1" />
      <PackageReference Include="Shouldly" Version="4.0.3" />
      <PackageReference Include="Spectre.Console" Version="0.44.0" />
      <PackageReference Include="Spectre.Console.Testing" Version="0.44.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\BattleshipGame\BattleshipGame.csproj" />
    </ItemGroup>

</Project>
```

Installed manually `Microsoft.VisualStudio.TestPlatform` nuget becasue I saw following in logs
```
File name: 'Microsoft.VisualStudio.TestPlatform.Fakes, Version=17.0.0.0, Culture=neutral'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.VisualStudio.TestPlatform.Common.Utilities.FakesUtilities.LoadTestPlatformAssembly()
```
but that didn't help.

**Comment by rouke-broersma** [comment]
@robertlyson are you using Microsoft.Fakes? I think we have an open issue about support for Fakes.

**Comment by robertlyson** [comment]
No, I'm not using Microsoft.Fakes. Here is my sample project having above issue https://github.com/robertlyson/Battleship.

**Comment by robertlyson** [comment]
When I check `C:\Users\Rob\RiderProjects\Battleship\BattleshipTests\StrykerOutput\2022-08-07.13-34-05\logs\Runner 1_VsTest-log.host.22-08-07_13-34-18_81649_7.txt` mentioned in this log line

```
2022-08-07T13:34:19.1206678+02:00  [VRB] Runner 1: [Warning] Could not find extensions: C:\Users\Rob\RiderProjects\Battleship\BattleshipTests\bin\Debug\net6.0 (b2a49870)
2022-08-07T13:34:19.1261423+02:00  [VRB] Runner 1: [Debug] Logging TestHost Diagnostics in file: C:\Users\Rob\RiderProjects\Battleship\BattleshipTests\StrykerOutput\2022-08-07.13-34-05\logs\Runner 1_VsTest-log.host.22-08-07_13-34-18_81649_7.txt (f929d3c8)
2022-08-07T13:34:19.2689026+02:00  [VRB] Runner 1: [Warning] No test is available in C:\Users\Rob\RiderProjects\Battleship\BattleshipTests\bin\Debug\net6.0\BattleshipTests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again. (f0192d1a)
2022-08-07T13:34:19.3875299+02:00  [VRB] Runner 1: Test session reports 0 result and 0 stuck tests. (073f8ee8)
```

I see something like
```
TpTrace Warning: 0 : 36908, 4, 2022/08/07, 13:34:19.195, 2717721607830, testhost.dll, TestPluginDiscoverer: Failed to load extensions from file 'Microsoft.VisualStudio.TestTools.CppUnitTestFramework.CppUnitTestExtension.dll'.  Skipping test extension scan for this file.  Error: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.TestTools.CppUnitTestFramework.CppUnitTestExtension, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'Microsoft.VisualStudio.TestTools.CppUnitTestFramework.CppUnitTestExtension, Culture=neutral, PublicKeyToken=null'
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.TestTools.CppUnitTestFramework.CppUnitTestExtension, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'Microsoft.VisualStudio.TestTools.CppUnitTestFramework.CppUnitTestExtension, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.InternalLoad(ObjectHandleOnStack assemblyName, ObjectHandleOnStack requestingAssembly, StackCrawlMarkHandle stackMark, Boolean throwOnFileNotFound, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack retAssembly)
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, RuntimeAssembly requestingAssembly, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.TestPluginCache.CurrentDomainAssemblyResolve(Object sender, AssemblyResolveEventArgs args)
   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.PlatformAssemblyResolver.AssemblyResolverEvent(Object sender, Object eventArgs)
   at System.Runtime.Loader.AssemblyLoadContext.GetFirstResolvedAssemblyFromResolvingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at System.Reflection.RuntimeAssembly.InternalLoad(ObjectHandleOnStack assemblyName, ObjectHandleOnStack requestingAssembly, StackCrawlMarkHandle stackMark, Boolean throwOnFileNotFound, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack retAssembly)
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, RuntimeAssembly requestingAssembly, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.VisualStudio.TestPlatform.Common.ExtensionFramework.TestPluginDiscoverer.GetTestExtensionsFromFiles[TPluginInfo,TExtension](String[] files, Dictionary`2 pluginInfos)
```

**Comment by rouke-broersma** [comment]
I don't know, sounds like an actual problem in vstest. Those loading warnings are not a problem AFAIK.

**Comment by dupdob** [comment]
@robertlyson : thanks for providing details and the project. It helped me analyzed your problem. This is a problem with your project, not Stryker. You need to add NUnit's VsTest adapter (`NUnit3TestAdapter.dll`) to the test project; this is mandatory for the tests to be visible to the .Net infrastructure (`dotnet test` and/or `vstest`). 

I just ran your project with the adapter added to the dependencies and then Stryker run properly, with 198 mutants generated and 27 survivors at the end!

@laurijssen: this may be the cause for your problems too: could you make sure you have `MsTest.TestAdapter` as part of your (test) project's dependencies?
Alternatively, can you check if you can run the test from Visual Studio and/or via the `dotnet test` command ?

And please report your results 😄 .

**Comment by robertlyson** [comment]
@dupdob thanks for the help :) Do you think it's worth mentioning this in docs? Happy to do PR for it.

**Comment by laurijssen** [comment]
I dont know what happened but it works suddenly.

11:38:08 INF] Identifying project to mutate.
[11:38:11 INF] The project Engine.csproj will be mutated.
[11:38:14 INF] Analysis complete.
[11:38:14 INF] Building test project Engine.Tests.csproj (1/1)
[11:39:39 INF] Total number of tests found: 19.
[11:39:39 INF] Initial testrun started.

**Comment by dupdob** [comment]
@laurijssen: well, if you did not update anything, we will probably never understand why.
@robertlyson: thanks for the proposal, I think this should appear as some pre-requisite. Along the lines of : the project's test base can be tested via `dotnet test`.  But I would like to get a second opinion here: @rouke-broersma what is the best way to document this ?

BTW I am working on a PR with an automatic diagnosis feature to report this automatically.

**Comment by rouke-broersma** [comment]
We already test thatbthe test project is not mstest v1 (which we cannot support), we could easily test if the test project references do not contain a test adapter and error.

**Comment by dupdob** [comment]
I opened #2126 to discuss how to work on this.
