### ISSUE TITLE
Open file fails when file path contains a space

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/stryker-net#2246]
**Describe the bug**
When passing -o to open the html report it fails when the path contains a space (`%20`).

```
Unhandled exception. System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'file://c/:/Info%20Support/Minor%202022/CursusAdmin.Website/CursusAdmin.Website.Test/StrykerOutput/2022-10-17.14-02-25/reports/mutation-report.html' with working directory 'C:\Info Support\Minor 2022\CursusAdmin.Website\CursusAdmin.Website.Test'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Stryker.Core.Reporters.HtmlReporter.ProcessWrapper.WebbrowserOpener.Open(String path) in /_/src/Stryker.Core/Stryker.Core/Reporters/HtmlReporter/ProcessWrapper/WebbrowserOpener.cs:line 17
   at Stryker.Core.Reporters.Html.reporter.HtmlReporter.OnAllMutantsTested(IReadOnlyProjectComponent reportComponent) in /_/src/Stryker.Core/Stryker.Core/Reporters/HtmlReporter/HtmlReporter.cs:line 44
   at Stryker.Core.Reporters.BroadcastReporter.OnAllMutantsTested(IReadOnlyProjectComponent reportComponent) in /_/src/Stryker.Core/Stryker.Core/Reporters/BroadcastReporter.cs:line 63
   at Stryker.Core.StrykerRunner.RunMutationTest(IStrykerInputs inputs, ILoggerFactory loggerFactory, IProjectOrchestrator projectOrchestrator) in /_/src/Stryker.Core/Stryker.Core/StrykerRunner.cs:line 111
   at Stryker.CLI.StrykerCli.RunStryker(IStrykerInputs inputs) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 93
   at Stryker.CLI.StrykerCli.<>c__DisplayClass10_0.<Run>b__0() in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 68
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass143_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Stryker.CLI.StrykerCli.Run(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 74
   at Stryker.CLI.Program.Main(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/Program.cs:line 14
```

**Expected behavior**
I expect the file to open in the browser.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Type of project: core
 - Framework Version net 6
 - Stryker Version 3.0.1

**Comment by richardwerkman** [comment]
I'm suspecting the issue is on line: https://github.com/stryker-mutator/stryker-net/blob/f98a2e8c6362bf2d435ca33706b06e233751e7b4/src/Stryker.Core/Stryker.Core/Reporters/HtmlReporter/HtmlReporter.cs#L40
Where we replace ` ` with `%20`. I think we don't need it but this should be tested

**Comment by rouke-broersma** [comment]
Uris with spaces are invalid, but perhaps command execution with spaces is also invalid. We might simply need to use the escaped variant for printing to console and the unescaped for auto opening.
