### ISSUE TITLE
Stryker crashes on console reporter trying to access console to change output even though no console is available in environment

### ISSUE THREAD

**Issue by Mobrockers** [stryker-mutator/stryker-net#228]
Integration test crashes on windows build agent due to trying to access a console, but no console being available in the azure pipeline.

See: https://stackoverflow.com/questions/327408/the-handle-is-invalid-when-running-net-console-via-java

We should detect in some way whether or not an interactive console is available and if not, skip this reporting functionality. This would fail in every build pipeline.

```
2018-11-05T03:34:11.9839759Z System.IO.IOException: The handle is invalid
2018-11-05T03:34:11.9840012Z    at System.ConsolePal.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
2018-11-05T03:34:11.9840728Z    at System.Console.get_CursorTop()
2018-11-05T03:34:11.9841461Z    at Stryker.Core.Reporters.Progress.ConsoleOneLineLogger.StartLog(String text, Object[] args) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Reporters\Progress\ConsoleOneLineLogger.cs:line 25
2018-11-05T03:34:11.9841815Z    at Stryker.Core.Reporters.Progress.ProgressBarReporter.ReportInitialState(Int32 totalNumberOfTests) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Reporters\Progress\ProgressBarReporter.cs:line 49
2018-11-05T03:34:11.9842155Z    at Stryker.Core.Reporters.Progress.ProgressReporter.OnStartMutantTestRun(IEnumerable`1 mutantsToBeTested) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Reporters\Progress\ProgressReporter.cs:line 30
2018-11-05T03:34:11.9842504Z    at Stryker.Core.Reporters.BroadcastReporter.OnStartMutantTestRun(IEnumerable`1 mutantsToBeTested) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Reporters\BroadcastReporter.cs:line 33
2018-11-05T03:34:11.9842797Z    at Stryker.Core.MutationTest.MutationTestProcess.Test(StrykerOptions options) in D:\a\1\s\src\Stryker.Core\Stryker.Core\MutationTest\MutationTestProcess.cs:line 119
2018-11-05T03:34:11.9843104Z    at Stryker.Core.StrykerRunner.RunMutationTest(StrykerOptions options) in D:\a\1\s\src\Stryker.Core\Stryker.Core\StrykerRunner.cs:line 77
2018-11-05T03:34:11.9896043Z [03:34:11 INF] Time Elapsed 00:30:21.6977504
```

**Comment by Mobrockers** [comment]
Specifially the following method causes the regression:

`https://github.com/stryker-mutator/stryker-net/blob/5178ed63ff0990ac0820244d5e686bdd8e74c805/src/Stryker.Core/Stryker.Core/Reporters/Progress/ConsoleOneLineLogger.cs#L29-L41`
