### ISSUE TITLE
LangVersion 11 not supported in options

### ISSUE THREAD

**Issue by Kuinox** [stryker-mutator/stryker-net#2316]
**Describe the bug**
```json
{
  "stryker-config":
  {
      "reporters": [
          "progress",
          "html"
      ],
      "project": "Draco.Compiler.csproj",
      "test-projects":[
        "src/Draco.Compiler.Tests/Draco.Compiler.Tests.csproj"
      ],
      "language-version": "11"
  }
}

```

**Logs**
```
Unhandled exception. System.InvalidOperationException: Unexpected value '11' of type 'Microsoft.CodeAnalysis.CSharp.LanguageVersion'
   at Microsoft.CodeAnalysis.CSharp.LanguageVersionExtensionsInternal.GetErrorCode(LanguageVersion version)
   at Microsoft.CodeAnalysis.CSharp.MessageIDExtensions.GetDisabledFeatureDiagnosticInfo(MessageID feature, LanguageVersion availableVersion)
   at Microsoft.CodeAnalysis.CSharp.MessageIDExtensions.GetFeatureAvailabilityDiagnosticInfo(MessageID feature, CSharpParseOptions options)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxParser.CheckFeatureAvailability[TNode](TNode node, MessageID feature, Boolean forceWarning)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseSwitchExpression(ExpressionSyntax governingExpression, SyntaxToken switchKeyword)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseExpressionContinued(ExpressionSyntax leftOperand, Precedence precedence)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseSubExpressionCore(Precedence precedence)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseSubExpression(Precedence precedence)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseExpressionCore()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseVariableInitializer()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseVariableDeclarator(TypeSyntax parentType, VariableFlags flags, Boolean isFirst, Boolean allowLocalFunctions, SyntaxList`1 attributes, SyntaxList`1 mods, LocalFunctionStatementSyntax& localFunction, Boolean isExpressionContext)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseVariableDeclarators(TypeSyntax type, VariableFlags flags, SeparatedSyntaxListBuilder`1 variables, Boolean variableDeclarationsExpected, Boolean allowLocalFunctions, SyntaxList`1 attributes, SyntaxList`1 mods, LocalFunctionStatementSyntax& localFunction)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseLocalDeclaration(SeparatedSyntaxListBuilder`1 variables, Boolean allowLocalFunctions, SyntaxList`1 attributes, SyntaxList`1 mods, TypeSyntax& type, LocalFunctionStatementSyntax& localFunction)        
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseLocalDeclarationStatement(SyntaxList`1 attributes)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseStatementCoreRest(SyntaxList`1 attributes, Boolean isGlobal, ResetPoint& resetPointBeforeStatement)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseStatementCore(SyntaxList`1 attributes, Boolean isGlobal)     
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseStatements(CSharpSyntaxNode& previousNode, SyntaxListBuilder`1 statements, Boolean stopOnSwitchSections)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseMethodOrAccessorBodyBlock(SyntaxList`1 attributes, Boolean isAccessorBody)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseBlockAndExpressionBodiesWithSemicolon(BlockSyntax& blockBody, ArrowExpressionClauseSyntax& expressionBody, SyntaxToken& semicolon, Boolean parseSemicolonAfterBlock, MessageID requestedExpressionBodyFeature)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseMethodDeclaration(SyntaxList`1 attributes, SyntaxListBuilder modifiers, TypeSyntax type, ExplicitInterfaceSpecifierSyntax explicitInterfaceOpt, SyntaxToken identifier, TypeParameterListSyntax typeParameterList)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseMemberDeclarationCore(SyntaxKind parentKind)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseClassOrStructOrInterfaceDeclaration(SyntaxList`1 attributes, SyntaxListBuilder modifiers)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseTypeDeclaration(SyntaxList`1 attributes, SyntaxListBuilder modifiers)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseMemberDeclarationCore(SyntaxKind parentKind)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseNamespaceBody(SyntaxToken& openBraceOrSemicolon, NamespaceBodyBuilder& body, SyntaxListBuilder& initialBadNodes, SyntaxKind parentKind)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseNamespaceDeclarationCore(SyntaxList`1 attributeLists, SyntaxListBuilder modifiers)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseNamespaceBody(SyntaxToken& openBraceOrSemicolon, NamespaceBodyBuilder& body, SyntaxListBuilder& initialBadNodes, SyntaxKind parentKind)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseCompilationUnitCore()
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseWithStackGuard[TNode](Func`1 parseFunc, Func`1 createEmptyNodeFunc)
   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseCompilationUnit()
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.ParseText(SourceText text, CSharpParseOptions options, String path, ImmutableDictionary`2 diagnosticOptions, Nullable`1 isGeneratedCode, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.ParseText(String text, CSharpParseOptions options, String path, Encoding encoding, ImmutableDictionary`2 diagnosticOptions, Nullable`1 isGeneratedCode, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.ParseText(String text, CSharpParseOptions options, String path, Encoding encoding, ImmutableDictionary`2 diagnosticOptions, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.ParseText(String text, CSharpParseOptions options, String path, Encoding encoding, CancellationToken cancellationToken)
 in /_/src/Stryker.Core/Stryker.Core/Initialisation/ProjectMutator.cs:line 32   at Stryker.Core.Initialisation.ProjectOrchestrator.MutateProjects(StrykerOptions options, IReporter reporters)+MoveNext() in /_/src/Stryker.Core/Stryker.Core/Initialisation/ProjectOrchestrator.cs:line 71   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)   at Stryker.Core.StrykerRunner.RunMutationTest(IStrykerInputs inputs, ILoggerFactory loggerFactory, IProjectOrchestrator projectOrchestrator) in /_/src/Stryker.Core/Stryker.Core/StrykerRunner.cs:line 58   at Stryker.CLI.StrykerCli.RunStryker(IStrykerInputs inputs) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 93
   at Stryker.CLI.StrykerCli.<>c__DisplayClass10_0.<Run>b__0() in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 68   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass143_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Stryker.CLI.StrykerCli.Run(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 74
   at Stryker.CLI.Program.Main(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/Program.cs:line 14
```

**Expected behavior**
It works :D

**Desktop (please complete the following information):**
 - OS: Windows
 - Type of project core
 - Framework Version .NET 7
 - Stryker Version 3.1.0

**Additional context**

**Comment by rouke-broersma** [comment]
Roslyn support for csharp11 has not yet been released for some reason, so we cannot support language version 11. You can use language version preview instead. See: https://github.com/dotnet/roslyn/blob/main/docs/wiki/NuGet-packages.md

I expected that we should handle incorrect versions more gracefully though.

**Comment by richardwerkman** [comment]
Should work now :)
