### ISSUE TITLE
Occasional failures when creating test runners

### ISSUE THREAD

**Issue by psfinaki** [stryker-mutator/stryker-net#2353]
**Describe the bug**
You get the point - it's one of those sporadic non-reproducible bugs :D But yeah we are running Stryker on 150+ projects in our nightlies and I noticed this error happens every now and then for quite random projects.

```
Unhandled exception. System.AggregateException: One or more errors occurred. (*** Failed to create a TestRunner, Stryker cannot recover from this! ***) (*** Failed to create a TestRunner, Stryker cannot recover from this! ***)
 --->

*** Failed to create a TestRunner, Stryker cannot recover from this! ***


   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 list, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body)
   at Stryker.Core.MutationTest.MutationTestProcess.TestMutants(IEnumerable`1 mutantsToTest) in /_/src/Stryker.Core/Stryker.Core/MutationTest/MutationTestProcess.cs:line 115
   at Stryker.Core.MutationTest.MutationTestProcess.Test(IEnumerable`1 mutantsToTest) in /_/src/Stryker.Core/Stryker.Core/MutationTest/MutationTestProcess.cs:line 101
   at Stryker.Core.StrykerRunner.RunMutationTest(IStrykerInputs inputs, ILoggerFactory loggerFactory, IProjectOrchestrator projectOrchestrator) in /_/src/Stryker.Core/Stryker.Core/StrykerRunner.cs:line 107
   at Stryker.CLI.StrykerCli.RunStryker(IStrykerInputs inputs) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 93
   at Stryker.CLI.StrykerCli.<>c__DisplayClass10_0.<Run>b__0() in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 68
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass143_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Stryker.CLI.StrykerCli.Run(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 74
   at Stryker.CLI.Program.Main(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/Program.cs:line 14
 ---> (Inner Exception #1)

*** Failed to create a TestRunner, Stryker cannot recover from this! ***
<---
```
**Logs**
Here are some partially redacted logs, hope this helps. I was able to get this locally when running the same Stryker command for N times.
[log-20221212.txt](https://github.com/stryker-mutator/stryker-net/files/10207590/log-20221212.txt)

**Expected behavior**
Successful execution.

**Desktop (please complete the following information):**
 - OS: Windows
 - Type of project: .NET Core
 - Framework Version: 7.0
 - Stryker Version: 3.3.0

**Additional context**
Feels like some concurrency issue. Maybe worth looking at the stack trace and analyzing where some deadlocks can happen or something along those lines.

**Comment by dupdob** [comment]
had the opportunity to look at your log. I suspect VsTest sessions crash early or (most likely) do not start at all. Could you have a look and/or share here the `Runner xVsTest-log.txt` files ? Those files traces VsTest client events and they may give a hint of what the problem was.
This is probably because Stryker generated a configuration file VsTest was unable to process.

Alas, VsTest client API does not provide us with a status when Stryker tries to launch a VsTest session.
In the past, this problem was due to negative timeout computation, but this does not seem to be the case, judging by the master log file.

**Comment by psfinaki** [comment]
Thanks for taking a look. Yep, I will catch the error again and bring more logs hopefully :)

**Comment by JoHeinrich** [comment]
I get this error quite a lot.
For me adding .Wait() to RunTestsWithCustomTestHostAsync solved the problem.
Please take a closer look at why the async function is used and if this can use proper async or if not maybe go back to the sync version

**Comment by dupdob** [comment]
We switched to the `...Async` methods to detect and deal with situation when VsTest got stuck (infinite wait on the sync call). Using `await` keyword would lead back to this.

There is actually an indirect wait logic, (see https://github.com/stryker-mutator/stryker-net/blob/057a4dcd70ee9ea2b9d8d5805e0a35d393ef80cf/src/Stryker.Core/Stryker.Core/TestRunners/VsTest/VsTestRunner.cs#LL213C39-L213C46).
There is an improved version in PR #2400.
@JoHeinrich : could you share some log files about this ? There is no visible reason why adding `Wait()` would solve this kind of issue?
