### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by princevince** [stryker-mutator/stryker-net#2415]
** Just the error and it's stack trace should be enough **

```
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Stryker.Core.Compiling.RollbackProcess.Start(CSharpCompilation compiler, ImmutableArray`1 diagnostics, Boolean lastAttempt, Boolean devMode) in /_/src/Stryker.Core/Stryker.Core/Compiling/RollbackProcess.cs:line 43
   at Stryker.Core.Compiling.CsharpCompilingProcess.TryCompilation(Stream ms, Stream symbolStream, CSharpCompilation compilation, EmitResult previousEmitResult, Boolean lastAttempt, Int32 retryCount) in /_/src/Stryker.Core/Stryker.Core/Compiling/CsharpCompilingProcess.cs:line 135
   at Stryker.Core.Compiling.CsharpCompilingProcess.Compile(IEnumerable`1 syntaxTrees, Stream ilStream, Stream symbolStream) in /_/src/Stryker.Core/Stryker.Core/Compiling/CsharpCompilingProcess.cs:line 83
   at Stryker.Core.MutationTest.CsharpMutationProcess.CompileMutations() in /_/src/Stryker.Core/Stryker.Core/MutationTest/CsharpMutationProcess.cs:line 89
   at Stryker.Core.MutationTest.CsharpMutationProcess.Mutate() in /_/src/Stryker.Core/Stryker.Core/MutationTest/CsharpMutationProcess.cs:line 81
   at Stryker.Core.MutationTest.MutationTestProcess.Mutate() in /_/src/Stryker.Core/Stryker.Core/MutationTest/MutationTestProcess.cs:line 89
   at Stryker.Core.Initialisation.ProjectMutator.MutateProject(StrykerOptions options, IReporter reporters, IEnumerable`1 solutionProjects) in /_/src/Stryker.Core/Stryker.Core/Initialisation/ProjectMutator.cs:line 41
   at Stryker.Core.Initialisation.ProjectOrchestrator.MutateProjects(StrykerOptions options, IReporter reporters)+MoveNext() in /_/src/Stryker.Core/Stryker.Core/Initialisation/ProjectOrchestrator.cs:line 71
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Stryker.Core.StrykerRunner.RunMutationTest(IStrykerInputs inputs, ILoggerFactory loggerFactory, IProjectOrchestrator projectOrchestrator) in /_/src/Stryker.Core/Stryker.Core/StrykerRunner.cs:line 58
   at Stryker.CLI.StrykerCli.RunStryker(IStrykerInputs inputs) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 93
   at Stryker.CLI.StrykerCli.<>c__DisplayClass10_0.<Run>b__0() in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 68
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass143_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Stryker.CLI.StrykerCli.Run(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 74
   at Stryker.CLI.Program.Main(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/Program.cs:line 14
```

**Comment by dupdob** [comment]
I am afraid they are not. Of course the code to be changed not to raise an exception at this point, but the exception signals an unsupported situation for the code. 
Here, it signals that we have a compilation error that is not related to any source code whatsoever. 
At this stage, the best we can do is report the error and stop the mutation, as we do not know how to fix this.

Any chance you could share the project triggering this or a smaller project reproducing the issue?

**Comment by princevince** [comment]
I'm not allowed to upload code. So I'm afraid I cannot help you with that. What I did was running it again with the flag `--verbosity debug` and these are the last errors that occurred before the crash:

`[09:30:34 DBG] Found mutant 10170 of type 'Block' controlled by 'IfInstrumentationEngine'.
[09:30:34 DBG] Found mutant 10166 of type 'Block' controlled by 'IfInstrumentationEngine'.
[09:30:34 DBG] Found mutant -1 of type 'null' controlled by 'EndingReturnEngine'.
[09:30:34 DBG] Found mutant 10172 of type 'String' controlled by 'ConditionalInstrumentationEngine'.
[09:30:34 DBG] Found mutant 10171 of type 'Block' controlled by 'IfInstrumentationEngine'.
[09:30:34 DBG] Found mutant -1 of type 'null' controlled by 'EndingReturnEngine'.
[09:30:34 DBG] Found mutant 10174 of type 'String' controlled by 'ConditionalInstrumentationEngine'.
[09:30:34 DBG] Found mutant 10175 of type 'String' controlled by 'ConditionalInstrumentationEngine'.
[09:30:34 DBG] Found mutant 10173 of type 'Block' controlled by 'IfInstrumentationEngine'.
[09:30:34 DBG] Found mutant -1 of type 'null' controlled by 'EndingReturnEngine'.
[09:30:34 DBG] Trying compilation for the 13th time.
[09:30:42 DBG] Compilation failed
[09:30:42 DBG] Error reading resource '<ProjectName>.resources' -- 'ResX file Could not load file or assembly 'System.Windows.Forms, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified. Line 123, position 5. cannot be parsed.', Unknown filepath
[09:30:42 INF] Time Elapsed 00:03:37.9076776
`

Is this of any help? What else can I do?

**Comment by rouke-broersma** [comment]
Looks like it's failing to generate the code behind for your a resx file.

**Comment by princevince** [comment]
I've drilled it down to a resource file which has a file reference like this:

```xml
<data name="MyTemplate" type="System.Resources.ResXFileRef, System.Windows.Forms">
    <value>..\Resources\MyTemplate.en.txt;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;Windows-1252</value>
</data>
```
The compiling process is not resolving the referenced files. Not even after marking it as an embedded resource. The project itself is a .NET Standard 2.0 project.

**Comment by causa-prima** [comment]
I encounter the same problem with the same stack trace and error output.

I'm not sure whether in both our cases the .resx is referenced alike, as if I remove the file in Visual Studio, the only other thing that changes is the .sln, where the following part is deleted:

```xml
<Compile Include="Resources\MyRessourcesFile.Designer.cs">
  <AutoGen>True</AutoGen>
  <DesignTime>True</DesignTime>
  <DependentUpon>MyRessourcesFile.resx</DependentUpon>
</Compile>
```

The only other difference is that my project is a .NET Framework 4.8 project, so to me, it seems like that doesn't matter.

**Comment by causa-prima** [comment]
I downgraded to 3.4, which works - @princevince, can you confirm that?

As 
- I just installed Stryker for the first time on this machine,
- this topic is very recent, and
- I couldn't find any earlier occurrences of this problem,

I suspected that former versions didn't have that problem. Seems like I'm right, which might make it easier to find the cause.

**Comment by rouke-broersma** [comment]
Yes this issue was recently introduced, I think I'll reintroduce the previous method of resolving the embedded resources and also keep the new implementation since the previous method seems to work fine for a lot more people than I thought.

**Comment by causa-prima** [comment]
I can confirm it's fixed in 3.7.1. Thanks for the quick response!
