### ISSUE TITLE
Stryker.NET : Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'path2')

### ISSUE THREAD

**Issue by Nagendra-Davala** [stryker-mutator/stryker-net#2450]
at System.IO.Path.Combine(String path1, String path2)
   at Stryker.Core.Initialisation.Buildalyzer.IAnalyzerResultExtensions.GetAssemblyOriginatorKeyFile(IAnalyzerResult analyzerResult) in /_/src/Stryker.Core/Stryker.Core/Initialisation/Buildalyzer/IAnalyzerResultExtensions.cs:line 155
   at Stryker.Core.Initialisation.Buildalyzer.IAnalyzerResultExtensions.GetCompilationOptions(IAnalyzerResult analyzerResult) in /_/src/Stryker.Core/Stryker.Core/Initialisation/Buildalyzer/IAnalyzerResultExtensions.cs:line 48
   at Stryker.Core.Compiling.CsharpCompilingProcess.Compile(IEnumerable`1 syntaxTrees, Stream ilStream, Stream symbolStream) in /_/src/Stryker.Core/Stryker.Core/Compiling/CsharpCompilingProcess.cs:line 58
   at Stryker.Core.MutationTest.CsharpMutationProcess.CompileMutations() in /_/src/Stryker.Core/Stryker.Core/MutationTest/CsharpMutationProcess.cs:line 89
   at Stryker.Core.MutationTest.CsharpMutationProcess.Mutate() in /_/src/Stryker.Core/Stryker.Core/MutationTest/CsharpMutationProcess.cs:line 81
   at Stryker.Core.MutationTest.MutationTestProcess.Mutate() in /_/src/Stryker.Core/Stryker.Core/MutationTest/MutationTestProcess.cs:line 89
   at Stryker.Core.Initialisation.ProjectMutator.MutateProject(StrykerOptions options, IReporter reporters, IEnumerable`1 solutionProjects) in /_/src/Stryker.Core/Stryker.Core/Initialisation/ProjectMutator.cs:line 41
   at Stryker.Core.Initialisation.ProjectOrchestrator.MutateSolution(StrykerOptions options, IReporter reporters, IEnumerable`1 projectsUnderTest, IEnumerable`1 testProjects, IEnumerable`1 solutionProjects)+MoveNext() in /_/src/Stryker.Core/Stryker.Core/Initialisation/ProjectOrchestrator.cs:line 102
   at Stryker.Core.Initialisation.ProjectOrchestrator.MutateProjects(StrykerOptions options, IReporter reporters)+MoveNext() in /_/src/Stryker.Core/Stryker.Core/Initialisation/ProjectOrchestrator.cs:line 62
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Stryker.Core.StrykerRunner.RunMutationTest(IStrykerInputs inputs, ILoggerFactory loggerFactory, IProjectOrchestrator projectOrchestrator) in /_/src/Stryker.Core/Stryker.Core/StrykerRunner.cs:line 58
   at Stryker.CLI.StrykerCli.RunStryker(IStrykerInputs inputs) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 93
   at Stryker.CLI.StrykerCli.<>c__DisplayClass10_0.<Run>b__0() in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 68
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass143_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Stryker.CLI.StrykerCli.Run(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 74
   at Stryker.CLI.Program.Main(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/Program.cs:line 14

**Comment by rouke-broersma** [comment]
Sounds like sign your binaries but your keyfile is missing/cannot be found by stryker during compilation

**Comment by dupdob** [comment]
Looking at the code, it is not a missing file, it looks more like Buildalyzer returning a `null` project path (unlikely) or a project marked as signed without any signature keyfile defined (property "AssemblyOriginatorKeyFile")

**Comment by dupdob** [comment]
Update:

1. Missing signing key file results in compilation exception. There is a unit test for that
2. you can request assembly signing without providing a key: this results in a build without any warning but without any signature either (of course).

So I stand by my suggestion 😄
