### ISSUE TITLE
Stryker fails when original dll is not found

### ISSUE THREAD

**Issue by richardwerkman** [stryker-mutator/stryker-net#2456]
**Describe the bug**
Stryker fails with an exception when the .dll.stryker-unchanged file cannot be found.

**Logs**
```
Unhandled exception. System.IO.FileNotFoundException: Could not find file '/home/vsts/work/1/s/integrationtest/TargetProjects/NetCoreTestProject.XUnit/bin/Debug/net6/ExtraProject.dll.stryker-unchanged'.
File name: '/home/vsts/work/1/s/integrationtest/TargetProjects/NetCoreTestProject.XUnit/bin/Debug/net6/ExtraProject.dll.stryker-unchanged'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at System.IO.Abstractions.FileWrapper.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Stryker.Core.ProjectComponents.TestProjects.TestProjectsInfo.RestoreOriginalAssembly(IAnalyzerResult targetProject)
   at Stryker.Core.MutationTest.MutationTestProcess.Restore()
   at Stryker.Core.StrykerRunner.RunMutationTest(IStrykerInputs inputs, ILoggerFactory loggerFactory, IProjectOrchestrator projectOrchestrator)
   at Stryker.CLI.StrykerCli.RunStryker(IStrykerInputs inputs) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 93
   at Stryker.CLI.StrykerCli.<>c__DisplayClass10_0.<Run>b__0() in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 68
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass143_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Stryker.CLI.StrykerCli.Run(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 74
   at Stryker.CLI.Program.Main(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/Program.cs:line 14
```

**Expected behavior**
I expect stryker to still succeed but with a warning.

**Comment by dupdob** [comment]
Failing to restore the original assembly is not a problem per se, but it should not happen either: failure to back it up should throw an exception. Failing to overwrite the mutated assembly may happen because it is still open by some stuck process, but failing to find our backup is worrying.

Of course, ignoring this does not impair the results. And we can assume a log entry will suffice

can you reproduce this scenario?

**Comment by richardwerkman** [comment]
Start stryker, remove `stryker-unchanged` file manually. You'll see this error when stryker is done.

I'd be better to just show a warning and still report the results

**Comment by richardwerkman** [comment]
Ah, naturally this should not happen. It happened now in a PR, but it was because of a bug. 

I created this issue because I can imagine someone deletes the file as they don't know what it does and it will ruin their run they have been waiting for a long time on.

**Comment by dupdob** [comment]
fair enough
I add this fix in my PR, as I don't see this as urgent 😄

**Comment by richardwerkman** [comment]
This seems fixed now
