### ISSUE TITLE
Browser auto-open does not work in wsl

### ISSUE THREAD

**Issue by rouke-broersma** [stryker-mutator/stryker-net#2471]
**Describe the bug**
When running stryker in WSL with the auto-open report option enabled stryker exits with an unmanaged exception.

**Logs**
```
Unhandled exception. System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'file:///home/mobrockers/git/stryker/stryker-net/integrationtest/TargetProjects/NetCoreTestProject.XUnit/StrykerOutput/2023-04-14.11-12-32/reports/mutation-report.html' with working directory '/home/mobrockers/git/stryker/stryker-net/integrationtest/TargetProjects/NetCoreTestProject.XUnit'. No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Stryker.Core.Reporters.HtmlReporter.ProcessWrapper.WebbrowserOpener.Open(String path)
   at Stryker.Core.Reporters.Html.reporter.HtmlReporter.OnAllMutantsTested(IReadOnlyProjectComponent reportComponent)
   at Stryker.Core.Reporters.BroadcastReporter.OnAllMutantsTested(IReadOnlyProjectComponent reportComponent)
   at Stryker.Core.StrykerRunner.RunMutationTest(IStrykerInputs inputs, ILoggerFactory loggerFactory, IProjectOrchestrator projectOrchestrator)
   at Stryker.CLI.StrykerCli.RunStryker(IStrykerInputs inputs) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 93
   at Stryker.CLI.StrykerCli.<>c__DisplayClass10_0.<Run>b__0() in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 68
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass143_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Stryker.CLI.StrykerCli.Run(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 74
   at Stryker.CLI.Program.Main(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/Program.cs:line 14
```

**Additional context**

We should try to borrow from the way azure cli/msal does this instead of simply trying to start the html report as a file:

https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/a506d6e5c72d32161a238172c4da5efbde96da9d/msal/application.py#L1816

https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/a506d6e5c72d32161a238172c4da5efbde96da9d/msal/oauth2cli/authcode.py#L51

**Comment by xandervedder** [comment]
To open, we should know if we are running in wsl (not sure how that is possible), and prepend the file url with the following:
`file://///wsl.localhost/Ubuntu/{path}` where `path` is `home/mobrockers/git/stryker/stryker-net/integrationtest/TargetProjects/NetCoreTestProject.XUnit/StrykerOutput/2023-04-14.11-12-32/reports/mutation-report.html`

But i'm not sure if wsl always runs using Ubuntu...

**Comment by rouke-broersma** [comment]
In the implementations I've found so far they simply use powershell to do the path translation:

```
    if not browser_opened and is_wsl():
        try:
            import subprocess
            # https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_powershell_exe
            # Ampersand (&) should be quoted
            exit_code = subprocess.call(
                ['powershell.exe', '-NoProfile', '-Command', 'Start-Process "{}"'.format(auth_uri)])
            browser_opened = exit_code == 0
        except FileNotFoundError:  # WSL might be too old
            pass
```

If it works for them it should work for us.
