### ISSUE TITLE
Error 400 uploading report to dashboard

### ISSUE THREAD

**Issue by NelsonBN** [stryker-mutator/stryker-net#2513]
**Describe the bug**
I'm getting a 400 error when trying to send my report to the dashboard in version 3.8.2 with version 3.8.0 it worked perfectly

**Logs**
Version: 3.8.2
```bash
[03:49:07 ERR] Failed to upload report to the dashboard at https://dashboard.stryker-mutator.io/api/reports/github.com/................
System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Stryker.Core.Clients.DashboardClient.PublishReport(JsonReport report, String version) in /_/src/Stryker.Core/Stryker.Core/Clients/DashboardClient.cs:line 48
[03:49:07 ERR] Uploading to stryker dashboard failed...
```

Version: 3.8.0
```bash
Your report has been uploaded at:
https://dashboard.stryker-mutator.io/................
You can open it in your browser of choice.
```

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Windows and GitAction ubuntu-latest
 - Type of project classlib
 - Framework Version .NET 7.0
 - Stryker Version 3.8.2

**Comment by rouke-broersma** [comment]
Thanks for reporting, this is mentioned in #2510
