### ISSUE TITLE
Unhandled LINQ exception during solution run

### ISSUE THREAD

**Issue by psfinaki** [stryker-mutator/stryker-net#2551]
**Describe the bug**
Mmmm this will be a bad bug report :D But basically I am getting this in the solution mode for 3.9.0:

```
[00:31:37 INF] Time Elapsed 08:49:21.3589196
Unhandled exception. System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Stryker.Core.Initialisation.ProjectMutator.EnrichTestProjectsWithTestInfo(InitialTestRun initialTestRun, TestProjectsInfo testProjectsInfo) in /_/src/Stryker.Core/Stryker.Core/Initialisation/ProjectMutator.cs:line 46
   at Stryker.Core.Initialisation.ProjectMutator.MutateProject(StrykerOptions options, MutationTestInput input, IReporter reporters) in /_/src/Stryker.Core/Stryker.Core/Initialisation/ProjectMutator.cs:line 34
   at Stryker.Core.Initialisation.ProjectOrchestrator.MutateProjects(StrykerOptions options, IReporter reporters, ITestRunner runner)+MoveNext() in /_/src/Stryker.Core/Stryker.Core/Initialisation/ProjectOrchestrator.cs:line 62
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Stryker.Core.StrykerRunner.RunMutationTest(IStrykerInputs inputs, ILoggerFactory loggerFactory, IProjectOrchestrator projectOrchestrator) in /_/src/Stryker.Core/Stryker.Core/StrykerRunner.cs:line 60
   at Stryker.CLI.StrykerCli.RunStryker(IStrykerInputs inputs) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 93
   at Stryker.CLI.StrykerCli.<>c__DisplayClass10_0.<Run>b__0() in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 68
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass143_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Stryker.CLI.StrykerCli.Run(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/StrykerCLI.cs:line 74
   at Stryker.CLI.Program.Main(String[] args) in /_/src/Stryker.CLI/Stryker.CLI/Program.cs:line 14
```

**Additional context**
I struggle to understand what project I am getting this for, prior to that I see some messages like `Number of tests found: A for project B.csproj. Initial test run started.` and `Stryker.NET encountered an compile error in C.cs with message: Use of unassigned local variable 'D' (Source code: D)` - not sure this is related.

If it's not obvious for you what could have triggered the problem, I can try reproducing it but it will take some time, since it takes Stryker hours to figure out the solution mode execution for our huge repo and sometimes it runs out of memory.

**Comment by dupdob** [comment]
This is a variant of #2538, which happens when the same test file appears in two different mutated projects.
Here, it happens when some test file appears more than once for 1 (one) mutated project.
I am not sure this actually relates to solution mode: it should happen for any project where multiple test projects have some source file(s) in common

**Comment by psfinaki** [comment]
Hmm I will check and let you know, hopefully tomorrow.

**Comment by psfinaki** [comment]
So, @dupdob, yes your suggestion is quite likely. 

We have this `TestUtilities` project, which is basically an Xunit wrapper with things like `[ConditionalFact]` etc. It's used in multiple test projects. I generated a smaller SDK (like, 50 projects as opposed to 500 projects) with several test projects making use of `TestUtilities` and yeah this exploded in the same manner.
