### ISSUE TITLE
Unable to rollback mutation

### ISSUE THREAD

**Issue by chris579** [stryker-mutator/stryker-net#269]
Stryker fails to rollback mutations for several nodes.

```
Version 0.7.0 (beta)

[10:48:59 INF] Using C:\foo\bar.csproj as project file
[10:48:59 INF] Starting initial build
[10:49:04 INF] Initial build successful
[10:49:05 INF] Using testrunner DotnetTestRunner
[10:49:05 INF] Initial testrun started
[10:49:40 INF] Total number of tests found in initial test run: 0
[10:49:40 INF] Initial testrun successful in 34437 ms
[10:49:40 INF] Using 81655 ms as testrun timeout
[10:49:41 INF] 949 mutants created
[10:49:43 ERR] Unable to rollback mutation for node reader with diagnostic message Der Name "reader" ist im aktuellen Kontext nicht vorhanden.
[10:49:43 ERR] Unable to rollback mutation for node command with diagnostic message Der Name "command" ist im aktuellen Kontext nicht vorhanden.
[10:49:43 ERR] Unable to rollback mutation for node mySqlConnection with diagnostic message Der Name "mySqlConnection" ist im aktuellen Kontext nicht vorhanden.
[10:49:43 ERR] Unable to rollback mutation for node mySqlConnection with diagnostic message Der Name "mySqlConnection" ist im aktuellen Kontext nicht vorhanden.
[10:49:43 ERR] An error occurred during the mutation test run
System.ArgumentException: Der aufzuzeichnende Knoten ist kein untergeordnetes Element des Stamms.
   at Microsoft.CodeAnalysis.SyntaxNodeExtensions.TrackNodes[TRoot](TRoot root, IEnumerable`1 nodes) in /_/src/Compilers/Core/Portable/Syntax/SyntaxNodeExtensions_Tracking.cs:line 43
   at Stryker.Core.Compiling.RollbackProcess.RemoveMutantIfStatements(SyntaxTree originalTree, ICollection`1 diagnosticInfo)
   at Stryker.Core.Compiling.RollbackProcess.Start(CSharpCompilation compiler, ImmutableArray`1 diagnostics)
   at Stryker.Core.Compiling.CompilingProcess.Compile(IEnumerable`1 syntaxTrees, MemoryStream ms)
   at Stryker.Core.MutationTest.MutationTestProcess.Mutate()
   at Stryker.Core.StrykerRunner.RunMutationTest(StrykerOptions options)
[10:49:43 INF] Time Elapsed 00:00:43.7736487
```

We have some database integration tests in our unit tests. Maybe this is related to the error.

**Comment by richardwerkman** [comment]
This error should have nothing to do with your test project. Could you run again with `--log-console trace` to find more information about what kind of mutation causes this error?

**Comment by chris579** [comment]
As this output contains the code itself (and therefore sensitive parts) I'm not allowed to post the output here. I may send it to a member privately.

**Comment by richardwerkman** [comment]
It may not be needed to send parts of the code. If you can create a simple example project that recreates the issue we could work with that.

If you can't recreate the issue you may send the output to my email and I'll look into it.

**Comment by chris579** [comment]
I've send you a mail.
