### ISSUE TITLE
Failed to generate source code for mutated assembly: error RZ3600: Invalid value ''' for RazorLangVersion. Valid values include 'Latest' or a valid version in range 1.0 to 8.0.

### ISSUE THREAD

**Issue by EMMPublisher** [stryker-mutator/stryker-net#2890]
**Describe the bug**
After execute the command dotnet-stryker I get the errors below. My solution don´t use Razor and there are not Razor Packages installed in any project of the solution.

**Logs**
[16:17:54 WRN] Failed to load analyzer 'Microsoft.Extensions.Logging.Generators': Assembly with same name is already loaded (error : UnableToLoadAnalyzer, analyzer: All).
[16:17:54 WRN] Failed to load analyzer 'Microsoft.Extensions.Logging.Generators': Exception System.IO.FileLoadException: Assembly with same name is already loaded
   at System.Runtime.Loader.AssemblyLoadContext.<LoadFromPath>g____PInvoke|5_0(IntPtr __ptrNativeAssemblyBinder_native, UInt16* __ilPath_native, UInt16* __niPath_native, ObjectHandleOnStack __retAssembly_native)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerFileReference.Extensions`1.AddExtensions(Builder builder, String language, Func`2 shouldInclude).
[16:17:54 ERR] Failed to generate source code for mutated assembly: error RZ3600: Invalid value ''' for RazorLangVersion. Valid values include 'Latest' or a valid version in range 1.0 to 8.0.
[16:17:54 ERR] An error occurred during the mutation test run 

Source Generator Failure

[16:17:54 INF] Time Elapsed 00:03:06.4311472

**Desktop:**
 - OS: Windows 10
 - Type of project: NETCORE WEBAPI
 - Framework Version: NETCORE SDK 8.0 AND RUNTIME 8.0.200
 - Stryker Version 4.0.2

**Comment by rouke-broersma** [comment]
This looks like the same issue as #2881
