### ISSUE TITLE
Unable to rollback mutation with C# 7.3 or greater features

### ISSUE THREAD

**Issue by Matthiee** [stryker-mutator/stryker-net#310]
I cannot run stryker because I'm using C# 7.3 features. 

- `Feature 'default literal' is not available in C# 7.0. Please use language version 7.1 or greater.`
- `Unable to rollback mutation for node Enum with diagnostic message Feature 'enum generic type constraints' is not available in C# 7.0. Please use language version 7.3 or greater..`

```
[07:56:52 ERR] Failed to restore the project to a buildable state. Please report the issue. Stryker can not proceed further
[07:56:52 ERR] An error occurred during the mutation test run
System.ApplicationException: Failed to restore build able state.
   at Stryker.Core.Compiling.CompilingProcess.Compile(IEnumerable`1 syntaxTrees, MemoryStream ms, Boolean devMode)
   at Stryker.Core.MutationTest.MutationTestProcess.Mutate(StrykerOptions options)
   at Stryker.Core.StrykerRunner.RunMutationTest(StrykerOptions options)
```

**Comment by richardwerkman** [comment]
Thank you for your input. I was able to reproduce this issue and solved it. I'll open a PR fixing this now.
