### ISSUE TITLE
System.OutOfMemoryException when generating HTML Report with class with many covered tests 

### ISSUE THREAD

**Issue by pkunze** [stryker-mutator/stryker-net#3126]
**Describe the bug**
We having trouble generating the HTML report. We are mutating a class which is covered by *a lot* of tests. 
Now, the generated json file is approx 1.5 GB large and generating the HTML Report fails as can be seen below.

Working around by turning coverage analysis off works, but doesn't really help, since the mutation test will run very long in this case. 

**Logs**
```
An error occurred during the mutation test run 
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.String.CreateStringFromEncoding(Byte* bytes, Int32 byteLength, Encoding encoding)
   at System.Text.Encoding.GetString(ReadOnlySpan`1 bytes)
   at System.Text.Json.JsonReaderHelper.TranscodeHelper(ReadOnlySpan`1 utf8Unescaped)
   at System.Text.Json.JsonSerializer.WriteString[TValue](TValue& value, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   at Stryker.Core.Reporters.Json.JsonReportSerialization.ToJson(IJsonReport report) in /_/src/Stryker.Core/Stryker.Core/Reporters/Json/JsonReportSerialization.cs:line 45
   at Stryker.Core.Reporters.Json.JsonReportSerialization.ToJsonHtmlSafe(IJsonReport report) in /_/src/Stryker.Core/Stryker.Core/Reporters/Json/JsonReportSerialization.cs:line 47
   at Stryker.Core.Reporters.Html.HtmlReporter.WriteHtmlReport(String filePath, IReadOnlyProjectComponent reportComponent, ITestProjectsInfo testProjectsInfo) in /_/src/Stryker.Core/Stryker.Core/Reporters/Html/HtmlReporter.cs:line 111
   at Stryker.Core.Reporters.Html.HtmlReporter.OnAllMutantsTested(IReadOnlyProjectComponent reportComponent, ITestProjectsInfo testProjectsInfo) in /_/src/Stryker.Core/Stryker.Core/Reporters/Html/HtmlReporter.cs:line 43
   at Stryker.Core.Reporters.BroadcastReporter.OnAllMutantsTested(IReadOnlyProjectComponent reportComponent, ITestProjectsInfo testProjectsInfo) in /_/src/Stryker.Core/Stryker.Core/Reporters/BroadcastReporter.cs:line 59
   at Stryker.Core.StrykerRunner.RunMutationTest(IStrykerInputs inputs, ILoggerFactory loggerFactory, IProjectOrchestrator projectOrchestrator) in /_/src/Stryker.Core/Stryker.Core/StrykerRunner.cs:line 105
Dem müssten wir dann eigentlich mal einen K... x Kunze, Paul
```
**Expected behavior**
It would be great if there would be options to work around this without turning test coverage analysis off.
Maybe an option to disable the inclusion of covered tests in the HTML Report would do the job just fine? 
Other than that, i have no idea how to solve this.

**Desktop (please complete the following information):**
 - OS: Windows 11, Windows Server 2019
 - Type of project: core
 - Framework Version: .NET 8
 - Stryker Version: 4.4.1

**Comment by rouke-broersma** [comment]
An option to turn off inclusion of test results in the json report seems fine to me. Perhaps there could also be a way for us to improve the handing of the json serialization so that we don't use so much memory. 1.5 gigs is insane for a report! Pretty sure that's the largest we've ever seen.

**Comment by EraYaN** [comment]
We have the same error, but no Json file is even created. And if we use the `-o` switch the process dies right after this log line

```
 Version: 4.16.0

[14:18:21 INF] Analysis starting.
[14:18:21 INF] Analyzing 1 test project(s).
[14:18:25 INF] Found project .\sot\sot.csproj to mutate.
[14:18:25 INF] Analysis complete.
[14:18:25 INF] Building test project .\tests\tests.csproj (1/1)
[14:18:26 INF] Building project tests.csproj using dotnet build tests.csproj -c Debug --property:Platform=AnyCPU (directory .\tests.)
[14:18:29 WRN] The Microsoft Test Platform testrunner is currently in preview. Results should be verified since this feature is still being tested.
[14:18:30 INF] Number of tests found: 7549 for project .\sot\sot.csproj. Initial test run started.
[14:18:37 INF] 3471 mutants created
[14:18:37 INF] Capture mutant coverage using 'CoverageBasedTest' mode.
[14:18:37 INF] Starting coverage capture for MTP runner
[14:18:39 INF] Coverage capture complete: 2548 mutations covered, 4 static mutations
[14:18:44 ERR] An error occurred during the mutation test run
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Text.Json.JsonReaderHelper.TranscodeHelper(ReadOnlySpan`1 utf8Unescaped)
   at System.Text.Json.JsonSerializer.WriteString[TValue](TValue& value, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   at Stryker.Core.Reporters.Json.JsonReportSerialization.ToJson(IJsonReport report) in /_/src/Stryker.Core/Stryker.Core/Reporters/Json/JsonReportSerialization.cs:line 45
   at Stryker.Core.Reporters.Json.JsonReportSerialization.ToJsonHtmlSafe(IJsonReport report) in /_/src/Stryker.Core/Stryker.Core/Reporters/Json/JsonReportSerialization.cs:line 47
   at Stryker.Core.Reporters.Html.HtmlReporter.WriteHtmlReport(String filePath, IReadOnlyProjectComponent reportComponent, ITestProjectsInfo testProjectsInfo) in /_/src/Stryker.Core/Stryker.Core/Reporters/Html/HtmlReporter.cs:line 124
   at Stryker.Core.Reporters.Html.HtmlReporter.OnMutantsCreated(IReadOnlyProjectComponent reportComponent, ITestProjectsInfo testProjectsInfo) in /_/src/Stryker.Core/Stryker.Core/Reporters/Html/HtmlReporter.cs:line 76
   at Stryker.Core.Reporters.BroadcastReporter.OnMutantsCreated(IReadOnlyProjectComponent reportComponent, ITestProjectsInfo testProjectsInfo) in /_/src/Stryker.Core/Stryker.Core/Reporters/BroadcastReporter.cs:line 26
   at Stryker.Core.StrykerRunner.RunMutationTestAsync(IStrykerInputs inputs) in /_/src/Stryker.Core/Stryker.Core/StrykerRunner.cs:line 77
[14:18:44 INF] Time Elapsed 00:00:23.2585414
Out of memory.
```

This is on about 23k lines of C# code. (xUnit.v3 v4, using the new MTP runner.)

The machine has about 36 GB of RAM free before starting the test, so the allocation must be huge.

.NET 10
Windows 11 x64
Same error on Ubuntu 24.04 (via WSL, process allocates about 7 to 8 GB before crashing which is easier to see on linux)

EDIT: tried it on a much bigger machine (300GB + free RAM, and it still fails)

**Comment by dupdob** [comment]
thanks for opening this issue. I lack experience with this part of the project, but I still wondering why it gets so big. 
Do you use a lot of theories and/or large parameters for those (such as long strings)?

**Comment by EraYaN** [comment]
We do use a lot of Theories (about 1280), but mostly with say 5-30 enum values (like 95% of them), sometimes some tuples. There are also a couple that have some objects, quite large (100 fields total, across 2 or 3 levels on nesting), but then it wil be 1 or 2 variants per test.

When I ignore a bunch the json is only 150MB and most of that seems to be "coveredBy" in the ignored sets "Removed by mutate filter"

`jq 'del(.. | .coveredBy?)' mutation-report.json >mutation-report-nocoveredby.json`


```
-rwxrwxrwx 1 user group 151731489 Sep  8 17:08 mutation-report.json
-rwxrwxrwx 1 user group   2511951 Sep 15 14:52 mutation-report-nocoveredby.json
```

count the array sizes:
`jq 'walk(if type == "object" and has("coveredBy") then .coveredByCount = ((.coveredBy // []) | length) | del(.coveredBy) else . end)' mutation-report.json >mutation-report-nocoveredby-counts.json`

The coveredBy array all have 7562 guids, which all seem to be duplicated for each test and for each mutation

This specific run was run with this config (for 1 file for example `UniqueFile.cs`)

```
"stryker-config": {
    "test-runner": "mtp",
    "mutate": [ "**/UniqueFile.cs" ],
    "reporters": [ "progress", "html", "json", "markdown" ],
    "mutation-level": "Complete",
    "ignore-methods": [ "ToString", "ConfigureAwait", "ThrowIfNull", "*Exception.ctor", "Console.Write*" ]
  }
```
When running with 5.0.0 the JSON seems smaller (only 25Mb)
When running without a filter the resulting json is about 114 MB and the HTML get generated just fine.

**Comment by rouke-broersma** [comment]
MTP did not have any coverage information so all mutants were reported as covered by all unit tests. In 5.0.0 we have coverage information for MTP which explains why the report is so much smaller.
