### ISSUE TITLE
VsTest runner fails if log folder does not exist

### ISSUE THREAD

**Issue by dupdob** [stryker-mutator/stryker-net#389]
When using VsTest as the (test) runner, an exception is raised if the log folder does not exists.

````
System.ArgumentException: LogFilePath must point to a valid directory for logging!
   at Microsoft.TestPlatform.VsTestConsole.TranslationLayer.ConsoleParameters.set_LogFilePath(String value)
   at Stryker.Core.TestRunners.VsTest.VsTestRunner.PrepareVsTestConsole() in C:\Users\dupdo\source\repos\stryker-net\src\Stryker.Core\Stryker.Core\TestRunners\VsTest\VsTestRunner.cs:line 204
   at Stryker.Core.TestRunners.VsTest.VsTestRunner..ctor(StrykerOptions options, ProjectInfo projectInfo, Nullable`1 testCasesDiscovered) in C:\Users\dupdo\source\repos\stryker-net\src\Stryker.Core\Stryker.Core\TestRunners\VsTest\VsTestRunner.cs:line 53
   at Stryker.Core.TestRunners.VsTest.VsTestRunnerPool..ctor(StrykerOptions options, ProjectInfo projectInfo) in C:\Users\dupdo\source\repos\stryker-net\src\Stryker.Core\Stryker.Core\TestRunners\VsTest\VsTestRunnerPool.cs:line 20
   at Stryker.Core.TestRunners.TestRunnerFactory.Create(StrykerOptions options, ProjectInfo projectInfo) in C:\Users\dupdo\source\repos\stryker-net\src\Stryker.Core\Stryker.Core\TestRunners\TestRunnerFactory.cs:line 39
   at Stryker.Core.Initialisation.InitialisationProcess.Initialize(StrykerOptions options) in C:\Users\dupdo\source\repos\stryker-net\src\Stryker.Core\Stryker.Core\Initialisation\InitialisationProcess.cs:line 55
   at Stryker.Core.StrykerRunner.RunMutationTest(StrykerOptions options) in C:\Users\dupdo\source\repos\stryker-net\src\Stryker.Core\Stryker.Core\StrykerRunner.cs:line 65
```

**Comment by Mobrockers** [comment]
This is fixed in the branch for #352. This should be merged soon. Thanks for reporting!
