### ISSUE TITLE
Stryker failed to run when the Nuget package Microsoft.Testplatform.Portable is not in user nuget cache folder

### ISSUE THREAD

**Issue by kwlin** [stryker-mutator/stryker-net#440]
The command dotnet stryker fails with the following message when the Microsoft.Testplatform.Portable is not in the user Nuget cache (example: c:\users\<username>\.nuget\packages folder.

```

   _____ _              _               _   _ ______ _______
  / ____| |            | |             | \ | |  ____|__   __|
 | (___ | |_ _ __ _   _| | _____ _ __  |  \| | |__     | |
  \___ \| __| '__| | | | |/ / _ \ '__| | . ` |  __|    | |
  ____) | |_| |  | |_| |   <  __/ |    | |\  | |____   | |
 |_____/ \__|_|   \__, |_|\_\___|_| (_)|_| \_|______|  |_|
                   __/ |
                  |___/


Version 0.9.0 (beta)

[12:16:35 INF] Using C:\Src\Git\Vecozo.WebFormulieren\60-FEWebformulier\Implementation\Vecozo.FEWebformulier\Implementation.UnitTest\05-Implementation.UnitTest.csproj as project file
[12:16:48 WRN] Analyzer result not successful
[12:16:48 INF] Started initial build using msbuild.exe
[12:16:51 INF] Auto detected msbuild version 15.9.21.664 at: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe
[12:17:25 INF] Initial build successful
[12:17:25 INF] Using C:\Src\Git\Vecozo.WebFormulieren\60-FEWebformulier\Implementation\Vecozo.FEWebformulier\Implementation.UnitTest\05-Implementation.UnitTest.csproj as project file
[12:17:30 WRN] Analyzer result not successful
[12:17:31 INF] Started initial build using msbuild.exe
[12:17:34 INF] Auto detected msbuild version 15.9.21.664 at: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe
[12:18:06 INF] Initial build successful
[12:18:07 ERR] An error occurred during the mutation test run
System.AggregateException: One or more errors occurred. (Sequence contains no matching element) ---> System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at Stryker.Core.ToolHelpers.VsTestHelper.DeployEmbeddedVsTestBinaries() in C:\Git\decipherer\stryker-net\src\Stryker.Core\Stryker.Core\ToolHelpers\VsTestHelper.cs:line 176
   at Stryker.Core.ToolHelpers.VsTestHelper.GetVsTestToolPaths() in C:\Git\decipherer\stryker-net\src\Stryker.Core\Stryker.Core\ToolHelpers\VsTestHelper.cs:line 75
   at Stryker.Core.ToolHelpers.VsTestHelper.GetCurrentPlatformVsTestToolPath() in C:\Git\decipherer\stryker-net\src\Stryker.Core\Stryker.Core\ToolHelpers\VsTestHelper.cs:line 32
   at Stryker.Core.TestRunners.VsTest.VsTestRunner.PrepareVsTestConsole() in C:\Git\decipherer\stryker-net\src\Stryker.Core\Stryker.Core\TestRunners\VsTest\VsTestRunner.cs:line 177
   at Stryker.Core.TestRunners.VsTest.VsTestRunner..ctor(StrykerOptions options, ProjectInfo projectInfo, IFileSystem fileSystem, ILogger logger) in C:\Git\decipherer\stryker-net\src\Stryker.Core\Stryker.Core\TestRunners\VsTest\VsTestRunner.cs:line 45
   at Stryker.Core.TestRunners.VsTest.VsTestRunnerPool.<>c__DisplayClass3_0.<.ctor>b__0(Int32 i, ParallelLoopState loopState) in C:\Git\decipherer\stryker-net\src\Stryker.Core\Stryker.Core\TestRunners\VsTest\VsTestRunnerPool.cs:line 25
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`2 body)
   at Stryker.Core.TestRunners.VsTest.VsTestRunnerPool..ctor(StrykerOptions options, ProjectInfo projectInfo) in C:\Git\decipherer\stryker-net\src\Stryker.Core\Stryker.Core\TestRunners\VsTest\VsTestRunnerPool.cs:line 27
   at Stryker.Core.TestRunners.TestRunnerFactory.Create(StrykerOptions options, ProjectInfo projectInfo) in C:\Git\decipherer\stryker-net\src\Stryker.Core\Stryker.Core\TestRunners\TestRunnerFactory.cs:line 31
   at Stryker.Core.Initialisation.InitialisationProcess.Initialize(StrykerOptions options) in C:\Git\decipherer\stryker-net\src\Stryker.Core\Stryker.Core\Initialisation\InitialisationProcess.cs:line 60
   at Stryker.Core.StrykerRunner.RunMutationTest(StrykerOptions options) in C:\Git\decipherer\stryker-net\src\Stryker.Core\Stryker.Core\StrykerRunner.cs:line 46
---> (Inner Exception #0) System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at Stryker.Core.ToolHelpers.VsTestHelper.DeployEmbeddedVsTestBinaries() in C:\Git\decipherer\stryker-net\src\Stryker.Core\Stryker.Core\ToolHelpers\VsTestHelper.cs:line 176
   at Stryker.Core.ToolHelpers.VsTestHelper.GetVsTestToolPaths() in C:\Git\decipherer\stryker-net\src\Stryker.Core\Stryker.Core\ToolHelpers\VsTestHelper.cs:line 75
   at Stryker.Core.ToolHelpers.VsTestHelper.GetCurrentPlatformVsTestToolPath() in C:\Git\decipherer\stryker-net\src\Stryker.Core\Stryker.Core\ToolHelpers\VsTestHelper.cs:line 32
   at Stryker.Core.TestRunners.VsTest.VsTestRunner.PrepareVsTestConsole() in C:\Git\decipherer\stryker-net\src\Stryker.Core\Stryker.Core\TestRunners\VsTest\VsTestRunner.cs:line 177
   at Stryker.Core.TestRunners.VsTest.VsTestRunner..ctor(StrykerOptions options, ProjectInfo projectInfo, IFileSystem fileSystem, ILogger logger) in C:\Git\decipherer\stryker-net\src\Stryker.Core\Stryker.Core\TestRunners\VsTest\VsTestRunner.cs:line 45
   at Stryker.Core.TestRunners.VsTest.VsTestRunnerPool.<>c__DisplayClass3_0.<.ctor>b__0(Int32 i, ParallelLoopState loopState) in C:\Git\decipherer\stryker-net\src\Stryker.Core\Stryker.Core\TestRunners\VsTest\VsTestRunnerPool.cs:line 25
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---
```

**Comment by kwlin** [comment]
Maybe it's related with: #407 ?

**Comment by Mobrockers** [comment]
It seems stryker failed to deploy vstest for some reason. Will look into it tomorrow.

**Comment by Mobrockers** [comment]
@kwlin Which RC version are you using? I remember fixing an issue like this in the last RC

**Comment by Mobrockers** [comment]
The only place where Single is used in that class is in the following code:

```
var vstestZip = typeof(VsTestHelper).Assembly
                .GetManifestResourceNames()
                .Single(r => r.Contains("Microsoft.TestPlatform.Portable"));
```

This resource is available in the RC packages:

![image](https://user-images.githubusercontent.com/3595932/55613405-ea543000-578a-11e9-872b-dbca303ce1be.png)

Are you perhaps using a custom packaged version where the resource files might not be available?

**Comment by richardwerkman** [comment]
This should be fixed within #371

**Comment by kwlin** [comment]
@Mobrockers  I was testing with a custom build based on the pull request of https://github.com/stryker-mutator/stryker-net/pull/428

**Comment by Mobrockers** [comment]
Ah. We nuget restore the portable nuget package to a folder in the project in our build pipeline and then include it as an embedded resource. If you packaged your own tool package then you most likely did not perform the manual nuget restore required and thus did not have the portable vstest package available to include as resource.

I would suggest download the package from the integration test nuget feed if you want to change: https://www.myget.org/feed/Packages/stryker-mutator-integrationtest

You can also just run the stryker cli project on your project to test from visual studio.
