### ISSUE TITLE
Running Stryker against .Net Core Application on Ubuntu throws exception

### ISSUE THREAD

**Issue by vinnytheviking** [stryker-mutator/stryker-net#486]
Good Morning,

I'm trying to run Stryker on Ubuntu and getting the following exception

_[08:03:25 ERR] An error occurred during the mutation test run 
System.AggregateException: One or more errors occurred. (Count cannot be less than zero.
Parameter name: count) ---> System.ArgumentOutOfRangeException: Count cannot be less than zero.
Parameter name: count
   at System.String.Ctor(Char c, Int32 count)
   at Stryker.Core.Reporters.Progress.ConsoleOneLineLogger.ClearLine()
   at Stryker.Core.Reporters.Progress.ConsoleOneLineLogger.ReplaceLog(String text, Object[] args)
   at Stryker.Core.Reporters.Progress.ProgressBarReporter.ReportRunTest()
   at Stryker.Core.Reporters.Progress.ProgressReporter.OnMutantTested(IReadOnlyMutant result)
   at Stryker.Core.Reporters.BroadcastReporter.OnMutantTested(IReadOnlyMutant result)
   at Stryker.Core.MutationTest.MutationTestProcess.<Test>b__29_1(Mutant mutant)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 list, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body)
   at Stryker.Core.MutationTest.MutationTestProcess.Test(StrykerOptions options)
   at Stryker.Core.StrykerRunner.RunMutationTest(StrykerOptions options)
---> (Inner Exception #0) System.ArgumentOutOfRangeException: Count cannot be less than zero.
Parameter name: count
   at System.String.Ctor(Char c, Int32 count)
   at Stryker.Core.Reporters.Progress.ConsoleOneLineLogger.ClearLine()
   at Stryker.Core.Reporters.Progress.ConsoleOneLineLogger.ReplaceLog(String text, Object[] args)
   at Stryker.Core.Reporters.Progress.ProgressBarReporter.ReportRunTest()
   at Stryker.Core.Reporters.Progress.ProgressReporter.OnMutantTested(IReadOnlyMutant result)
   at Stryker.Core.Reporters.BroadcastReporter.OnMutantTested(IReadOnlyMutant result)
   at Stryker.Core.MutationTest.MutationTestProcess.<Test>b__29_1(Mutant mutant)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---_

Running locally on my windows machine works and I can see the 1 mutation successfully completing

Any Ideas ?

**Comment by richardwerkman** [comment]
I see that we request the `Console.WindowWidth` [there](https://github.com/stryker-mutator/stryker-net/blob/e9b3030e5d489f090ab297268dc98c81abc0d946/src/Stryker.Core/Stryker.Core/Reporters/Progress/ConsoleOneLineLogger.cs#L59). It looks like this .NET Core property returns a negative value on your machine. This could be a bug in .NET Core? What version of .NET Core are you running?

Maybe upgrading to a newer version will resolve your issue?

**Comment by vinnytheviking** [comment]
We use .NET Standard 2.0.3 and .NET Core 2.2.0

**Comment by richardwerkman** [comment]
@vinnytheviking did upgrading your .net core version work? 

If not you could disable the progressbar reporter. The exception arrises from that reporter. I suggest something like:

```
"reporters": [
     "ConsoleProgressDots",
     "Html"
]
```
By enabling the ConsoleProgressDots reporter you still have an indication of progress.

**Comment by Mobrockers** [comment]
@vinnytheviking Does this problem still crash stryker when running on ubuntu?

**Comment by vinnytheviking** [comment]
Stryker is running fine on ubuntu. We have the issue of not being able to run it against our .net core 3 projects at the moment #804

**Comment by Mobrockers** [comment]
Thanks for the update! Unfortunately I am not able to reproduce that issue at the moment, stryker runs fine in our pipelines :/
