### ISSUE TITLE
Stryker fails to find all rollbackable mutations

### ISSUE THREAD

**Issue by bbenetskyy** [stryker-mutator/stryker-net#531]
**Describe the bug**
We have one test project **XXX.Tests** it is **.Net Core 2.1**, it have references to two **.Net Standard 2.0** projects - **XXX.Api** & **XXX.Core**

With **XXX.Core** project all working as expected, thanks.

But for **XXX.Api** it fails with exception

**Logs**
```bat
[09:07:06 INF] Started initial build using dotnet build
[09:07:09 INF] Initial build successful
[09:07:09 INF] Using testrunner DotnetTest
[09:07:09 INF] Initial testrun started
[09:07:13 INF] Total number of tests found in initial test run: 0
[09:07:13 INF] Initial testrun successful in 3532 ms
[09:07:13 INF] Using 105298 ms as testrun timeout
[09:07:16 WRN] Stryker.NET encountered an compile error in C:\Work\XX\XXX.Api\Clients\XXXX.cs with message: Argument 2: cannot convert from 'System.Exception' to 'System.Runtime.Serialization.StreamingContext' (Source code: innerException)
[09:07:16 WRN] Safe Mode! Stryker will try to continue by rolling back all mutations in method. This should not happen, please report this as an issue on github with the previous error message.
[09:07:16 FTL] Stryker.NET could not compile the project after mutation. This is probably an error for Stryker.NET and not your project. Please report this issue on github with the previous error message.
[09:07:16 ERR] An error occurred during the mutation test run
System.ApplicationException: Internal error due to compile error.
   at Stryker.Core.Compiling.RollbackProcess.RemoveMutantIfStatements(SyntaxTree originalTree, ICollection`1 diagnosticInfo, Boolean devMode) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Compiling\RollbackProcess.cs:line 191
   at Stryker.Core.Compiling.RollbackProcess.Start(CSharpCompilation compiler, ImmutableArray`1 diagnostics, Boolean devMode) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Compiling\RollbackProcess.cs:line 61
   at Stryker.Core.Compiling.CompilingProcess.TryCompilation(MemoryStream ms, CSharpCompilation compilation, EmitResult previousEmitResult, Boolean devMode, Int32 retryCount) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Compiling\CompilingProcess.cs:line 108
   at Stryker.Core.Compiling.CompilingProcess.Compile(IEnumerable`1 syntaxTrees, MemoryStream ms, Boolean devMode) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Compiling\CompilingProcess.cs:line 76
   at Stryker.Core.MutationTest.MutationTestProcess.Mutate(StrykerOptions options) in D:\a\1\s\src\Stryker.Core\Stryker.Core\MutationTest\MutationTestProcess.cs:line 91
   at Stryker.Core.StrykerRunner.RunMutationTest(StrykerOptions options) in D:\a\1\s\src\Stryker.Core\Stryker.Core\StrykerRunner.cs:line 77
[09:07:16 INF] Time Elapsed 00:00:14.8422309
```
**Expected behavior**
For **XXX.Api** same behavior as for **XXX.Core**:
```bat
[09:02:52 INF] Started initial build using dotnet build
[09:02:58 INF] Initial build successful
[09:02:58 INF] Using testrunner DotnetTest
[09:02:58 INF] Initial testrun started
[09:03:01 INF] Total number of tests found in initial test run: 0
[09:03:01 INF] Initial testrun successful in 3541 ms
[09:03:01 INF] Using 105311 ms as testrun timeout
[09:03:05 INF] 1 mutants could not compile and got status CompileError
[09:03:05 INF] 64 mutants ready for test

Your html report has been generated at:
 C:\Work\XX\XXX.UnitTests\StrykerOutput\2019-05-27.09-02-47\reports\mutation-report.html
You can open it in your browser of choice.
[09:04:49 INF] Time Elapsed 00:02:02.3004631
```

**Desktop (please complete the following information):**
 - OS: **Windows 10 x64**
 - Type of project **xamarin**
 - Framework Version **.Net Core 2.1** & **.Net Standard 2.0** 
 - Stryker Version **0.11.0**

**Comment by Mobrockers** [comment]
Could you run stryker with option -f and send us the logfile from C:\Work\XX\XXX.UnitTests\StrykerOutput\<timestamp>\logs or provide us with a reproducible sample?

**Comment by bbenetskyy** [comment]
[log-20190527.txt](https://github.com/stryker-mutator/stryker-net/files/3222471/log-20190527.txt)
Here is log file with `-f` option, thanks @Mobrockers  for fast response

**Comment by bbenetskyy** [comment]
@Mobrockers  should `stryker` works with `NUnit` and `XUnit` test frameworks? Maybe this also a part of problem?

Just try to run with `NUnit` on other .Net Core 2.1 project and it's immediatly fail by some `NUnit.Framework.Internal...` and short message from Stryker: `Stryker.NET failed to mutate your project`

**Comment by Mobrockers** [comment]
Stryker should work with any testframework that works in dotnet test or visual studio. We are failing to compile some part of your code in this case and we will need to investigate what we are missing to successfully compile. The issue seems to be in C:\Work\{{Project Folder}}\{{Project Name}}.Api\Clients\ApiGatewayClients.cs specifically, we're looking into it.

**Comment by bbenetskyy** [comment]
`ApiGatewayClients` file is autogenerated by NSWAG, after excluding this file, all works fine.

Have only two more questions.

1) With excluding that autogenerated file all works as expected, so should I close this issue or you still want to search for a root problem?

2)I will try to investigate what's wrong with `NUnit` tests. If does not find the answer should I create a new issue or add details under this one?

**Comment by Mobrockers** [comment]
We are investigating the root cause, this should not have happened as we have a fallback mechanism in case a mutation causes a compile failure. In your case it seems to have fallen through anyway. You can keep this issue open and we will implement a fix.

If you find out what's wrong with NUnit I would appreciate a new issue with details so we can investigate that as well.

**Comment by Mobrockers** [comment]
@bbenetskyy Is this still an issue?

**Comment by bbenetskyy** [comment]
Just check with that project with newer version it works for me 😊
