### ISSUE TITLE
Total number of tests parser fails to parse nunit result because output is not as expected

### ISSUE THREAD

**Issue by bbenetskyy** [stryker-mutator/stryker-net#555]
**Describe the bug**
Looks like it's not [Issue 531](https://github.com/stryker-mutator/stryker-net/issues/531) and it happens once per 5-7 runs.

**Logs**
Console Output for command `dotnet stryker -cp .\core-stryker-config.json -f`
```powershell
[10:33:32 INF] Started initial build using dotnet build
[10:33:35 INF] Initial build successful
[10:33:35 INF] Using testrunner DotnetTest
[10:33:35 INF] Initial testrun started
[10:33:39 INF] Total number of tests found in initial test run: 0
[10:33:39 INF] Initial testrun successful in 4048 ms
[10:33:39 INF] Using 106072 ms as testrun timeout
[10:33:43 INF] 1 mutants could not compile and got status CompileError
[10:33:43 INF] 56 mutants ready for test
[10:34:04 ERR] An error occurred during the mutation test run
System.AggregateException: One or more errors occurred. (Specified argument was out of the range of valid values.) ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at System.ReadOnlySpan`1.Slice(Int32 start, Int32 length)
   at Stryker.Core.Parsers.TotalNumberOfTestsParser.ParseTotalNumberOfTests(String testProcessRunnerOutput) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Parsers\TotalNumberOfTestsParser.cs:line 28
   at Stryker.Core.TestRunners.DotnetTestRunner.RunAll(Nullable`1 timeoutMS, Nullable`1 activeMutationId) in D:\a\1\s\src\Stryker.Core\Stryker.Core\TestRunners\DotnetTestRunner.cs:line 32
   at Stryker.Core.MutationTest.MutationTestExecutor.Test(Mutant mutant) in D:\a\1\s\src\Stryker.Core\Stryker.Core\MutationTest\MutationTestExecutor.cs:line 35
   at Stryker.Core.MutationTest.MutationTestProcess.<Test>b__29_2(Mutant mutant) in D:\a\1\s\src\Stryker.Core\Stryker.Core\MutationTest\MutationTestProcess.cs:line 174
   at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList`1 list, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body)
   at Stryker.Core.MutationTest.MutationTestProcess.Test(StrykerOptions options) in D:\a\1\s\src\Stryker.Core\Stryker.Core\MutationTest\MutationTestProcess.cs:line 169
   at Stryker.Core.StrykerRunner.RunMutationTest(StrykerOptions options) in D:\a\1\s\src\Stryker.Core\Stryker.Core\StrykerRunner.cs:line 80
---> (Inner Exception #0) System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at System.ReadOnlySpan`1.Slice(Int32 start, Int32 length)
   at Stryker.Core.Parsers.TotalNumberOfTestsParser.ParseTotalNumberOfTests(String testProcessRunnerOutput) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Parsers\TotalNumberOfTestsParser.cs:line 28
   at Stryker.Core.TestRunners.DotnetTestRunner.RunAll(Nullable`1 timeoutMS, Nullable`1 activeMutationId) in D:\a\1\s\src\Stryker.Core\Stryker.Core\TestRunners\DotnetTestRunner.cs:line 32
   at Stryker.Core.MutationTest.MutationTestExecutor.Test(Mutant mutant) in D:\a\1\s\src\Stryker.Core\Stryker.Core\MutationTest\MutationTestExecutor.cs:line 35
   at Stryker.Core.MutationTest.MutationTestProcess.<Test>b__29_2(Mutant mutant) in D:\a\1\s\src\Stryker.Core\Stryker.Core\MutationTest\MutationTestProcess.cs:line 174
   at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---
[10:34:04 INF] Time Elapsed 00:00:37.7564979
```
Logs:
[log-20190531.txt](https://github.com/stryker-mutator/stryker-net/files/3240561/log-20190531.txt)

**Expected behavior**
Like on most runs:
```powershell
[10:34:34 INF] Started initial build using dotnet build
[10:34:37 INF] Initial build successful
[10:34:37 INF] Using testrunner DotnetTest
[10:34:37 INF] Initial testrun started
[10:34:40 INF] Total number of tests found in initial test run: 0
[10:34:40 INF] Initial testrun successful in 3784 ms
[10:34:40 INF] Using 105676 ms as testrun timeout
[10:34:44 INF] 1 mutants could not compile and got status CompileError
[10:34:44 INF] 56 mutants ready for test

Your html report has been generated at:
 C:\Work\{{ProjectFolder}}\{{ProjectName}}.UnitTests\StrykerOutput\2019-05-31.10-34-29\reports\mutation-report.html
You can open it in your browser of choice.
[10:36:17 INF] Time Elapsed 00:01:48.6347714
```

**Desktop (please complete the following information):**
 - OS: **Windows 10**
 - Type of project **xamarin**
 - Framework Version **.Net Core 2.1 & .Net Standard 2.0**
 - Stryker Version **0.11.0**

**Comment by richardwerkman** [comment]
We parse the output that `dotnet test` gives us to find the number of test cases that were run. Given that the exception only occurs sometimes for you I guess that the `dotnet test` command gives unexpected output sometimes. Maybe we could improve the parsing to check first if the output looks like we expect it.

Another solution would be to remove the parser as a whole, since it has given us more trouble before and it doesn't add that much value anyway...

**Comment by Si1ver** [comment]
I hit similar issue and made a pr #556. It might fix your case as well.
