### ISSUE TITLE
Compilation error when running against a Xamarin project with a Views Namespace

### ISSUE THREAD

**Issue by Project4MobileDev** [stryker-mutator/stryker-net#572]
Running Stryker.NET fails with a compilation error instead of listing mutants that were killed/survived. The same solution compiles fine in VS.

**Steps to reproduce:**
1. Clone [Example project](https://github.com/Project4MobileDev/Stryker.Net.Xamarin.Views.Namespace.Issue)
2. Go to `[REPO]/Source/Example/Module/Tests`
3. Run `dotnet stryker`

```
   _____ _              _               _   _ ______ _______
  / ____| |            | |             | \ | |  ____|__   __|
 | (___ | |_ _ __ _   _| | _____ _ __  |  \| | |__     | |
  \___ \| __| '__| | | | |/ / _ \ '__| | . ` |  __|    | |
  ____) | |_| |  | |_| |   <  __/ |    | |\  | |____   | |
 |_____/ \__|_|   \__, |_|\_\___|_| (_)|_| \_|______|  |_|
                   __/ |
                  |___/


Version 0.11.0 (beta)

[10:37:05 INF] Using D:\Repository\Stryker.Net.Xamarin.Views.Namespace.Issue\Source\Example\Module\Tests\Example.Module.UnitTests.csproj as project file
[10:37:16 INF] File D:\Repository\Stryker.Net.Xamarin.Views.Namespace.Issue\Source\Example\Module\UI\ExampleModule.cs will be excluded from mutation.
[10:37:16 INF] Started initial build using dotnet build
[10:37:19 INF] Initial build successful
[10:37:19 INF] Using testrunner DotnetTest
[10:37:19 INF] Initial testrun started
[10:37:21 INF] Total number of tests found in initial test run: 0
[10:37:21 INF] Initial testrun successful in 2419 ms
[10:37:21 INF] Using 13628 ms as testrun timeout
[10:37:23 WRN] Original project under test D:\Repository\Stryker.Net.Xamarin.Views.Namespace.Issue\Source\Example\Module\UI\bin\Debug\netstandard2.0\Example.Module.dll could not be loaded.
Embedded Resources might be missing.
Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Xamarin.Forms.Xaml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'
   at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at Mono.Cecil.DefaultAssemblyResolver.Resolve(AssemblyNameReference name)
   at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
   at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
   at Mono.Cecil.SignatureReader.ReadCustomAttributeEnum(TypeReference enum_type)
   at Mono.Cecil.SignatureReader.ReadCustomAttributeElement(TypeReference type)
   at Mono.Cecil.SignatureReader.ReadCustomAttributeConstructorArguments(CustomAttribute attribute, Collection`1 parameters)
   at Mono.Cecil.MetadataReader.ReadCustomAttributeSignature(CustomAttribute attribute)
   at Mono.Cecil.CustomAttribute.<Resolve>b__35_0(CustomAttribute attribute, MetadataReader reader)
   at Mono.Cecil.ModuleDefinition.Read[TItem](TItem item, Action`2 read)
   at Mono.Cecil.CustomAttribute.get_ConstructorArguments()
   at Mono.Cecil.ImmediateModuleReader.ReadCustomAttributes(ICustomAttributeProvider provider)
   at Mono.Cecil.ImmediateModuleReader.ReadModule(ModuleDefinition module, Boolean resolve_attributes)
   at Mono.Cecil.ModuleDefinition.Read[TItem](TItem item, Action`2 read)
   at Mono.Cecil.ModuleReader.CreateModule(Image image, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at Stryker.Core.Initialisation.EmbeddedResourcesGenerator.LoadModule(String assemblyPath, ILogger logger) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Initialisation\EmbeddedResourcesGenerator.cs:line 42
[10:37:23 WRN] Stryker.NET encountered an compile error in D:\Repository\Stryker.Net.Xamarin.Views.Namespace.Issue\Source\Example\Module\UI\ExampleModule.cs with message: The type or namespace name 'Views' does not exist in the namespace 'Example.Module' (are you missing an
 assembly reference?) (Source code: Views)
[10:37:23 WRN] Safe Mode! Stryker will try to continue by rolling back all mutations in method. This should not happen, please report this as an issue on github with the previous error message.
[10:37:23 FTL] Stryker.NET could not compile the project after mutation. This is probably an error for Stryker.NET and not your project. Please report this issue on github with the previous error message.
[10:37:23 ERR] An error occurred during the mutation test run
System.ApplicationException: Internal error due to compile error.
   at Stryker.Core.Compiling.RollbackProcess.RemoveMutantIfStatements(SyntaxTree originalTree, ICollection`1 diagnosticInfo, Boolean devMode) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Compiling\RollbackProcess.cs:line 191
   at Stryker.Core.Compiling.RollbackProcess.Start(CSharpCompilation compiler, ImmutableArray`1 diagnostics, Boolean devMode) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Compiling\RollbackProcess.cs:line 61
   at Stryker.Core.Compiling.CompilingProcess.TryCompilation(MemoryStream ms, CSharpCompilation compilation, EmitResult previousEmitResult, Boolean devMode, Int32 retryCount) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Compiling\CompilingProcess.cs:line 108
   at Stryker.Core.Compiling.CompilingProcess.Compile(IEnumerable`1 syntaxTrees, MemoryStream ms, Boolean devMode) in D:\a\1\s\src\Stryker.Core\Stryker.Core\Compiling\CompilingProcess.cs:line 76
   at Stryker.Core.MutationTest.MutationTestProcess.Mutate(StrykerOptions options) in D:\a\1\s\src\Stryker.Core\Stryker.Core\MutationTest\MutationTestProcess.cs:line 91
   at Stryker.Core.StrykerRunner.RunMutationTest(StrykerOptions options) in D:\a\1\s\src\Stryker.Core\Stryker.Core\StrykerRunner.cs:line 77
[10:37:23 INF] Time Elapsed 00:00:17.6031315
```

**Expected behavior**
Striker should compile the project and list mutants that were killed or survived.

 - OS: Windows 10
 - Type of project: Xamarin Forms v3.6.0.344457
 - Framework Version: core 2.2 (Example.Module.UnitTests), Standard 2.0 (Example.Module)
 - Stryker Version: 0.11.0 (beta)
```

**Comment by Project4MobileDev** [comment]
[log-20190610.txt](https://github.com/stryker-mutator/stryker-net/files/3273073/log-20190610.txt)

**Comment by Mobrockers** [comment]
Could you provide us with information on the Views namespace? Is that a Xamarin Forms library component?

**Comment by Project4MobileDev** [comment]
Hi! Apologies, I forgot to include a link to the [example project](https://github.com/Project4MobileDev/Stryker.Net.Xamarin.Views.Namespace.Issue).

Honestly, I'm not sure what exactly is causing the issue, so my description might be beside the point, but hopefully logs and the example project will let you get to the bottom of it.

**Comment by Mobrockers** [comment]
`*.xaml.cs` should not be excluded from compilation iirc, only from mutation. @richardwerkman right?

**Comment by p4dev** [comment]
@Mobrockers @richardwerkman is there any update on this? Is this being worked on? Is this an issue that is can't currently cannot be resolved?

**Comment by Mobrockers** [comment]
Hey @p4dev , we have identified the problem (xaml.cs files do contain source code sometimes, so cannot be excluded) but we do not yet know how to fix it, as simply including xaml.cs files in the compilation does not fix it. The compiler somehow generates some code for xaml.cs files during xamarin compilation and we have not yet identified how we can reproduce this.

**Comment by richardwerkman** [comment]
It looks like Xamarin support is not fully done. At first we thought that excluding the `*.xaml.cs` files was enough to run on the project. Now the strange thing is that it compiles perfectly as long as the view is not mentioned in any code.

We are looking into ways to include the xamarin generated code into our mutated assembly. We see two ways to do this:
- Get the code from the existing assembly after the initial build by decompiling the assembly and fetch the generated code.
- Use a Xamarin.Forms API to compile the xaml files into C# and create the generated code ourselves.

Both options don't seem ideal as they could break easily when Xamarin updates or when decompiling doesn't work correctly.

For now it is fair to say that xamarin support is very limited until this issue is tackled.

**Comment by felipebaltazar** [comment]
Hey everyone!
I've been able to solve this problem by copying the Xamarin.Forms.Xaml.dll from the `.nuget` folder to the working directory (normally project tests folder).
I tested in my personal projects and with attached sample on this issue

I opened a PR with a suggestion that copies the `Xamarin.Forms.Xaml.dll` to working directory
https://github.com/stryker-mutator/stryker-net/pull/1716
