### ISSUE TITLE
Unity3d project. Get "Expected exactly one .csproj" even when specifying the .csproj

### ISSUE THREAD

**Issue by MadsPB** [stryker-mutator/stryker-net#573]
**Describe the bug**
I'm attempting to run stryker on a unity3d project.
There are 4 project files in the project root of this project all generated by unity.
Assembly-CSharp-Editor.csproj <- our tests
Assembly-CSharp-Editor-firstpass.csproj <- plugins pre compiled by unity and referenced in the tests
Assembly-CSharp-firstpass.csproj <- plugins precompiled by unity and referenced in the producetion code
Assembly-CSharp.csproj <- production code to be mutated

I've tried running stryker with -p Assembly-CSharp.csproj
and i've included the following stryker-config.json
```
{
    "stryker-config":
    {    
        "solution-path":"word-show.sln",
        "project-file":"Assembly-CSharp.csproj"
    }
}
```

**Logs**
```
Version 0.11.0 (beta)

[23:56:25 DBG] Stryker started with options: {"BasePath":"/Users/mads/WorkSpaces/word-show","SolutionPath":"/Users/mads/WorkSpaces/word-show/word-show.sln","OutputPath":"/Users/mads/WorkSpaces/word-show/StrykerOutput/2019-06-11.23-56-25","Reporters":["Progress","ClearText"],"LogOptions":{"LogToFile":false,"OutputPath":"/Users/mads/WorkSpaces/word-show/StrykerOutput/2019-06-11.23-56-25","LogLevel":"Debug"},"DevMode":false,"ProjectUnderTestNameFilter":"Assembly-CSharp.csproj","AdditionalTimeoutMS":30000,"ExcludedMutations":[],"ConcurrentTestrunners":6,"Thresholds":{"High":80,"Low":60,"Break":0},"TestRunner":"DotnetTest","FilesToExclude":[]}
[23:56:25 INF] Time Elapsed 00:00:00.2474748
Stryker.NET failed to mutate your project. For more information see the logs below:

Expected exactly one .csproj file, found more than one:
/Users/mads/WorkSpaces/word-show/Assembly-CSharp-Editor.csproj
/Users/mads/WorkSpaces/word-show/Assembly-CSharp-Editor-firstpass.csproj
/Users/mads/WorkSpaces/word-show/Assembly-CSharp-firstpass.csproj
/Users/mads/WorkSpaces/word-show/Assembly-CSharp.csproj

Please fix your project contents
```

**Expected behavior**
I expected stryker to mutate the production code and run the tests in the test project.

**Desktop (please complete the following information):**
 - OS: macOS 10.14
 - Unity 2018.1.9f2, targeting .net 4.7
 - Stryker Version 0.11.0
- using NUnit test framework

**Additional context**
None of the guides or documentation mentioned any way to point to the test project. I'm uncertain how stryker knows which project contains the tests or if there is a specific naming convention.

I hope have some insight in how to make stryker run. I would really like to use it for our project.
Best Wishes, Mads

**Comment by Mobrockers** [comment]
We currently do not support having the test project and source project in the same directory. It is convention to have these in separate directories for most c# projects. Stryker knows which project is the test project because there would only be one csproj in the directory where you execute Stryker, which should be the test project directory.

Is this not a normal project structure for unity?

**Comment by MadsPB** [comment]
Unity is a bit different. It has an asset folder containing everything (usually in sub folder structures) from artwork to scripts. You can create assembly definitions and unity has some default ones. For each assembly definition unity then compiles the scripts into a .dll and generates a .csproj in the root folder. This happens every time you trigger a project sync. Which is usually whenever something is changed in unity or a script has been saved by an IDE.

I just tried created a new unity project, with two folders inside the Asset folder.
Assets/Scripts
Assets/Tests
with an assembly definition for each, one marked for tests, referencing the production definition.
Assets/Tests/TestAssembly.asmdef
Assets/Scripts/ProductionAssembly.asmdef

And my project root folder now has:
Assembly-csharp.csproj <- unity default csproj for csharp scripts
ProductionAssembly.csproj
TestAssembly.csproj

However! I tried creating a new folder in root
and then create a symlink to the TestAssembly.csproj 
named t/TestAssembly.csproj 
And that worked! Installing Stryker, and running it in the subfolder /t/ 
though i now get another error.

`Version 0.11.0 (beta)

[04:07:22 INF] Using /Users/mads/WorkSpaces/StrykerTest/t/TestAssembly.csproj as project file
[04:07:23 INF] Restoring nuget packages using nuget.exe
[04:07:23 ERR] An error occurred during the mutation test run 
System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Stryker.Core.Testing.ProcessExecutor.ProcessWrapper..ctor(ProcessStartInfo info, Boolean redirectOutput)
   at Stryker.Core.Testing.ProcessExecutor.RunProcess(ProcessStartInfo info, Int32 timeoutMS)
   at Stryker.Core.Testing.ProcessExecutor.Start(String path, String application, String arguments, IEnumerable`1 environmentVariables, Int32 timeoutMS)
   at Stryker.Core.Initialisation.ProjectFileReader.RestorePackages(String solutionPath)
   at Stryker.Core.Initialisation.ProjectFileReader.AnalyzeProject(String projectFilePath, String solutionFilePath)
   at Stryker.Core.Initialisation.InputFileResolver.ResolveInput(StrykerOptions options)
   at Stryker.Core.Initialisation.InitialisationProcess.Initialize(StrykerOptions options)
   at Stryker.Core.StrykerRunner.RunMutationTest(StrykerOptions options)`

**Comment by Mobrockers** [comment]
This page : https://docs.unity3d.com/Manual/testing-editortestsrunner.html

Shows a button called create test assembly folder. It suggests to me if you use that option unity will put the test project in a separate folder for you. Have you tried that?

**Comment by Mobrockers** [comment]
Could you show the contents of the test project csproj?

**Comment by MadsPB** [comment]
> https://docs.unity3d.com/Manual/testing-editortestsrunner.html

yes, but sadly it simply creates a folder with an assembly definition, and then compiles and generates the csproj in root.

**Comment by MadsPB** [comment]
> Could you show the contents of the test project csproj? Does it actually have a project reference?

<img width="506" alt="Screenshot 2019-06-12 at 05 28 08" src="https://user-images.githubusercontent.com/48548934/59321599-f4d2fe80-8cd2-11e9-98fa-e1fa5ba96d24.png">
<img width="470" alt="Screenshot 2019-06-12 at 05 26 48" src="https://user-images.githubusercontent.com/48548934/59321600-f56b9500-8cd2-11e9-8fd4-d2eee630ca57.png">

The csproj does seem to have a reference, both to script i'm trying to reference and to the actual ProductionAssembly.csproj

**Comment by Mobrockers** [comment]
Could you enable log to file and attach the resulting logfile? You can use -f on the command line to do so.

**Comment by Mobrockers** [comment]
I'm fairly confident we won't be able to get this working today unfortunately. Unity seems to be it's whole own little subsection of dotnet. I think it will require quite some effort to be able to compile unity projects as the project structure and references are very different from normal projects.

Would you be willing and able to work on this? With our help of course.

**Comment by MadsPB** [comment]
> Could you enable log to file and attach the resulting logfile? You can use -f on the command line to do so.
[log-20190612.txt](https://github.com/stryker-mutator/stryker-net/files/3279487/log-20190612.txt)

I'm afraid the logs don't say much more.


> Would you be willing and able to work on this? With our help of course.

Yes I would be very keen to work on this in my spare time. I think it's a really good concept you have going, and I would love to be able to use on our company code bases.

**Comment by Mobrockers** [comment]
Actually from the logging it looks like you ran stryker from the production folder instead of the test folder.

>Yes I would be very keen to work on this in my spare time. I think it's a really good concept you have going, and I would love to be able to use on our company code bases.

Awesome :) I'll write down some pointers when I get to work to help you get started.

**Comment by Mobrockers** [comment]
I created a project for you where we can track progress on this feature and I have added some initial issues for what I think needs to be implemented to implement unity support. See https://github.com/stryker-mutator/stryker-net/projects/2

**Comment by MadsPB** [comment]
You're right! mistakes are made in the late late hours.
this is what i get now:
```Version 0.11.0 (beta)

[11:30:53 DBG] Stryker started with options: {"BasePath":"/Users/mads/WorkSpaces/StrykerTest/t","SolutionPath":"/Users/mads/WorkSpaces/StrykerTest/StrykerTest.sln","OutputPath":"/Users/mads/WorkSpaces/StrykerTest/t/StrykerOutput/2019-06-12.11-30-53","Reporters":["Progress","ClearText"],"LogOptions":{"LogToFile":true,"OutputPath":"/Users/mads/WorkSpaces/StrykerTest/t/StrykerOutput/2019-06-12.11-30-53","LogLevel":"Debug"},"DevMode":false,"ProjectUnderTestNameFilter":"/Users/mads/WorkSpaces/StrykerTest/ProductionAssembly.csproj","AdditionalTimeoutMS":30000,"ExcludedMutations":[],"ConcurrentTestrunners":6,"Thresholds":{"High":80,"Low":60,"Break":0},"TestRunner":"DotnetTest","FilesToExclude":[]}
[11:30:53 INF] Using /Users/mads/WorkSpaces/StrykerTest/t/TestAssembly.csproj as project file
[11:30:53 DBG] Analyzing solution file /Users/mads/WorkSpaces/StrykerTest/StrykerTest.sln
[11:30:54 DBG] Analyzing project file /Users/mads/WorkSpaces/StrykerTest/t/TestAssembly.csproj
[11:30:55 INF] Time Elapsed 00:00:02.0362847
Stryker.NET failed to mutate your project. For more information see the logs below:

Project reference issue.

No project reference matched your --project-file=/Users/mads/WorkSpaces/StrykerTest/ProductionAssembly.csproj
Choose one of the following references:

  /Users/mads/WorkSpaces/StrykerTest/t/ProductionAssembly.csproj

Example: --project-file=/Users/mads/WorkSpaces/StrykerTest/t/ProductionAssembly.csproj```

**Comment by Mobrockers** [comment]
> It wants the production file to be in the same folder as the test file, likely because the reference is relative in the csproj.

We receive the project references as full paths from buildalyzer, an external tool:

https://github.com/stryker-mutator/stryker-net/blob/f0903d71537cb25058d7d1ec01b38ace006bfb11/src/Stryker.Core/Stryker.Core/Initialisation/InputFileResolver.cs#L57

**Comment by MadsPB** [comment]
Is there a Discord/Slack or other chat channel for easy communication?

**Comment by Mobrockers** [comment]
https://gitter.im/stryker-mutator/stryker-net

**Comment by Narmdo** [comment]
@MadsPB Did you get anywhere trying to get Stryker working with a Unity project in the end?

**Comment by CodeSmile-0000011110110111** [comment]
Is an estimate possible or know regarding how much effort it would take to make it compatible with Unity? Is it more like 20 hours or 20 days of work? 

Would the effort mainly be to adjust the project references, or is it about the nonstandard .NET used by Unity?

**Comment by rouke-broersma** [comment]
> Is an estimate possible or know regarding how much effort it would take to make it compatible with Unity? Is it more like 20 hours or 20 days of work? 
> 
> Would the effort mainly be to adjust the project references, or is it about the nonstandard .NET used by Unity?
> 

Hard to say since I have never used it, but from what I remember it seemed like it requires implementing most Stryker features in a different way. Someone has started the work, there's a pr with some changes.

**Comment by CodeSmile-0000011110110111** [comment]
Thanks, I‘ll have a look.

**Comment by dupdob** [comment]
I since it is more 20+ days than hours. you can look at PR #2388.
The problem is that Unity is a complete new platform with specific build and testing processes. Alas, Stryker needs strong coupling with both processes:
1) strong coupling with the build process as Stryker uses an _try and rollback if needed_ approach to mutation injection
2) strong coupling with testing as Stryker needs to streamline the testing phase as much as possible to keep realistic run time.

This coupling implies: a large initial effort to port existing logic to Unity build chain as well as continuous effort to reintegrate changes to the Stryker code base.

On the bright side, some stuff do not need to change:
1) mutators
2) reporting logic

**Comment by dupdob** [comment]
Duplicate. See #2381
