### ISSUE TITLE
System.AggregateException ... An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by sergiocabral** [stryker-mutator/stryker-net#813]
**Describe the bug**
During the execution of tests by stryker an exception with no associated explanation occurs. With this message: `System.AggregateException: One or more errors occurred. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host`

**Logs**
Source code of projet: `https://github.com/sergiocabral/Cabrones.Kli`
```
C:\Git\Kli\Test.Kli (master -> github)
λ dotnet stryker

   _____ _              _               _   _ ______ _______
  / ____| |            | |             | \ | |  ____|__   __|
 | (___ | |_ _ __ _   _| | _____ _ __  |  \| | |__     | |
  \___ \| __| '__| | | | |/ / _ \ '__| | . ` |  __|    | |
  ____) | |_| |  | |_| |   <  __/ |    | |\  | |____   | |
 |_____/ \__|_|   \__, |_|\_\___|_| (_)|_| \_|______|  |_|
                   __/ |
                  |___/

Version: 0.14.0 (beta)

[16:37:33 INF] The project C:\Git\Kli\Kli\Kli.csproj will be mutated
[16:37:34 INF] Started initial build using dotnet build
[16:37:37 INF] Initial build successful
[16:38:00 INF] Using testrunner VsTest
[16:38:00 INF] Total number of tests found: 371
[16:38:00 INF] Initial testrun started
[16:38:03 INF] Using 9617 ms as testrun timeout
[16:38:06 INF] 2 mutants got status CompileError. Reason: Could not compile
[16:38:06 INF] 138 mutants ready for test
[16:38:06 INF] Capture mutant coverage using 'perTest' mode.
[16:38:18 WRN] Failed to retrieve coverage info for Kli.Input.TestIInput.verifica_se_os_métodos_existem_com_base_na_assinatura.
[16:38:18 WRN] Failed to retrieve coverage info for Kli.Input.TestIInput.verifica_se_os_métodos_existem_com_base_na_assinatura.
[16:38:18 WRN] Failed to retrieve coverage info for Kli.Input.TestIInput.verifica_se_os_métodos_existem_com_base_na_assinatura.
[16:38:18 WRN] Failed to retrieve coverage info for Kli.Input.TestIInput.verifica_se_o_total_de_métodos_públicos_declarados_está_correto_neste_tipo.
[16:38:18 WRN] Failed to retrieve coverage info for Kli.i18n.TestITranslate.verifica_se_os_métodos_existem_com_base_na_assinatura.
[16:38:18 WRN] Failed to retrieve coverage info for Kli.i18n.TestITranslate.verifica_se_os_métodos_existem_com_base_na_assinatura.
[16:38:18 WRN] Failed to retrieve coverage info for Kli.i18n.TestITranslate.verifica_se_os_métodos_existem_com_base_na_assinatura.
[16:38:18 WRN] Failed to retrieve coverage info for Kli.i18n.TestITranslate.verifica_se_os_métodos_existem_com_base_na_assinatura.
[16:38:18 WRN] Failed to retrieve coverage info for Kli.i18n.TestITranslate.verifica_se_os_métodos_existem_com_base_na_assinatura.
[16:38:18 WRN] Failed to retrieve coverage info for Kli.i18n.TestITranslate.verifica_se_os_métodos_existem_com_base_na_assinatura.
[16:38:18 WRN] Failed to retrieve coverage info for Kli.i18n.TestITranslate.verifica_se_os_métodos_existem_com_base_na_assinatura.
[16:38:18 WRN] Failed to retrieve coverage info for Kli.i18n.TestITranslate.verifica_se_os_métodos_existem_com_base_na_assinatura.
[16:38:18 WRN] Failed to retrieve coverage info for Kli.i18n.TestITranslate.verifica_se_o_total_de_métodos_públicos_declarados_está_correto_neste_tipo.
[16:38:18 INF] Congratulations, all mutants are covered by tests!
[16:38:18 INF] Coverage analysis eliminated 93,52% of tests (i.e. 47879 tests out of 51198).

Testing mutant | ██████████ | 138 / 138 | 100 % | ~0m 00s |
Killed : 125
Survived: 7
Timeout : 6
[16:38:29 WRN] VsTest error occured. Please report the error at https://github.com/stryker-mutator/stryker-net/issues
System.AggregateException: One or more errors occurred. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.Stream.ReadByte()
   at System.IO.BinaryReader.ReadByte()
   at System.IO.BinaryReader.Read7BitEncodedInt()
   at System.IO.BinaryReader.ReadString()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.LengthPrefixCommunicationChannel.NotifyDataAvailable()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TcpClientExtensions.MessageLoopAsync(TcpClient client, ICommunicationChannel channel, Action`1 errorHandler, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
[16:38:45 WRN] VsTest error occured. Please report the error at https://github.com/stryker-mutator/stryker-net/issues
System.AggregateException: One or more errors occurred. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.Stream.ReadByte()
   at System.IO.BinaryReader.ReadByte()
   at System.IO.BinaryReader.Read7BitEncodedInt()
   at System.IO.BinaryReader.ReadString()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.LengthPrefixCommunicationChannel.NotifyDataAvailable()
   at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TcpClientExtensions.MessageLoopAsync(TcpClient client, ICommunicationChannel channel, Action`1 errorHandler, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
```

**Expected behavior**
No exceptions should occur.

**Desktop (please complete the following information):**
- OS: Windows 10
- Type of project: NET Core, Console Application
- Framework Version: netcoreapp3.0
- Stryker Version 0.14.0 (beta)

**Additional context**
N/A

**Comment by Mobrockers** [comment]
Thank you for the reports! This looks similar to other reports we are investigating.

**Comment by dupdob** [comment]
It looks like it is related to timeouts

**Comment by dupdob** [comment]
Actually, it is related to cancelling test runs. When Stryker cancels the test run, it triggers some race condition.

**Comment by dupdob** [comment]
Warning has been demoted to a lower logging level in PR #936
