### ISSUE TITLE
Stryker raises misleading error when initial tests failed unexpectedly

### ISSUE THREAD

**Issue by dupdob** [stryker-mutator/stryker-net#825]
**Describe the bug**
As seen in issue #821, it appears that Stryker fails to identify an issue when doing the initial test.
Processing is still blocked, but error message is confusing : 'the operation was cancelled'

**Logs**
> [10:02:30 INF] Using testrunner VsTest
[10:02:30 INF] Total number of tests found: 6
[10:02:30 INF] Initial testrun started
[10:02:30 DBG] Runner 4: VsTest runsettings set to: \<RunSettings>
> \<RunConfiguration>
> \<MaxCpuCount>4\</MaxCpuCount>
>  \<TargetFrameworkVersion>.NETCoreApp,Version = vnetcoreapp2.1\</TargetFrameworkVersion>
> \</RunConfiguration>
> \</RunSettings>
> [10:02:31 ERR] An error occurred during the mutation test run
System.OperationCanceledException: The operation was canceled.
   at Stryker.Core.TestRunners.VsTest.VsTestRunner.RunVsTest(IEnumerable`1 testCases, Nullable`1 timeoutMs, Dictionary`2 envVars) in d:\a\1\s\src\Stryker.Core\Stryker.Core\TestRunners\VsTest\VsTestRunner.cs:line 189
   at Stryker.Core.TestRunners.VsTest.VsTestRunner.RunAll(Nullable`1 timeoutMs, IReadOnlyMutant mutant) in d:\a\1\s\src\Stryker.Core\Stryker.Core\TestRunners\VsTest\VsTestRunner.cs:line 100
   at Stryker.Core.TestRunners.VsTest.VsTestRunnerPool.RunAll(Nullable`1 timeoutMs, IReadOnlyMutant mutant) in d:\a\1\s\src\Stryker.Core\Stryker.Core\TestRunners\VsTest\VsTestRunnerPool.cs:line 54
   at Stryker.Core.Initialisation.InitialTestProcess.InitialTest(ITestRunner testRunner) in d:\a\1\s\src\Stryker.Core\Stryker.Core\Initialisation\InitialTestProcess.cs:line 43
   at Stryker.Core.Initialisation.InitialisationProcess.InitialTest(StrykerOptions options, Int32& nbTests) in d:\a\1\s\src\Stryker.Core\Stryker.Core\Initialisation\InitialisationProcess.cs:line 63
   at Stryker.Core.StrykerRunner.RunMutationTest(StrykerOptions options, IEnumerable`1 initialLogMessages) in d:\a\1\s\src\Stryker.Core\Stryker.Core\StrykerRunner.cs:line 82
[10:02:31 INF] Time Elapsed 00:00:17.3768319

**Expected behavior**
The error message should clearly states that the initial test session crashed (different from having failing test(s)) and provides the specific reason when available.

**Comment by dupdob** [comment]
Working on it, will be integrated with #633.
