### ISSUE TITLE
An error occurred during the mutation test run : Internal error due to compile error

### ISSUE THREAD

**Issue by ggingras** [stryker-mutator/stryker-net#841]
Hi, 

When I tried to run stryker-net with my application in .Net fwk 4.7.2, I received the error below.

Maybe it is due to C# 7 new syntax : 

var fileName = openFileViewModel is IOpenFile vm ? vm.FullPath : string.Empty;

Here logs:
[log-20191206.txt](https://github.com/stryker-mutator/stryker-net/files/3933762/log-20191206.txt)
[vstest-log.txt](https://github.com/stryker-mutator/stryker-net/files/3933763/vstest-log.txt)

```
[13:36:57 WRN] Stryker.NET encountered an compile error in C:\Sources\Dev\CAD\CAD.Wpf.Logic\Commands\CreateAndOpenFileCommand.cs (at 122:145) with message: Use of unassigned local variable 'vm' (Source code: vm)
[13:38:07 WRN] Safe Mode! Stryker will try to continue by rolling back all mutations in method. This should not happen, please report this as an issue on github with the previous error message.
[13:38:08 WRN] Stryker.NET encountered an compile error in C:\Sources\Dev\CAD\CAD.Wpf.Logic\Memory\TransactionManagerBase.cs (at 10:22) with message: The namespace 'Emergensys.CAD.Wpf.Logic.Memory' already contains a definition for 'TransactionManagerStateEventHandler' (Source code: public delegate void TransactionManagerStateEventHandler(bool isDirty);)
[13:38:08 WRN] Safe Mode! Stryker will try to continue by rolling back all mutations in method. This should not happen, please report this as an issue on github with the previous error message.
[13:38:08 FTL] Stryker.NET could not compile the project after mutation. This is probably an error for Stryker.NET and not your project. Please report this issue on github with the previous error message.
[13:38:08 ERR] An error occurred during the mutation test run
System.ApplicationException: Internal error due to compile error.
   at Stryker.Core.Compiling.RollbackProcess.RemoveMutantIfStatements(SyntaxTree originalTree, ICollection`1 diagnosticInfo, Boolean devMode) in d:\a\1\s\src\Stryker.Core\Stryker.Core\Compiling\RollbackProcess.cs:line 193
   at Stryker.Core.Compiling.RollbackProcess.Start(CSharpCompilation compiler, ImmutableArray`1 diagnostics, Boolean devMode) in d:\a\1\s\src\Stryker.Core\Stryker.Core\Compiling\RollbackProcess.cs:line 60
   at Stryker.Core.Compiling.CompilingProcess.TryCompilation(MemoryStream ms, CSharpCompilation compilation, EmitResult previousEmitResult, Boolean devMode, Int32 retryCount) in d:\a\1\s\src\Stryker.Core\Stryker.Core\Compiling\CompilingProcess.cs:line 124
   at Stryker.Core.Compiling.CompilingProcess.Compile(IEnumerable`1 syntaxTrees, MemoryStream ms, Boolean devMode) in d:\a\1\s\src\Stryker.Core\Stryker.Core\Compiling\CompilingProcess.cs:line 92
   at Stryker.Core.MutationTest.MutationTestProcess.Mutate() in d:\a\1\s\src\Stryker.Core\Stryker.Core\MutationTest\MutationTestProcess.cs:line 124
   at Stryker.Core.StrykerRunner.RunMutationTest(StrykerOptions options, IEnumerable`1 initialLogMessages) in d:\a\1\s\src\Stryker.Core\Stryker.Core\StrykerRunner.cs:line 85
[13:38:08 INF] Time Elapsed 00:07:25.0264589
PS C:\Sources\Dev\CAD\CAD.Wpf.Logic.Test>
```

**Comment by dupdob** [comment]
Thanks for reporting this issue and thanks for providing needed details. After reviewing the log, I think there is two issues. The first one being that Stryker should not mutate this:
```csharp
var fileName = openFileViewModel is IOpenFile vm ? vm.FullPath : string.Empty;
```
but this is a minor issue, as safe mode can recover from this.

But the blocking issue lies elsewhere, with the duplicate definition of **TransactionManagerStateEventHandler**.
Reading the log, it looks that 'TransactionManagerBase.cs' file was mutated twice, as if it present somehow twice in the project.
Do you see any reason this could happen?

**Comment by ggingras** [comment]
Hi, 

You were right, the class was present twice in the file explorer, but not in my project solution.

We renamed the class, but the old file was still in the explorer structure. 

Since I provided csproj and sln path, I thought that Stryker used those to find all files, but I was wrong.

I deleted the old file and the error is gone.

Thanks for your help.

**Comment by Mobrockers** [comment]
@ggingras Awesome! We have been trying to work towards a system where we use to project files to get the source files, but this has proven to be difficult to implement, so for now we still gather the source files from the filesystem. We do hope in the future to change this, but the available tooling does not seem sufficient.

Closing because the issue has been fixed.
