### ISSUE TITLE
Static constructor with expression body syntax throws error

### ISSUE THREAD

**Issue by jasonwoods-7** [stryker-mutator/stryker-net#959]
**Describe the bug**
When a class has a static constructor using expression body syntax, the following exception is thrown when running the `dotnet stryker` command:

```
System.ArgumentException: Node to track is not a descendant of the root.
   at Microsoft.CodeAnalysis.SyntaxNodeExtensions.TrackNodes[TRoot](TRoot root, IEnumerable`1 nodes)
   at Stryker.Core.Mutants.MutantOrchestrator.MutateStaticConstructor(ConstructorDeclarationSyntax constructorDeclaration, MutationContext context) in d:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\MutantOrchestrator.cs:line 137
   at Stryker.Core.Mutants.MutantOrchestrator.Mutate(SyntaxNode currentNode, MutationContext context) in d:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\MutantOrchestrator.cs:line 104
   at Stryker.Core.Mutants.MutantOrchestrator.MutateExpression(SyntaxNode currentNode, MutationContext context) in d:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\MutantOrchestrator.cs:line 260
   at Stryker.Core.Mutants.MutantOrchestrator.Mutate(SyntaxNode currentNode, MutationContext context) in d:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\MutantOrchestrator.cs:line 132
   at Stryker.Core.Mutants.MutantOrchestrator.MutateExpression(SyntaxNode currentNode, MutationContext context) in d:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\MutantOrchestrator.cs:line 260
   at Stryker.Core.Mutants.MutantOrchestrator.Mutate(SyntaxNode currentNode, MutationContext context) in d:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\MutantOrchestrator.cs:line 132
   at Stryker.Core.Mutants.MutantOrchestrator.MutateExpression(SyntaxNode currentNode, MutationContext context) in d:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\MutantOrchestrator.cs:line 260
   at Stryker.Core.Mutants.MutantOrchestrator.Mutate(SyntaxNode currentNode, MutationContext context) in d:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\MutantOrchestrator.cs:line 132
   at Stryker.Core.Mutants.MutantOrchestrator.Mutate(SyntaxNode currentNode) in d:\a\1\s\src\Stryker.Core\Stryker.Core\Mutants\MutantOrchestrator.cs:line 81
   at Stryker.Core.MutationTest.MutationTestProcess.Mutate() in d:\a\1\s\src\Stryker.Core\Stryker.Core\MutationTest\MutationTestProcess.cs:line 90
   at Stryker.Core.StrykerRunner.RunMutationTest(StrykerOptions options, IEnumerable`1 initialLogMessages) in d:\a\1\s\src\Stryker.Core\Stryker.Core\StrykerRunner.cs:line 85
```

I've added a minimal [repro](https://github.com/jasonwoods-7/StaticConstructor) showing the issue.

**Logs**
Log file attached.
[log-20200225.txt](https://github.com/stryker-mutator/stryker-net/files/4251622/log-20200225.txt)

**Expected behavior**
No exception is thrown and the static constructor is correctly mutated.

**Desktop (please complete the following information):**
 - OS: Windows Server 2012 R2
 - Type of project: .Net Core
 - Framework Version: 3.1
 - Stryker Version: 0.16.0 (beta)

**Additional context**
I can work around the issue by changing the static constructor to use statement body syntax instead of expression body syntax.

**Comment by Mobrockers** [comment]
Thanks for the report!
